### ISSUE TITLE
Broken Method in LanguageMenuViewHelper, missing method GET

### ISSUE THREAD

**Issue by lukasgurschler** [FluidTYPO3/vhs#1006]
Wrong:

	protected function getLanguageUrl($uid) {
		$excludedVars = trim((string) $this->arguments['excludeQueryVars']);
		$config = array(
			'parameter' => $this->getPageUid(),
			'returnLast' => 'url',
			'additionalParams' => '&L=' . $uid,
			'useCacheHash' => $this->arguments['useCHash'],
			'addQueryString' => 'GET',
			'addQueryString.' => array(
				'exclude' => 'id,L,cHash' . ($excludedVars ? ',' . $excludedVars : '')
			)
		);
		if (TRUE === is_array($this->arguments['configuration'])) {
			$config = $this->mergeArrays($config, $this->arguments['configuration']);
		}
		return $this->cObj->typoLink('', $config);
	}

Right:

    protected function getLanguageUrl($uid) {
        $excludedVars = trim((string) $this->arguments['excludeQueryVars']);
        $config = array(
            'parameter' => $this->getPageUid(),
            'returnLast' => 'url',
            'additionalParams' => '&L=' . $uid,
            'useCacheHash' => $this->arguments['useCHash'],
            'addQueryString' => '1',
            'addQueryString.' => array(
                'exclude' => 'id,L,cHash' . ($excludedVars ? ',' . $excludedVars : ''),
                'method' => 'GET'
            )
        );
        if (TRUE === is_array($this->arguments['configuration'])) {
            $config = $this->mergeArrays($config, $this->arguments['configuration']);
        }
        return $this->cObj->typoLink('', $config);
    }

**Comment by bjo3rnf** [comment]
Fixed in ad215751
