### ISSUE TITLE
[BUG] SourceSetViewHelperTrait does not work with Media/ImageViewHelper and treatIdAsReference=true

### ISSUE THREAD

**Issue by BenjaminBeck** [FluidTYPO3/vhs#1011]
The Problem is ``vhs/Classes/Traits/SourceSetViewHelperTrait.php`` ``~L:44``
where ``$this->getImgResource`` does use the ``$src`` parameter which comes from
``vhs/Classes/ViewHelpers/Media/ImageViewHelper.php``  ``~L:77`` (``$this->mediaSource``) and is the path to the already processed image and not as required the file-reference-uid.

**Comment by bjo3rnf** [comment]
FIxed by #1013
