### ISSUE TITLE
v:page.menu does not handle "Hide at login" correctly

### ISSUE THREAD

**Issue by pvanhemmen** [FluidTYPO3/vhs#1014]
Pages with Access level "Hide at login" are never rendered in the menu, no matter if a user is logged in or not.

TYPO3 7.6.5
vhs 2.4.0

Thanx!
Paul

**Comment by bjo3rnf** [comment]
Hi Paul,

please try the current development branch of vhs. We refactored the menu viewhelpers and this issue should be fixed as well.

Cheers
Björn

**Comment by pvanhemmen** [comment]
Works as expected. You guys are awesome, thanx!
Closing this issue.
