### ISSUE TITLE
[TASK] Migration guide for v:page.menu to v:menu

### ISSUE THREAD

**Issue by jmverges** [FluidTYPO3/vhs#1016]
Hi there, 

We have a menu like:
             
`<v:page.menu doktypes="1,2,3,4,6,7,85,86">
         <ul class="nav navbar-nav navbar-right">
                <f:for each="{menu}" as="item" iteration="iteration">
                   <f:if condition="{item.hasSubPages}">`

- if I don't remove doktypes argument installation is broken.
- if I remove doktypes I don't see any submenu element but installation is good.

How we should migrate this? 
Was there some magic behind and now the magic is gone and we didn't register properly the doktypes in the cms?

Hugs,
Juan Manuel.

**Comment by cedricziel** [comment]
An error message would be very helpful :)

Apart from that the filtering by doctype has been removed if I'm correct. Ping @bjo3rnf

**Comment by bjo3rnf** [comment]
> Apart from that the filtering by doctype has been removed if I'm correct.

It looks like that, yes, but that was not intended at all. I'll fix that.

**Comment by jmverges** [comment]
Sorry, the error is: "doktype argument is not registered". Without doktype I don't get any error but subpages are not there.

**Comment by bjo3rnf** [comment]
There you go. Please test ;)

**Comment by bjo3rnf** [comment]
BTW: The viewhelper location also changed. It's v:menu now, v:page.menu is depracted.
