### ISSUE TITLE
v:media.extension vs v:media.size and white spaces in filenames

### ISSUE THREAD

**Issue by Geddo** [FluidTYPO3/vhs#1029]
Hey gang, I wanna use these two VH for extending my Fluidstyled MediaGallery. So got this:

```
<f:format.case value="{v:media.extension(file:'{f:uri.image(src: \'{column.media.link}\', treatIdAsReference:1)}')}" mode="upper"></f:format.case>-Download, 

<f:format.bytes value="{v:media.size(path: '{f:uri.image(src: \'{column.media.link}\', treatIdAsReference:1)}')}" decimals="2" ></f:format.bytes>
```
If I'm linking to an file with whitespaces in the name (like "test file.pdf") the second VH v:media.size throws an exception, while the first one works like charm. Why is that?

**Comment by bjo3rnf** [comment]
Hi @Geddo,

the vh throws two different exceptions. Which one is it in your case (i. e. what is the exception message you get)?

**Comment by bjo3rnf** [comment]
ping @Geddo ;)

**Comment by Geddo** [comment]
here you go:

`Oops, an error occurred!
Cannot determine size of "C:/xampp/htdocs/xxx/peter%20pan.pdf". File does not exist or is a directory.
More information regarding this error might be available online.`

So v:media.size breaks if the file contains a space, but v:media.extension doesnt

**Comment by bjo3rnf** [comment]
Ah, Windows... Thanks.

**Comment by bjo3rnf** [comment]
The thing is, v:media.extension doesn't check if the file exists as this is not required to determine the extension. v:media.size instead requires access to the actual file to determine its size. Since we use core methods to process the filename I'm afraid there's nothing we can do about it on our side and the problem should also occur in other situations outside of vhs. Didn't you encounter any yet?

**Comment by Geddo** [comment]
no yet. everything else works fine :-/

**Comment by bjo3rnf** [comment]
Hm. I suspect it's an issue with the white space in combo with Windows. Is the file uploaded via backend? Could you please test what happens if you rename it to ``peter_pan.pdf`` (not meant to be a fix of course)?

**Comment by bjo3rnf** [comment]
Closed due to lack of feedback. Feel free to reopen in case.
