### ISSUE TITLE
Argument "divider" was not registered.

### ISSUE THREAD

**Issue by MarkusBausK** [FluidTYPO3/vhs#1030]
Hi,

I always used the breadcrumb-viewhelper in that way: `<v:page.breadCrumb linkCurrent="0" class="breadcrumb" divider=">"entryLevel="1"/> `There was no problem but since (I really don't know it exactly) TYPO3 7.6.something the system is throwing the following exception: 

Uncaught TYPO3 Exception
#1237823695: Argument "divider" was not registered. (More information)

TYPO3\CMS\Fluid\Core\Parser\Exception thrown in file
/html/typo3/typo3_src-7.6.6/typo3/sysext/fluid/Classes/Core/Parser/TemplateParser.php in line 604.

If I delete the divider argument everything is working fine.

Greetings

**Comment by bjo3rnf** [comment]
Hi @MarkusBausK,

thanks for reporting. This seems to be gone lost during a recent refactoring of the menu viewhelpers. I'll fix that.

Cheers
Björn
