### ISSUE TITLE
v:page.header.* does not work with non-caching plugins

### ISSUE THREAD

**Issue by Juburin** [FluidTYPO3/vhs#1034]
When using v:page.header.meta or other v:page.header.* ViewHelpers (except title) they will not be rendered if called from a template of a non-caching plugin.
I think that this is the real problem of #696.

**Comment by NamelessCoder** [comment]
This one depends on PageRenderer and I'm afraid the conclusion is that if PageRenderer doesn't support this completely, neither will any of the `v:page.header.*` ViewHelpers. Note that PageRenderer may also be influenced by hooks during generating the page and indeed, it does not work the same way in all cases.

The technical reason for it is that `USER_INT` contents are *replaced into the output via markers* so the plugin does not actually execute until after the page, including header and footer, has been built. The generated HTML is simply `str_replace`d - that way a common HTML can be cached for performance and only the uncached parts need to be generated on each request. It's not a super integration friendly method (it stems way back from the start of TYPO3) but it is currently the only uncached output method, with the exception of completely disabling the cache, obviously.

If you wish to improve PageRenderer then by all means please do report an issue or feature request in the TYPO3 core bug tracker!

**Comment by Juburin** [comment]
Thank your for clearing that up.
