### ISSUE TITLE
v:media.picture with absrefprefix wrong path

### ISSUE THREAD

**Issue by cybergwei** [FluidTYPO3/vhs#1035]
using v:media.picture in combination with absrefprefix = / results in wrong path examp: //fileadmin/....

**Comment by bjo3rnf** [comment]
Can you please give some details on how you use the viewhelper? The src argument is not processed in any way so the path has to be manipulated before that by something else, thanks.

**Comment by bjo3rnf** [comment]
Closed due to lack of feedback and possibly not caused by vhs itself. Feel free to reopen.
