### ISSUE TITLE
v:page.resources.fal struggles with translated pages which have deleted versions

### ISSUE THREAD

**Issue by MichaelNussbaumerGOWEST** [FluidTYPO3/vhs#1038]
Hello,

i found out that the "v:page.resources.fal" Viewhelper has a problem if you have for example a page which is translated.
Example: 
 - You create a translation of default language with sys_language_uid 4
 - You delete the translation
 - Later you create again a translation for sys_language_uid 4
 - You synchronize the ressources from default language
 - The Viewhelper doesn't find the images
 - Go to database and search for the deleted translation in pages_language_overlay
 - Delete the "deleted=1" record by DELETE FROM pages_language_overlay WHERE uid = XX 
 - Now the Viewhelper finds the Files

It seems that the Viewhelper doesn't respect the "deleted" flag of pages_language_overlay. 

Regards

**Comment by NamelessCoder** [comment]
Fixed by https://github.com/FluidTYPO3/vhs/commit/f0a49f2de30290901c2206ddc5b2ca149148a6d8 but not yet released to TER. If you need this one quickly you can check out the `development` branch of VHS - but I think there will be a new VHS 3.0.0 release shortly.
