### ISSUE TITLE
Pages with access restrictions don't appear in menus

### ISSUE THREAD

**Issue by JostBaron** [FluidTYPO3/vhs#1039]
Don't know if it's fixed by know (I've seen a menu viewhelper refactoring since 2.4.0).

When having two pages in a (directory) menu rendered using `v:page.menu.directory`, and those two pages have the access restriction "Show on any login" and "Hide at login", none of them is ever rendered in the menu.

This happens in TYPO3 7.6.7 with vhs 2.4.0. It works with vhs 2.3.3.

**Comment by bjo3rnf** [comment]
Hi Jost,

mind giving the current development branch here on GitHub a try? Access restriction related behavior should work as expected and a new release is about to be published soon. Thanks.

Cheers
Björn

**Comment by NamelessCoder** [comment]
Closing this one since we've tested and retested the new feature. Of course it isn't released yet - but soon!
