### ISSUE TITLE
Non-static "once" view helpers

### ISSUE THREAD

**Issue by kraftb** [FluidTYPO3/vhs#1043]
The "once" view helpers derive from the "AbstractOnceViewHelper" which in turn derives from the "AbstractConditionViewHelper". The "AbstractConditionViewHelper" implements the "CompilableInterface". Thus all "once" view helpers should implement the "renderStatic" method which they aren't.

Thus the "once" view helpers will only get called during the first rendering of the page after clearing all caches. For subsequent page renderings (even after clearing the FE cache) the view helper methods wont' get called again.

In an example I try to add the class "active" to a bootstrap carousel item - but only for the first rendered slider element. This does work after clearing all caches but when pressing shift-reload the "active" class doesn't get added.

I do not really know how to easily solve this issue. I guess all "once" view helpers have to get rewritten to use static methods. I do not know if this is possible at all for all kinds of "once" view helpers. Eventually they must not derive from "AbstractConditionViewHelper" or the "AbstractConditionViewHelper" must not implement the "compilableInterface". This could get solved by creating a "AbstractThenElseViewHelper" which acts as basis for the "AbstractConditionViewHelper" (splitting it up). The "once" view helpers could then use the "AbstractThenElseViewHelper" and would not need to implement the CompilableInterface any more. Of course this would require changes in the TYPO3 cores "fluid" extension.

**Comment by NamelessCoder** [comment]
Please see https://forge.typo3.org/issues/73565 - we will insist that the problem is the incorrect application of CompilableInterface (and compile method) on AbstractConditionViewHelper in the TYPO3 core. Implementing it correctly as described on the link above will automatically solve this issue for every condition ViewHelper at the same time.
