### ISSUE TITLE
[BUG] v:content.render slide does not work

### ISSUE THREAD

**Issue by ste101** [FluidTYPO3/vhs#1049]
For me `<v:content.render column="1" slide="-1" as="heroUnitContentElements">` does not work anymore in TYPO3 7.6 and vhs 2.4.0 and latest github version.
Is this a vhs bug or a core bug?

**Comment by ste101** [comment]
Could anyone give me a hint please.

**Comment by NamelessCoder** [comment]
Record sliding, including content record sliding, hasn't been changed in a good while. If you can include some more information about your actual setup that might help. In addition you may be affected by a number of core regressions but it is impossible to tell without knowing exactly what your page structure is, how your content is placed on those pages, whether workspaces is involved, if pages or content is translated and more.

Generally speaking though: content sliding should still work if the structures you use are compatible with sliding (same column, not nested, rendered in page not content template, same language or using `content_fallback` and knowing about current limitations with that fallback, etc).

**Comment by sdfghasdfg** [comment]
<v:content.render column="0" slide="-1" slideCollect="-1" slideCollectReverse="1"/>

1. slide="-1" is working well but not slide="0", slide="1"...
2. slideCollectReverse: There is no differenz if I use "1" or "0"
3. slideCollect: Is working well with "-1" but not with "1"...

**Comment by sdfghasdfg** [comment]
System is T3 7.6.16
vhs is 4.1.0

**Comment by sdfghasdfg** [comment]
<div xmlns="http://www.w3.org/1999/xhtml" lang="en"
	 xmlns:v="http://typo3.org/ns/FluidTYPO3/Vhs/ViewHelpers"
	 xmlns:f="http://typo3.org/ns/fluid/ViewHelpers">

<f:layout name="Partial"/>
	
	<f:section name="RecursivePageContent">
		<div class="page-header container">
			<v:content.render column="0" slide="-1" slideCollect="-1" slideCollectReverse="1"/>
		</div>
	</f:section>
</div>
This snippet collects the content reversal for each page in the page tree as expected. But slideCollectReverse is broken, slide only works with -1.

Love you, thx
