### ISSUE TITLE
Composer Update cannot resolve requirements

### ISSUE THREAD

**Issue by Lumrenion** [FluidTYPO3/vhs#1050]
As long as the composer.json file contains false information about the PHP version requirement,  if you are developing in a PHP 7 environment, you are unable to call **composer update**.
I am aware of the **composer update --ignore-platform-reqs** command. This command should not be a long term solution.

For this I would highly appreciate it if @bjo3rnf's commit from March 25th (@see https://github.com/FluidTYPO3/vhs/commit/88ae050119ac88e53296b19842cf7e7545e30947) would make it into a new version of vhs soon.

For the record:
> Your requirements could not be resolved to an installable set of packages.
>
>  Problem 1
>    - typo3-ter/vhs 2.4.0 requires php >= 5.4.0, <= 5.6.99 -> your PHP version (7.0.4) does not satisfy that requirement.
>    - typo3-ter/vhs 2.4.0 requires php >= 5.4.0, <= 5.6.99 -> your PHP version (7.0.4) does not satisfy that requirement.
>    - Installation request for typo3-ter/vhs ^2.4 -> satisfiable by typo3-ter/vhs[2.4.0].

**Comment by NamelessCoder** [comment]
Already scheduled for next TER release.
