### ISSUE TITLE
[TASK] Remove v:uri.typolink

### ISSUE THREAD

**Issue by ste101** [FluidTYPO3/vhs#1051]
and v:link.typolink.
In TYPO3 7.6 there is a viewhelper f:link.typolink

**Comment by cedricziel** [comment]
I don't think that's reasonable. Last time i looked, the core viewhelper didn't work the way you'd expect. - What is your experience?

**Comment by ste101** [comment]
My tests with ID, _blank, email and external link where successful.

**Comment by NamelessCoder** [comment]
I think the Fluid variants of these should be good enough at this point (since 7.6 LTS at least). They more or less lifted them from VHS so yep, they should work ;)

**Comment by bjo3rnf** [comment]
Deprecate or remove right away? The signature is a little different and there's `f:link.typolink` as well as `f:uri.typolink`.

**Comment by NamelessCoder** [comment]
Good question... how different are the signatures? If the essential arguments are the same we could leave empty classes subclassing the fluid classes - and inform that they will be removed in for example VHS 3.2.0 or 4.0.0 whichever comes first. If they're very different maybe a hard removal is best, seeing as we're about to do a new major version bump.

**Comment by cedricziel** [comment]
I thought we follow semver - which would leave us with the option to remove them in 4.0.0, but not 3.2.0.

**Comment by NamelessCoder** [comment]
Cedric with the "gotcha!" Yep, 4.0.0 ;)

**Comment by cedricziel** [comment]
^^

**Comment by danielkestler** [comment]
See my PR. It's just a suggestion ... I tried it by subclassing the Fluid viewhelpers first, but it didn't work out probably because of different method signatures (I thought these could be overwritten in the subclass, but it just didn't work) – so now the Fluid viewhelpers' renderStatic methods are called.

**Comment by bjo3rnf** [comment]
Hi Daniel,

I like your approach. Mind taking care of `v:link.typolink` as well?

Cheers
Björn

**Comment by bjo3rnf** [comment]
Oh, nvm. You already did. Sorry. ^^

**Comment by danielkestler** [comment]
No problem ;) Yes I did, and already did update the documentation for it – it was wrong IMO.
