### ISSUE TITLE
Error in FE after installing vhs

### ISSUE THREAD

**Issue by mhagenbruch** [FluidTYPO3/vhs#1056]
I get this error in FE directly after installing vhs
Fatal error: Call to a member function usePageCache() on a non-object in /vagrant/typo3_src/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php on line 3163
how can i solve this??

**Comment by NamelessCoder** [comment]
Your TYPO3 site is unable to create an instance of `AssetService` from VHS. Please check the following:

* Make sure you use composer to install and have ran `composer install`
* Make sure you've cleared the temporary files in `typo3temp`

https://github.com/FluidTYPO3/fluidcontent/pull/356 may also have an effect here if you use fluidcontent; if you installed all extensions in a dependency graph at the same time, fluidcontent may have caused an error that prevented other extensions from for example flushing system caches. But I suspect the composer issue is the one you face.
