### ISSUE TITLE
Shortcut contentUid ordering

### ISSUE THREAD

**Issue by haraldkrischner** [FluidTYPO3/vhs#1070]
With no order given it should use the order of the IDs you give in.

contentUids="3,4,6" would otherwise result in rather random ordering. "sorting" is default ordering, but the given uids could reside on different pages.

**Comment by NamelessCoder** [comment]
Please use `order` argument on the ViewHelper to control this one.

**Comment by haraldkrischner** [comment]
`order` will use DB fields. But when I pick content element from different pages there is no common DB attribute to accurately order these elements.

**Comment by NamelessCoder** [comment]
An empty string as `order` will do it - see https://github.com/FluidTYPO3/vhs/blob/development/Classes/ViewHelpers/Content/AbstractContentViewHelper.php#L147
