### ISSUE TITLE
media picture crop is missing

### ISSUE THREAD

**Issue by HaraldDolderer** [FluidTYPO3/vhs#1071]
sorry, heading is misleading. usage of image processing is the problem.

with css styled content installed you are able to use the image processing in 7.6 for images in content elements. It seems the viewhelper media picture unfortunately has no ability to use this great feature. 
Is this planed to include in the near future?
Thank you for your reply.

kind regards
Harald

**Comment by bjo3rnf** [comment]
Hi,

please see #853.

Cheers
Björn

**Comment by NamelessCoder** [comment]
Closing with reference to #853 and note that cropping is defined for each `v:media.source` inside the `v:media.picture` container.
