### ISSUE TITLE
v:render.uncache doesn't respect partialRootPaths

### ISSUE THREAD

**Issue by smichaelsen** [FluidTYPO3/vhs#1075]
Though `v:render.uncache` should be usable just like `f:render` there's an important difference: When you rely on non-standard `partialRootPaths` your partials won't be found/resolved correctly.

That's because the "uncached" rendering is done with a new view object (`UncacheTemplateView`), which doesn't get the path settings from the view object that is rendering the rest of the templates.

Immediately, I didn't get a good idea how to pass those settings properly - but maybe someone else does.

**Comment by smichaelsen** [comment]
I implemented a fix for myself. Don't know if this is a beautiful solution though.
https://gist.github.com/smichaelsen/6d76c7afaf050741441dd083f6e29939

**Comment by typo3ua** [comment]
When I use this Helper <v:render.uncache/> get the error:

=My code:
``
<v:render.uncache partial="Subscription/Form" arguments="{_all}"/>
``
=Error:
``
Oops, an error occurred!
TYPO3 Fatal Error: Extension key "" is NOT loaded!
More information regarding this error might be available online.
``
Why?

**Comment by typo3ua** [comment]
I found this [solution ...](https://www.stephan-meier.com/vhsrender-uncache-viewhelper-typo3-fatal-error/)

**Comment by NamelessCoder** [comment]
Solved by https://github.com/FluidTYPO3/vhs/commit/530649c52bc5629ecae7a22b428c7c09a17a3769

**Comment by smichaelsen** [comment]
@NamelessCoder I guess #1163 should also be closed then.
