### ISSUE TITLE
3.0.0 "stable" includes broken code

### ISSUE THREAD

**Issue by cobalamin** [FluidTYPO3/vhs#1079]
This bugfix:
https://github.com/FluidTYPO3/vhs/commit/9cca3a8fdd58951356a95187c5700cf03ee21afd

is pretty integral for the extension to work - especially the fix on [line 180](https://github.com/FluidTYPO3/vhs/commit/9cca3a8fdd58951356a95187c5700cf03ee21afd#diff-56f3f4c49f9c4d997940062ff8ba69beR180), but it's **not** included in the 3.0.0 release, which was 15 days ago. The 3.0.0 release thus isn't stable and there should at least be a 3.0.1 release that includes this fix.

**Comment by cedricziel** [comment]
Exactly, I think that one slipped through although we fast-merged it. Thanks for the hint.

I think @NamelessCoder will take care of a release shortly.

Ref: #1068

**Comment by NamelessCoder** [comment]
3.0.1 released.
