### ISSUE TITLE
v:page.menu and doktype sysfolder

### ISSUE THREAD

**Issue by Atsyn** [FluidTYPO3/vhs#1081]
I use page with doktype sysfolder in pageUid. And menu doesn't rendered.
Code look like:
```
<vhs:page.menu pageUid="{settings.pages.footer}" as="blocks" doktypes="254">
...
</vhs:page.menu>
```
I found a problem in \FluidTYPO3\Vhs\Service\PageService function getPageConstraints
Problem part:
```
$constraints[] = 'doktype NOT IN (' . PageRepository::DOKTYPE_BE_USER_SECTION . ',' .
            PageRepository::DOKTYPE_RECYCLER . ',' . PageRepository::DOKTYPE_SYSFOLDER . ')';
```
This part ignore my "doktypes".

**Comment by bjo3rnf** [comment]
Thanks for pointing this out. The argument `doktypes` is actually completely ignored. I will take care of it.

**Comment by bjo3rnf** [comment]
Hm. This piece of code from `TypoScriptFrontendController` is a showstopper in this case:

```php
   /**
     * Sets sys_page where-clause
     *
     * @return void
     * @access private
     */
    public function setSysPageWhereClause()
    {
        $this->sys_page->where_hid_del .= ' AND pages.doktype<200';
        $this->sys_page->where_groupAccess = $this->sys_page->getMultipleGroupsWhereClause('pages.fe_group', 'pages');
    }
```
What now?

**Comment by bjo3rnf** [comment]
I suggest to drop this feature and recommend to use some other doktype like a shortcut to group pages in the pagetree since sysfolders are not meant to be listed in menus in the first place. The above code is there for a reason I guess. @NamelessCoder what do you think?

**Comment by NamelessCoder** [comment]
Doktypes definitely should not be possible to render in menus (although technically they *can* be used as starting point for one). The hardcoded restrictions are very much intentional ;)

**Comment by NamelessCoder** [comment]
Closed - we will opt to stay closer to what the TYPO3 core does/allows in this case. Rendering of sysfolders in menu is not possible, neither in TYPO3 nor VHS.

On a side note the clause from TypoScriptFrontendController is... well, not a friendly one. It's a legacy leftover arbitrarily selected value where some random number is chosen to divide normal behaviors from special ones. Had TYPO3 done this today I suspect a secondary boolean toggle (is record storage) would have been implemented... but it is what it is, currently.
