### ISSUE TITLE
[BUG] v:menu ignores hideIfEmpty in manual rendering

### ISSUE THREAD

**Issue by tantegerda1** [FluidTYPO3/vhs#1085]
It doesn't exactly _ignore_ it but it falls back to automatic rendering instead - yielding an auto-generated menu in cases where a handcrafted menu should remain empty.

---
# Example:

```xml
<v:menu pageUid="1" as="menuItems" hideIfEmpty="true">
    <f:for each="{menuItems}" as="menuItem">
        <f:if condition="{menuItem.someAttribute} == foo">
            <a href="{menuItem.link}">{menuItem.linktext}</a>
        </f:if>
    </f:for>
</v:menu>
```
----
## Case 1
```
Page 1
+-+ Page 10
| + Page 11
| + Page 12 (someAttribute=foo)
```
```html
<a href="?id=12">Page 12</a>
```
## Case 2
_(same structure, just attribute differs)_
```
Page 1
+-+ Page 10
| + Page 11
| + Page 12
```
```html
<ul>
    <li>
       <a href="?id=10">Page 10</a>
       <a href="?id=11">Page 11</a>
       <a href="?id=12">Page 12</a>
    </li>
</ul>
```
While the expected result here would be:
```html
````
---
# Explanation:
Once the tag content (manual rendering mode) is rendered, the ViewHelper [recognizes that the output is empty after trimming](https://github.com/FluidTYPO3/vhs/blob/development/Classes/ViewHelpers/Menu/AbstractMenuViewHelper.php#L269) and (wrongly) assumes automatic rendering. Since the automatic rendering **does** deliver some output, it is no longer affected by `hideIfEmpty`.

**Comment by tantegerda1** [comment]
I pushed a commit that kind-of fixes that issue, but that has it's issues too.
To me it seems we have following options:
- ignore the issue altogether (one can argue it's a special case)
- find a way to determine if `as` has been actively set or is just a fallback (I doubt that)
- find a way to determine if the `v:menu` tag actually _has children_ (even if they are conditional and render to a mostly empty string)
- change the default value of `as`
- introduce a new argument

**Comment by tantegerda1** [comment]
## Workaround
(_for later reference_)
When rendering HTML, it is easy to circumvent this issue by non-conditionally including a small HTML-comment inside the menu. Not very beautiful, but works.
```html
<v:menu pageUid="1" as="menuItems" hideIfEmpty="true">
    <!-- XXX comment to help making the tag content non-empty -->
    <f:for each="{menuItems}" as="menuItem">
        <f:if condition="{menuItem.someAttribute} == foo">
            <a href="{menuItem.link}">{menuItem.linktext}</a>
        </f:if>
    </f:for>
</v:menu>

**Comment by bjo3rnf** [comment]
Hi,

what is `hideIfEmpty` good for in the context of menus especially with manual rendering? I think this is an edge case.

Cheers
Björn

**Comment by bjo3rnf** [comment]
What about removing `trim()`? I think whitespace can safely be ignored as 'rendered' content.

**Comment by tantegerda1** [comment]
Hi Björn, 

thanks for taking care. I'm not quite sure but I think your solution introduces another quirk for users who _want_ auto rendering **and** `hideIfEmpty` - which seems a legit use case? As far as I can see, in that case the auto rendering will never be triggered (instead, an empty string is immediately returned).

Cheers, 
Ludwig

**Comment by bjo3rnf** [comment]
Hi Ludwig,

I'm not sure but I think empty menus don't trigger autorendering and return null early so it should be `hideIfEmpty` out of the box.

Cheers
Björn

**Comment by danielkestler** [comment]
Try the following: 

```html 
<v:menu pageUid="1" as="menuItems" deferred="true">
    <f:if condition="{menuItems}">
        <f:for each="{menuItems}" as="menuItem">
            <f:if condition="{menuItem.someAttribute} == foo">
                <a href="{menuItem.link}">{menuItem.linktext}</a>
            </f:if>
        </f:for>
    </f:if>
</v:menu>
```

Or do I understand something wrong?
