### ISSUE TITLE
form.select selected option on error

### ISSUE THREAD

**Issue by NyroTheCat** [FluidTYPO3/vhs#1087]
I found an issue. May it wont be a bug, but please take a look at it.

Earlier i used default fluid view helpers to render select inputs like this:

``` html
<f:form.select name="location" options="{locations}" />
```

On form errors the choosen option will be restored.

Now i switched to `vhs`:

``` html
<v:form.select name="location" options="{locations}" />
```

The choosen option wont be restored anymore like before.

PS: If the `property` attribute ist used instead of `name` the option becomes restored correctly as expected.

I'm on v3.0.1

**Comment by 4-lom** [comment]
There is also an issue, happening for example in the Backend Module of the builder extension.
![bildschirmfoto 2016-08-16 um 16 29 12](https://cloud.githubusercontent.com/assets/4653214/17702554/b3f3742e-63ce-11e6-9cdc-a0add58dc447.png)
I've looked in the code. Seems like the method getValue was deprecated in 7.x and removed in 8.0.0. I got this error only in TYPO3 >= 8.0.0
