### ISSUE TITLE
GraphicalFunctions::pngToGifByImagemagick has been removed

### ISSUE THREAD

**Issue by georgringer** [FluidTYPO3/vhs#1092]
The method ´GraphicalFunctions::pngToGifByImagemagick` has been removed in 8. Read about it at https://forge.typo3.org/issues/72426.

It is used e.g. in `AbstractImageViewHelper`

**Comment by bjo3rnf** [comment]
Already removed in ddb06b1eaba0c030c2cea67bbb1e042d9314dd3f, thanks.
