### ISSUE TITLE
Hook/Signal Slot request for preprocessing assets

### ISSUE THREAD

**Issue by Josta** [FluidTYPO3/vhs#1101]
I'm currently developing an asset extension that builds upon VHS and that enables the user to define SCSS and Coffeescript snippets on three levels: Applied globally, for specific pages, and for specific content elements (meaning pages and CEs have new fields in the Backend).

The specific assets I compile and cache on my own, so I can simply add them to VHS with _Asset::createFromSettings()_. The global assets are another matter. What I would like to have is that they can simply be defined in the TS "_plugin.tx_vhs.settings.asset_" array with type "_scss_" or "_coffee_". Then I'd hook into the VHS asset service and precompile the assets (while changing the type to "_css_" or "_js_"), making the process transparent to VHS.

If you like that idea, I'd ask you to add a hook or signal that allows to preprocess any assets (file or content-based) in a way that allows the preprocessing to be cached. I'm not sure where the best place would be, but I'd guess in the _AssetService_ class within the _extractAssetContent()_ function,  before the _detectAndCopyFileReferences_ call (it should be able to read and modify the variables _$asset_, _$assetSettings_ and _$content_ there).

**Comment by NamelessCoder** [comment]
Signals sound like a nice way to solve this and I confirm there is no other immediately available way to do such asset processing in VHS - would you mind preparing a pull request with signals added in the key places you would need?

**Comment by bjo3rnf** [comment]
Ping @Josta. Is this feature request still valid?

**Comment by cedricziel** [comment]
I request it, if he doesn't. :grapes:

**Comment by bjo3rnf** [comment]
> would you mind preparing a pull request with signals added in the key places you would need?

**Comment by cedricziel** [comment]
I'm afraid I can't do that, @bjo3rnf

**Comment by danielkestler** [comment]
I don't think we can modify $asset or $assetSettings here, because they are local variables. Wouldn't it be sufficient to pass $content in the signal? We could check for asset-type before or could pass the asset-type in the signal, too.

**Comment by NamelessCoder** [comment]
We have `writeAssetFile` signal in `AssetService` which you can slot into - it will only receive the file contents but that should be all you need. If however you still require a signal that allows you to modify $settings or $assetSettings before the asset content string is built - then please open a pull request that implements a new signal in the same way as `writeAssetFile`.

In fact, feel free to PR for as many signals as you'd like.
