### ISSUE TITLE
[Question] How to properly define a namespace in vhs 3.0.1

### ISSUE THREAD

**Issue by kludikovsky** [FluidTYPO3/vhs#1113]
I ran into an issue as described [in this error report](https://github.com/derhansen/sf_event_mgt/issues/356#event-781075408).

After a days work or so, I figured out that this has to do with the vhs.
I've now solved my problem for the moment. 

But I'd like to know how to properly define the vhs-namespace now in a template as in my case. 
The above mentioned problem report includes the 'faulty' template.

**Comment by NamelessCoder** [comment]
The namespace is defined with `{namespace v=FluidTYPO3\Vhs\ViewHelpers}`. Your particular error with switch and case is because those ViewHelpers were removed in version 3.0.0 - you can use the TYPO3 core's corresponding ViewHelpers now. See CHANGELOG.md for more info if needed!

**Comment by kludikovsky** [comment]
This was the namespace I use (as can be ssen in the template), 
But the error did indicate that the  ViewHelpers where missing instead of that the used functions (switch/case) where missing.

**Comment by NamelessCoder** [comment]
To clarify, "class not found" happens only if the class was in fact removed - or if there was a typo in the namespace. In this case, definitely because the classes were removed.

If the namespace was not registered then that yields another type of error.
