### ISSUE TITLE
empty array from page.info of sysfolder

### ISSUE THREAD

**Issue by fischhase** [FluidTYPO3/vhs#1114]
Dear vhs-team,

thank you for your great work. 
After updatinig the typo3 extension from V 2.4.0 to 3.0.1 the page.info viewhelper does not act as before: 
If you call {v:page.info(pageUid: '17')}  and the PID is from a sysfolder, the output array ist empty. If you change pageUid to eg. 1, an array of the home page is given. I changed back to 2.4.0 and the page.info gives array of sysfolder.

Typo3 7.10

regards
seebold

**Comment by bjo3rnf** [comment]
Hi @fischhase,

this is a side effect of recent changes in the underlying page service which no longer considers sysfolders as regular pages. What kind of data do you try to get from the sysfolder?

Cheers
Björn

**Comment by fischhase** [comment]
Hallo Björn,

I made a small EXT, that adds a field to pages. I can add the uid of a 
event detail page and a news detail page to the news/event-sysfolder 
property. So I can show news of different e.g. miocrosites in one 
news/eventlist, but the details are shown on the specific micropage.

> {v:page.info(pageUid: '{n.pid}', field:'fh_addfields_eventsinglepid')}
But I also could imagine other applications: If you have data in 
different sysfolders, you could use the media of the sysfolders as an 
icons.

It would be great to restore the functionality :-) maybe a sysfolder 
service should be established parallel to the page service :-/

Danke für die schnelle Reaktion.
Grüße
Martin


Am 12.09.2016 um 18:00 schrieb Björn Fromme:

**Comment by cedricziel** [comment]
Hi there :)

While I'm neutral to the API changes, I see the need to retrieve data. - At least in cases you know the uid.

We need to be careful with dynamic querying, but maybe there's some point in between we could meet. While I cannot offer you a solution straight-away, crafting a viewhelper yourself that just fetches data from a pages record and eventually overlays them with the translation (both through `BackendUtility`) should be easily possible. Maybe you're better off crafting a precise solution to your needs.

Cheers,
Cedric

**Comment by fischhase** [comment]
Hi Cedrik,

I used your viewhelper before, so  I will stay at the working version. I 
only have to remember, not to update vhs in the extmanager. But if it is 
not possible to keep previous functionality, it may be unsuspectingly 
for all, who upgrades vhs.

Anyway. I can deal with it. If you find a way sometimes, I would be pleased.

Thanks
Martin


Am 13.09.2016 um 12:51 schrieb Cedric Ziel:

**Comment by cedricziel** [comment]
Okay, I checked the issue in depth - while the menu viewhelpers now receive different input, I think it's not the `page.info` viewhelper that doesn't let you get the info.

As a proof, I wrote a test that asserts that the behaviour (#1118) of the viewhelper and the pageservice is correct. Could you please double check that your uid argument is set correctly?

I'd happily review more template code of yours. For now I tend to think the issue is invalid.

**Comment by bjo3rnf** [comment]
@cedricziel thanks for investigating but I'm quite sure the test doesn't cover everything. IIRC `PageRepository` limits page or menu results to doktypes < 200 at some point. I can reproduce the described behavior and I think the viewhelper should be rewritten using a simple query or better: removed completely ;)

**Comment by cedricziel** [comment]
The point I wanted to proof, is that it's not the `PageService` that limits the visibility. :)

The code in `PageRepository` itself is quite simple https://github.com/TYPO3/TYPO3.CMS/blob/TYPO3_7-6/typo3/sysext/frontend/Classes/Page/PageRepository.php#L224

If there would be anything that's able to alter the `WHERE` clause, it's in a hook :)

Anyways - I'd be happy to use the BackendUtility to simply grab the record. - And of course I'd like to be proven wrong.

**Comment by cweiske** [comment]
`TypoScriptFrontendController::setSysPageWhereClause` adds the rule:

    $this->sys_page->where_hid_del .= ' AND pages.doktype<200';

This issue breaks menus here for us; you cannot use sysfolders as non-linked menu groupers anymore.

**Comment by cweiske** [comment]
Related to #1081.
