### ISSUE TITLE
v:unless throws '#1237823695: Argument "condition" was not registered.'

### ISSUE THREAD

**Issue by InvisibleKind** [FluidTYPO3/vhs#1121]
Trying to use `v:unless` but it results in an exception `#1237823695: Argument "condition" was not registered.`.

I added the following code (just like in `f:if` ViewHelper ) into UnlessViewHelper and it works again:

```
/**
 * @return void
 */
public function initializeArguments()
{
    $this->registerArgument('condition', 'boolean', 'Condition to be evaluated.');
}
```

The question is: should this code be added directly into `UnlessViewHelper` or it should inherit from `IfViewHelper`?

TYPO3 7.6.11
vhs 3.0.1

**Comment by NamelessCoder** [comment]
Looks like this condition ViewHelper was missed. It should inherit from AbstractConditionViewHelper and should implement evaluateCondition() as the only overridden method - that should work.

**Comment by InvisibleKind** [comment]
It actually inherits from [AbstractConditionViewHelper](https://github.com/FluidTYPO3/vhs/blob/development/Classes/ViewHelpers/UnlessViewHelper.php#L47), but as I understand Fluid throws an exception, because it can't find "condition" in VH's signature. And the exception is thrown before `evaluateCondition()` could be called.

**Comment by bjo3rnf** [comment]
@InvisibleKind is right. The argument `condition` is never registered. Mind making a pull request out of your solution?
