### ISSUE TITLE
forgotten methods inAbstractMenuViewHelper.php

### ISSUE THREAD

**Issue by farconada** [FluidTYPO3/vhs#1124]
Hi guys,
IMHO you have forgotten this methods in Classes/ViewHelpers/Menu/AbstractMenuViewHelper.php and you are using them for example in SubViewHelper.php

It's causing to me a critical error after a migration from 2.4 to 3.0. I've just monkey patching with those lines and the error is fixed
 
```
    /**
     * @param integer $pageUid
     * @return boolean
     */
    protected function isCurrent($pageUid) {
        return (boolean) ((integer) $pageUid === (integer) $GLOBALS['TSFE']->id);
    }

    /**
     * @param integer $pageUid
     * @param array $rootLine
     * @param integer $originalPageUid
     * @return boolean
     */
    protected function isActive($pageUid, $rootLine, $originalPageUid = NULL) {
        if (NULL !== $originalPageUid && $pageUid !== $originalPageUid) {
            $pageUid = $originalPageUid;
        }
        foreach ($rootLine as $page) {
            if ((integer) $page['uid'] === (integer) $pageUid) {
                return TRUE;
            }
        }
        return FALSE;
    }
```

**Comment by NamelessCoder** [comment]
@cedricziel You seem to have this code in active memory. Your thoughts? Missing refactoring?

**Comment by bjo3rnf** [comment]
Hi,

this is indeed a missed refactoring. I'll take care of it. Thanks @farconada.

Cheers
Björn

**Comment by cedricziel** [comment]
Possibly, my last patches was to correct exactly that by using the PageService, that's available.

Thx for taking care, @bjo3rnf
