### ISSUE TITLE
v:page.menu - shortcut and translation problem

### ISSUE THREAD

**Issue by rasgor** [FluidTYPO3/vhs#1129]
- under 7.6.11 and VHS 3.0.1 the v:page.menu dismisses pages which are declared as shortcuts (tried to set several options)
- on a multilanguage website the standard translation will be shown even if the INSTALL-TOOL option 
  [FE][hidePagesIfNotTranslatedByDefault] is set to 1

Both issues were nearly fixed when I downgrade to the VHS 2.4.0 version.

**Comment by bjo3rnf** [comment]
Hi @rasgor,

I can't confirm the described issue regarding shortcuts. What do you mean by 'dismisses pages'?  Please make sure to set the proper attribute `useShortcutUid` or `useShortcutTarget` to avoid redirects. I'm not sure about the multilanguage issue though so I will do some testing and try to reproduce.

Cheers
Björn

**Comment by rasgor** [comment]
Hi @bjo3rnf ,

thank you for your reply. The very first problem was a mistake made by myself. The page tree in the project I am currently working at is pretty big so i got stuck/blind in the problem view and did not see that the "problem" pages were hidden in the menu.

I'll test the translation handling again and will give feedback (maybe i have overlooked another obvious setting ).

**Comment by cedricziel** [comment]
ping @rasgor

**Comment by bjo3rnf** [comment]
Closed due to lack of feedback. Feel free to reopen if required.
