### ISSUE TITLE
v:menu: "Link to external URL" not directly linked

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/vhs#1130]
After upgrading from vhs 2.4.0 to 3.0.1, we noticed that menu items of pages with type "Link to external URL"  do not get their external URL set anymore - but their internal one.

Example:
- Page uid 3, type "Link to external URL", URL `http://example.org/`
- Link generated by `<v:menu>`:
  - 2.4.0: `<a href="http://example.org/">dummy</a>`
  - 3.0.1: `<a href="/index.php?id=3">dummy</a>`

When accessing `/?id=3`, TYPO3 redirects to the final URL.

Unfortunately this breaks our static export that simply does not export redirected pages.

This all happens in `PageService::getItemLink()`.

**Comment by bjo3rnf** [comment]
Confirmed. Thanks for reporting. I'll come up with a fix asap.

**Comment by cweiske** [comment]
Unfortunately the patch does not respect the `urltype` field (mailto, http, https, ftp, ...).

```
$url = $sys_page->getExtUrl($pageRow)
```
should be used to get the full URL with scheme.
