### ISSUE TITLE
v:page.menu crashes with pages-only-in-workspace: Broken rootline. Could not resolve page with uid 23

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/vhs#1132]
`<v:page.menu>` breaks when a menu shall be rendered that contains pages that are only available in the workspace. Error message is:

> Broken rootline. Could not resolve page with uid 23

Steps to reproduce:

1. In the TYPO3 backend, create a workspace and switch to it
2. Create a new page
3. Make sure the page is shown in a menu created with `<v:page.menu>`. "Normal" preview links work fine.
4. Generate a preview link with Workspaces -> "Generate page preview links" (URL will look like `http://example.org/index.php?&ADMCMD_prev=cc469fafe925917a4cc60b0a6177da12&id=23&L=0`)
5. Open the URL and see the fatal error: "Broken rootline. Could not resolve page with uid 23"

This happens with vhs 2.4.0

![2016-10-17 typo3 preview link](https://cloud.githubusercontent.com/assets/59036/19440818/a05ec14e-9483-11e6-94c3-c32637356769.png)

**Comment by cweiske** [comment]
.. and I just see that it does not happen anymore with vhs 3.0.1.

Sorry for the spam.

**Comment by NamelessCoder** [comment]
Not spam - good search engine fodder. Thanks for documenting it, I'm not sure there was an issue about it before!
