### ISSUE TITLE
Argument "allowMoveToFooter" was not registered

### ISSUE THREAD

**Issue by junfan59** [FluidTYPO3/vhs#1172]
With TYPO3 7.6.12 + vhs 3.1.0 I have this error message in frontend : Argument "allowMoveToFooter" was not registered.
If I delete this argument into my template the error message disapear.

Exemple 
`<v:asset.script name="modernizr"      path="{settings.pathjslib}modernizr-2.8.3.min.js"      allowMoveToFooter="false" dependencies="jquery" />` ---> ERROR

`<v:asset.script name="modernizr"      path="{settings.pathjslib}modernizr-2.8.3.min.js"      dependencies="jquery" />` ---> NOT ERROR

Any idea ?
Have I to use an other new argument ? Or the documention is it wrong ?

Thanks

**Comment by bjo3rnf** [comment]
Hi @junfan59,

the correct usage is `movable="false"` which is like this for quite some time now. Where did you find it documented that way?

Cheers
Björn

**Comment by junfan59** [comment]
Hi bjo3rnf,

Thanks for your answer :)
Your solution is working !

I found this argument into this documentation https://fluidtypo3.org/viewhelpers/vhs/master/Asset/StyleViewHelper.html

Thanks again ;)
Christophe

**Comment by bjo3rnf** [comment]
Hi Christophe,

to close this one: please make sure to select the correct docs' version. Your link points to the master branch of vhs.

Cheers
Björn
