### ISSUE TITLE
After updating from 2.4 to 3.1 v.page.resources.fal delivers empty array

### ISSUE THREAD

**Issue by MarkusBausK** [FluidTYPO3/vhs#1173]
Hi,

after updating vhs from 2.4 to 3.1 I have a problem with the v:page.resources.fal viewhelper. In a lot of my projects the editors get the possibility to change the header of the pages uploading an image to page resources. In vhs 2.4.0 the header partial is filled with the image by (works fine):

`<v:page.resources.fal table="pages" field="media" uid="{page.uid}" as="images" slide="-1">
	<f:for each="{images}" as="image">
		<f:image src="{image.url}" alt="{image.alternative}" />
	</f:for>
</v:page.resources.fal>`

After updating to some version from vhs 3 I get an empty array for "images". I read the issue of the page.info viewhelper in case of reading something from a sysfolder. Maybe it has something to do with that, because in my case the masterpages in the trees where the editor should upload are a pagetype shortcut to the first subpage in the tree. If I use a standard page from the tree the viewhelper is working. Changing every shortcut masterpage to defaut pages would be really bad for me. Is there any possibilty to change that back to the former behavior?

Best regards in my bumpy English :-)
Markus

**Comment by siorpaesas** [comment]
Hi
I can confirm this. The viewhelper doesn't work anymore after the upgrade.

Does anyone know if there is a workaround for this via another viewhelper?

Thanks
Flo
