### ISSUE TITLE
v:format.replace() with backslash

### ISSUE THREAD

**Issue by aWuttig** [FluidTYPO3/vhs#1180]
We try to replace all occurences of backslashes with a dot:

`{ foo -> v:format.replace(substring: '\\', replacement: '.')}`

This doesn`t work, because backslash is not escaped.

Could you help us with this?

**Comment by bjo3rnf** [comment]
Hi @aWuttig,

`{ foo -> v:format.replace(substring: "\", replacement: '.')}` should do the trick.

Cheers
Björn

**Comment by cedricziel** [comment]
Closing. Feel free to reopen when necessary.
