### ISSUE TITLE
BreadCrumbViewHelper renders sysfolders and ignores "doctypes" argument

### ISSUE THREAD

**Issue by moger-xx** [FluidTYPO3/vhs#1181]
Hi,

TYPO3 7.6.13
VHS 3.1.0 

The breadCrumb Viewhelper unexpectedly renders sysfolders (doktype=254). AFAIK VHS 2.4 did not do that.

Example:
`<v:page.breadCrumb pageUid="{page.uid}" as="breadCrumb" entryLevel="1" showHiddenInMenu="false">`

Also, adding the "doktypes" argument does not seem to have any effect:
`<v:page.breadCrumb pageUid="{page.uid}" as="breadCrumb" entryLevel="1" doktypes="default,shortcut">`
`<v:page.breadCrumb pageUid="{page.uid}" as="breadCrumb" entryLevel="1" doktypes="DEFAULT,SHORTCUT">`
`<v:page.breadCrumb pageUid="{page.uid}" as="breadCrumb" entryLevel="1" doktypes="default">`

Note: I worked around by saving my sysfolders temporarily as standard page, then check "do not show in menus", save, then switch it back to "sysfolder" and save again.

Cheers,
Moritz

**Comment by NamelessCoder** [comment]
@bjo3rnf / @cedricziel this looks related to both https://github.com/FluidTYPO3/vhs/issues/1182 and https://github.com/FluidTYPO3/vhs/issues/1081 - do either of you have a known solution for this one, e.g. switching to PageRepository in this VH? Just probing for a quick fix :)

**Comment by bjo3rnf** [comment]
Hi @moger-xx,

I can confirm this. Question: what is the expected behavior in this case? Should folders simply be skipped or should the breadcrumb stop at that level?

Cheers
Björn

**Comment by moger-xx** [comment]
Hi bjoern,

Thank you for looking into this.

I suggest non-standard pagetypes to be skipped, I think this is most
flexible.

Nice would be if the pagetypes which shall be displayed can be overriden by
setting the doctypes Parameter.

Cheer,
Moritz

Am 03.12.2016 11:27 vorm. schrieb "Björn Fromme" <notifications@github.com>:

Hi @moger-xx <https://github.com/moger-xx>,

I can confirm this. Question: what is the expected behavior in this case?
Should folders simply be skipped or should the breadcrumb stop at that
level?

Cheers
Björn

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/FluidTYPO3/vhs/issues/1181#issuecomment-264630942>, or mute
the thread

**Comment by bjo3rnf** [comment]
Closed with merging of #1185. Argument 'doktypes' is deprecated so it can't be considered.

**Comment by ogrosko** [comment]
With the merge #1185 now it's not possible to have custom page types in breadCrumb line :(
Doktypes are hardcoded
`$isAllowedDoktype = in_array((int) $record['doktype'], [
                PageRepository::DOKTYPE_DEFAULT,
                PageRepository::DOKTYPE_LINK,
                PageRepository::DOKTYPE_SHORTCUT,
                PageRepository::DOKTYPE_MOUNTPOINT
            ]);`

I would suggest to use this:
`$isAllowedDoktype = (int) $record['doktype'] < 200;`

according to https://docs.typo3.org/typo3cms/CoreApiReference/PageTypes/Index.html

> The choice of value for the doktype is critical. If you want your custom page type to be displayed in the frontend, you must make sure to choose a doktype smaller than 200. If it's supposed to be just some storage, choose a doktype larger than 200.

Is it acceptable

**Comment by bjo3rnf** [comment]
I like this approach. Mind turning it into a pull request?

**Comment by cedricziel** [comment]
Sounds great, I'm sold.

**Comment by ogrosko** [comment]
What about this #1344 ?
