### ISSUE TITLE
Drop PHP5 support in the next major release

### ISSUE THREAD

**Issue by cedricziel** [FluidTYPO3/vhs#1199]
This issue expands on most of the other projects in the org.

We should drop PHP 5 support from travis and set the baseline at PHP7 on April 1st 2017 when TYPO3 7 LTS switches from active support to effectively frozen "priority bugfix" mode.

## rationale

TYPO3 v8 is PHP 7+ and PHP 5 has reached EOL and should never ever be used for new projects by January 1st 2017.

Any project using TYPO3 <= 7.6 should have settled in a stable state by the given date, and while that may or may not match all projects in the wild, we should force the upgrade on us and anyone else. We have a pretty good track record on only supporting actively developed TYPO3 versions and we shouldn't stop with the next one.

ping @bjo3rnf @NamelessCoder @coding46 @xf-

**Comment by bjo3rnf** [comment]
Drop it like it's hot.

**Comment by NamelessCoder** [comment]
@cedricziel would you mind preparing a pull request for this, á la the ones we did for Flux etc.?

**Comment by cedricziel** [comment]
Sure, @NamelessCoder :)
