### ISSUE TITLE
L ViewHelper does not respect extensionName argument 

### ISSUE THREAD

**Issue by mrk131324** [FluidTYPO3/vhs#1217]
It's simple matter of order of lines in 

vhs/Classes/ViewHelpers/LViewHelper.php:75 we have

```
  $arguments = $arguments['arguments'];
  $extensionName = $arguments['extensionName'];
```

Instead we should have

```
  $extensionName = $arguments['extensionName'];
  $arguments = $arguments['arguments'];
```

Or even better find a different name for $arguments to avoid confusion.

**Comment by NamelessCoder** [comment]
Reversing the argument assignment order or not declaring $arguments and using $arguments['arguments'] below would both be okay. Second solution probably preferred to avoid confusion with redeclaring an argument. Feel free to create a pull request with this! :)
