### ISSUE TITLE
v:content.render content element rendering problem

### ISSUE THREAD

**Issue by advOpk** [FluidTYPO3/vhs#1218]
Hello, I'm having problem after upgrading VHS to 4.0 With <v:content.render contentUids="{0:123}" render="1"/> Same installation with VHS ver. 3.1. viewhelper is working
Debug gives empty string.

ContentUid points to news plugin inserted via tt_content. Typo 7.6.15, fluidcontent 5.0.0, fluidpages 4.0.0, flux 8.0.0

**Comment by bjo3rnf** [comment]
Should be fixed by #1221
