### ISSUE TITLE
Problem with hidden pages

### ISSUE THREAD

**Issue by filoucrackeur** [FluidTYPO3/vhs#1242]
page hidden is 14

 <v:menu.list pages="{settings.footer.menuBesoinAide.pages}">  where = 12,13,14 
Fail

 <v:menu.list pages="{settings.footer.menuBesoinAide.pages}">  where = 12,13
Ok

An exception occurred while executing 'SELECT * FROM `pages` WHERE (`pid` IN ()) AND (((`pages`.`deleted` = 0) AND (`pages`.`t3ver_state` <= 0) AND (`pages`.`hidden` = 0) AND (`pages`.`starttime` <= 1486628040) AND ((`pages`.`endtime` = 0) OR (`pages`.`endtime` > 1486628040))) AND (`pages`.`doktype` < 200)) AND (((`pages`.`fe_group` = '') OR (`pages`.`fe_group` IS NULL) OR (`pages`.`fe_group` = 0) OR (FIND_IN_SET('0', `pages`.`fe_group`)) OR (FIND_IN_SET('-1', `pages`.`fe_group`)))) AND (doktype NOT IN (6,255,254) AND nav_hide = 0 AND doktype != 199) ORDER BY `sorting` ASC': SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')) AND (((`pages`.`deleted` = 0) AND (`pages`.`t3ver_state` <= 0) AND (`pages`.`' at line 1 

Doctrine\DBAL\Exception\SyntaxErrorException thrown in file
/home/DE/pcourt/dev.sunshine.qua/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php in line 90.

78 Doctrine\DBAL\Driver\AbstractMySQLDriver::convertException("An exception occurred while executing 'SELECT * FR…ges`.`t3ver_state` <= 0) AND (`pages`.`' at line 1", Doctrine\DBAL\Driver\PDOException)

/home/DE/pcourt/dev.sunshine.qua/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:
00126: 
00127:         if ($driver instanceof ExceptionConverterDriver && $driverEx instanceof DriverException) {
00128:             return $driver->convertException($msg, $driverEx);
00129:         }
00130: 

77 Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Doctrine\DBAL\Driver\PDOMySql\Driver, Doctrine\DBAL\Driver\PDOException, "SELECT * FROM `pages` WHERE (`pid` IN ()) AND (((`…ide = 0 AND doktype != 199) ORDER BY `sorting` ASC", array)

/home/DE/pcourt/dev.sunshine.qua/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:
00853:             }
00854:         } catch (\Exception $ex) {
00855:             throw DBALException::driverExceptionDuringQuery($this->_driver, $ex, $query, $this->resolveParams($params, $types));
00856:         }
00857: 

76 Doctrine\DBAL\Connection::executeQuery("SELECT * FROM `pages` WHERE (`pid` IN ()) AND (((`…ide = 0 AND doktype != 199) ORDER BY `sorting` ASC", array, array)

/home/DE/pcourt/dev.sunshine.qua/vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:
00204:     {
00205:         if ($this->type == self::SELECT) {
00206:             return $this->connection->executeQuery($this->getSQL(), $this->params, $this->paramTypes);
00207:         } else {
00208:             return $this->connection->executeUpdate($this->getSQL(), $this->params, $this->paramTypes);

**Comment by bjo3rnf** [comment]
Confirmed. I will take a look at it.

**Comment by bjo3rnf** [comment]
This has already been fixed in current development branch, but resulted in empty menu entries for hidden pages. My patch also removes those.

**Comment by filoucrackeur** [comment]
ok thanks sorry
