### ISSUE TITLE
bracket in bracket

### ISSUE THREAD

**Issue by droomdre** [FluidTYPO3/vhs#1244]
Hi folks, 
how can i do the following:
<v:iterator.for from="1" to="6" iteration="i">
    {description.{i.index}.title}
</v:iterator.for>

It is not working.

**Comment by monosize** [comment]
try this one `{v:variable.get(name:'description.{i.index}.title')}`
more infos here https://fluidtypo3.org/viewhelpers/vhs/master/Variable/GetViewHelper.html
