### ISSUE TITLE
render.inline ViewHelper renders nothing since vhs Version 4

### ISSUE THREAD

**Issue by dr-bock** [FluidTYPO3/vhs#1246]
Since we updated from vhs 3.1 to 4.0 the render.inline ViewHelper renders nothing. No Error is thrown. Same Syntax as in 3.1 and before:
`<v:render.inline content="{data.bodytext}" onError="NULL" graceful="1" />`

or

`<v:render.inline content="<p>test</p>" onError="NULL" graceful="1" />`

render always "NULL" or nothing if no "onError" or "graceful" are set.

--

We use vhs4, flux8, fludicontent5 on TYPO 7.6.16-dev

**Comment by ogrosko** [comment]
Can confirm same behaviour for version vhs v4.2.0, typo3 v7.6.18

**Comment by gdnwp** [comment]
Have not checked with TYPO 7.6, but with TYPO 8.7 it works if using

<v:render.inline  graceful="1">{content}</v:render.inline>
instead of
<v:render.inline  graceful="1" content="{content}" />

**Comment by ogrosko** [comment]
@gdnwp yes you are right it works
anyway it should accept `content` attribure

**Comment by ogrosko** [comment]
Checking file [InlineViewHelper.php](vhs/Classes/ViewHelpers/Render/InlineViewHelper.php) class uses [TYPO3Fluid](https://github.com/FluidTYPO3/vhs/blob/development/Classes/ViewHelpers/Render/InlineViewHelper.php#L11) trait which is not part of vhs ext. I guess problem will be here
