### ISSUE TITLE
v:page.info crashes in TYPO3 backend

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/vhs#1250]
When using the `<v:page.info>` view helper in the fluidcontent preview section, it crashes:

> Call to a member function getPage_noCheck() on null

It tries to access `$GLOBALS['TSFE']` which does not exist in the backend:

     $page = $GLOBALS['TSFE']->sys_page->getPage_noCheck($pageUid);

**Comment by bjo3rnf** [comment]
Is `TYPO3_MODE === 'BE'` the proper way to detect backend context or is there some shiny new method?

**Comment by NamelessCoder** [comment]
The constant is still the best (fastest) way to check FE/BE so please do use that :)
