### ISSUE TITLE
Headers in content elements are not numbered

### ISSUE THREAD

**Issue by mortenpless** [FluidTYPO3/vhs#1256]
Normally, when rendering content using css_styled_content, headers are wrapped in numbered divs:
I.e: 
`<div class="csc-header csc-header-nX">`
When using vhs, `<v:content.render` column="0" />` this number is always 1.

vhs uses RECORDS and css_styled_content uses CONTENT.

**Comment by bjo3rnf** [comment]
I don't know about the implications here but if this is about applying styles to those headers according to the number maybe `.csc-header:nth-of-type(X)` is an option?

**Comment by bjo3rnf** [comment]
Closing due to lack of response. Furthermore this is not a vhs issue IMHO. Please reopen for further discussion if necessary.
