### ISSUE TITLE
Injection of object manager fails in UncacheTemplateView

### ISSUE THREAD

**Issue by webloft** [FluidTYPO3/vhs#1260]
Got the error on Typo3 8.6 and vhs-dev:

Error: Call to a member function get() on null in .../typo3conf/ext/vhs/Classes/View/UncacheTemplateView.php on line 68

**Comment by bjo3rnf** [comment]
How do you implement/instantiate the view?

**Comment by cedricziel** [comment]
We need to inject the objectmanager manually or retrieve the view through the object manager. `GeneralUtility::makeInstance` doesn't inject dependencies.
