### ISSUE TITLE
PHP Strict Error: Non-static method mergeArraysStatic() should not be called statically

### ISSUE THREAD

**Issue by benjaminpick** [FluidTYPO3/vhs#1267]
(Using vhs 4.1.0)

I have enabled all errors and get:

`PHP Runtime Deprecation Notice: Non-static method FluidTYPO3\Vhs\ViewHelpers\Iterator\MergeViewHelper::mergeArraysStatic() should not be called statically in /var/www/html/webroot/typo3conf/ext/vhs/Classes/ViewHelpers/Iterator/MergeViewHelper.php line 68`

The real issue is in ArrayConsumingViewHelperTrait.php where this method needs the `static` qualifier.

Thanks for your work!

**Comment by cedricziel** [comment]
Thx, good catch!
