### ISSUE TITLE
v:condition.string.contains significantly slows down rendering

### ISSUE THREAD

**Issue by Adan0s** [FluidTYPO3/vhs#1277]
Hi all,

just upgrade a website from Typo3 6.2 / vhs 2.4 to Typo3 7.6 / vhs 4.1.0 and noticed a massive increase in rendering time on a specific partial layout.

The partial contains the following snippet:
```
<v:condition.string.contains haystack="{something.comment}" needle="&euro;">
	<f:then>
		<s><f:format.raw>{something.comment}</f:format.raw></s><br>
		<span class='specialprice'>{something.price}</span>
	</f:then>
	<f:else>
		<f:format.raw>{something.comment}</f:format.raw><br>
		{something.price}
	</f:else>
</v:condition.string.contains>
```

On the Typo3 6.2 instance a page with 170 of these partials rendered took 2.48s to load.
On Typo3 7.2 the same page needs 12.2s.

As soon as I just delete the condition or replace it with a simple f:condition and variable which is getting declared in php the page is down to 1.4s.

Could it be that there is something wrong with the cache generation of that ViewHelper?

**Comment by NamelessCoder** [comment]
The only thing special about that ViewHelper is that it used the ConditionViewHelperTrait - but if this were the problem you should see many other ViewHelpers with similar problems.

I've removed usages of the ConditionViewHelperTrait and the ViewHelper now uses the default condition compiling logic. If that doesn't solve the problem you face, I encourage you to open an issue on https://github.com/TYPO3/Fluid.
