### ISSUE TITLE
Page/Menu/BrowseViewHelper does not properly handle empty menu data

### ISSUE THREAD

**Issue by xperseguers** [FluidTYPO3/vhs#1278]
In my page template I have this:

```
<v:page.menu.browse as="pages" doktypes="DEFAULT,LINK,SHORTCUT,MOUNTPOINT,111">
```

This crashes when parent of current page has only "not in menu" child pages:

![structure](https://cloud.githubusercontent.com/assets/646805/24299782/94d1e308-10aa-11e7-87a3-30aee0c6a022.png)

This may be fixed with a simple test within `\FluidTYPO3\Vhs\ViewHelpers\Menu\BrowseViewHelper::render`:

```
        $menuData = $this->getMenu($parentUid);
        if (empty($menuData)) return null;
```

since `$menuData` is null for such a use case.

**Comment by bjo3rnf** [comment]
Hi Xavier,

thanks for reporting. Haven't come across this constellation yet.

Cheers
Björn
