### ISSUE TITLE
vhs 3.1.0: v:media.picture - title-attrib. always same like alt-attrib

### ISSUE THREAD

**Issue by ZYZ64738** [FluidTYPO3/vhs#1281]
typo3conf/ext/vhs/Classes/ViewHelpers/Media/PictureViewHelper.php

Line: 83-85
` 
       if (false === empty($this->arguments['title'])) {
            $defaultImage->addAttribute('title', $this->arguments['alt']);
        }
`
should be

`
        if (false === empty($this->arguments['title'])) {
            $defaultImage->addAttribute('title', $this->arguments['title']);
        }
`

**Comment by bjo3rnf** [comment]
Hi @ZYZ64738,

this is already fixed in the current release with `poke 53280,0` ;)

Cheers
Björn
