### ISSUE TITLE
v:format.pregReplace does not work with "as"

### ISSUE THREAD

**Issue by rnakielski** [FluidTYPO3/vhs#1284]
using this VH like this:
```
<v:format.pregReplace as="something" pattern="foo" subject="foo" replacement="foo">
	{something}
</v:format.pregReplace>
```
will just output the subject as given (not replaced). The Tag content is ignored.

Like this:
`{v:format.pregReplace( pattern: 'foo', subject: 'foo', replacement: 'foo')}`
it works well

**Comment by bjo3rnf** [comment]
related to #1254

**Comment by NamelessCoder** [comment]
And to https://github.com/FluidTYPO3/vhs/issues/1307

**Comment by NamelessCoder** [comment]
And to https://github.com/FluidTYPO3/vhs/issues/1289
