### ISSUE TITLE
additionalAttributes with TYPO3 8.7

### ISSUE THREAD

**Issue by timofo** [FluidTYPO3/vhs#1286]
If i use for example 
`<v:media.image src="{file}" srcset="480,768,992,1200" maxW="1200" treatIdAsReference="1" alt="{file.alternative}" title="{file.title}" class="img-responsive" additionalAttributes="{foo: 'bar'}" />`
then i get the error: Undeclared arguments passed to ViewHelper FluidTYPO3\Vhs\ViewHelpers\Media\ImageViewHelper: additionalAttributes
Without additionalAttributes it works.

**Comment by ratschnowski** [comment]
Same issue, also with T3 8.6.

**Comment by ratschnowski** [comment]
It seems to work if you modify typo3conf/ext/vhs/Classes/ViewHelpers/Media/AbstractMediaViewHelper.php and add parent::initializeArguments(); after line 33:

`public function initializeArguments()`
` {`
`parent::initializeArguments();`

**Comment by timofo** [comment]
Yes then it works with additionalAttributes.
Maybe this should be in the next update?
In https://fluidtypo3.org/viewhelpers/vhs/master/Media/ImageViewHelper.html there is no more the additionalAttributes option? Why? I think that is was there before a couple of days...

**Comment by timofo** [comment]
Or there should be a "sizes" option. Because if you use srcset, you should be able to use sizes too.

**Comment by timofo** [comment]
<v:media.video is missing this attribute too.... why do you remove it from all helpers?

**Comment by jdreesen** [comment]
According to the [TYPO3 8.0 changelog](https://docs.typo3.org/typo3cms/extensions/core/Changelog/8.0/Breaking-69863-ChangesInViewHelpersPostFluidStandalone.html?highlight=parent::initializeArguments()) there was a breaking change that requires to call `parent::initializeArguments();` **every time** you overwrite that method. This seems not to be the case in many VHS view helpers.

**Comment by NamelessCoder** [comment]
> there was a breaking change that requires to call `parent::initializeArguments();` every time you overwrite that method.

...when the parent class registers arguments, and only then. There are probably some left which need to call `parent::initializeArguments()` but it is certainly far from all of them. Just in case you decide to make a pull request ;)
