### ISSUE TITLE
<v:iterator.random subject="{pages}" as="pageUid" /> returns NULL

### ISSUE THREAD

**Issue by FreddyFFM** [FluidTYPO3/vhs#1289]
Since Update to 4.1.0 vhs:iterator:random is not working correct. It returns only NULL value althoug given array has valid entries:

`<ce:menu.directory pageUids="{pageUids}" as="pages">
	<v:iterator.random subject="{pages}" as="pageUid" />
` 

With Version 3.1.0 code is working properly.

**Comment by bjo3rnf** [comment]
Maybe related to #1272

**Comment by FreddyFFM** [comment]
It's the same issue using `<v:page.menu.directory ... />`

**Comment by bjo3rnf** [comment]
Which TYPO3 version are you using?

**Comment by FreddyFFM** [comment]
It's 7.6.16 LTS

**Comment by bjo3rnf** [comment]
Ok, this is related to #1254. A workaround for now is to avoid `as` and use inline notation instead:
`{v:iterator.random(subject: pages) -> v:variable.set(name: 'pageUid')}` or whatever you use `pageUid` for in the following code. Setting a variable may not the best choice here.
