### ISSUE TITLE
<v:content.render> doesn't find new elements in workspace when using preview link.

### ISSUE THREAD

**Issue by cushingw** [FluidTYPO3/vhs#1297]
I came across this problem while troubleshooting a fluid content element problem in FluidTYPO3/fluidcontent#399. We've got a fluid page template that renders the main content area of the page using <v:content.render>. During testing we found that workspace preview links show the correct content for elements that have been updated in the workspace. However, elements that are new in the workspace don't show up at all.

I tracked the problem down to  \FluidTYPO3\Vhs\ViewHelpers\Content\AbstractContentViewHelper. On line 154 in getSlideRecordsFromPage(), the function calls BackendUtility::versioningPlaceholderClause() if the workspaces module is loaded to get the additional SQL to filter out non-workspace items. The SQL is constructed using the value from $GLOBALS['BE_USER']->workspace.

When this code is called by a logged-in user via the back-end preview, everything works properly. However, when the page is viewed via a workspace preview link, initializePreviewUser() in \TYPO3\CMS\Version\Hook\PreviewHook never sets the workspace ID from the preview configuration in the data for the simulated back-end user. The only place that the correct workspace ID is stored is in the workspacePreview variable of the \TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController passed to it. The result is the filtering SQL from versioningPlaceholderClause() has the wrong workspace ID (usually having -99) and so workspace-only new elements get filtered out.

I've confirmed that patching PreviewHook to set the workspace value for the simulated back-end user fixes the problem and that the new elements appear via preview links.

However, I'm not sure if this is a bug in PreviewHook() from typo3 core or a problem with how getSlideRecordsFromPage() is interacting with versioning/workspaces to select content records.

**Comment by NamelessCoder** [comment]
This appears to be an issue with how the method interacts with workspaces - I've had this issue reported by another user via email and he suggests simply removing the versionPlaceholderClause() call solves the issue on his end (but I cannot say if it also introduces other problems). Comparing the SQL produced by the two cases does seem to indicate that removing the call is the solution.

If you could confirm this that would be very helpful.

**Comment by cushingw** [comment]
Sorry for the delay, but we were in a code freeze prior to an upgrade. I just tested out removing that call and it does appear to make the new content visible in preview links.

**Comment by NamelessCoder** [comment]
Thanks @cushingw - since then, #1366 has taken over the patching of this one. The result should be the same as removing that line, but if you've got time to confirm #1366 that would help a lot. It's the last piece before we can release 4.3.1 :)

**Comment by cushingw** [comment]
I tried to install 4.3.1 to test this patch, but immediately ran into an issue where all of our content was being rendered twice on the page. Once I troubleshoot that problem (and open a ticket if necessary), I'll try to patch 4.3.1 and test.

**Comment by NamelessCoder** [comment]
Before you waste time looking into this one: try dev-development, the colPos=0 bug is fixed there!

**Comment by cushingw** [comment]
Thanks for the tip. Installing the development snapshot solved the duplicate content issue.
Tried patching in commit abdd30d, but it failed in hunk 2 of the updates to LanguageMenuViewHelper.php
Here are the failed diffs:
--- Classes/ViewHelpers/Page/LanguageMenuViewHelper.php
+++ Classes/ViewHelpers/Page/LanguageMenuViewHelper.php
@@ -275,16 +273,14 @@
             'flag' => $this->arguments['defaultIsoFlag']
         ];
 
-        $select = 'uid, title, flag';
+        $select = 'uid,title,flag';
         $from = 'sys_language';
         $limitLanguages = static::arrayFromArrayOrTraversableOrCSVStatic($this->arguments['languages'] ?? []);
         if (!empty($limitLanguages)) {
-            $where = 'uid IN (' . implode(',', $limitLanguages) . ')';
+            $sysLanguage = $GLOBALS['TSFE']->cObj->getRecords($from, ['selectFields' => $select, 'pidInList' => -1, 'uidInList' => implode(
',', $limitLanguages)]);
         } else {
-            $where = '1=1';
+            $sysLanguage = $GLOBALS['TSFE']->cObj->getRecords($from, ['selectFields' => $select, 'pidInList' => 'root']);
         }
-        $where .= $this->cObj->enableFields('sys_language');
-        $sysLanguage = $GLOBALS['TYPO3_DB']->exec_SELECTgetRows($select, $from, $where);
 
         foreach ($sysLanguage as $value) {
             $tempArray[$value['uid']] = [

**Comment by cushingw** [comment]
Here are the diff segments that failed:
`
--- Classes/ViewHelpers/Page/LanguageMenuViewHelper.php
+++ Classes/ViewHelpers/Page/LanguageMenuViewHelper.php
@@ -275,16 +273,14 @@
             'flag' => $this->arguments['defaultIsoFlag']
         ];
 
-        $select = 'uid, title, flag';
+        $select = 'uid,title,flag';
         $from = 'sys_language';
         $limitLanguages = static::arrayFromArrayOrTraversableOrCSVStatic($this->arguments['languages'] ?? []);
         if (!empty($limitLanguages)) {
-            $where = 'uid IN (' . implode(',', $limitLanguages) . ')';
+            $sysLanguage = $GLOBALS['TSFE']->cObj->getRecords($from, ['selectFields' => $select, 'pidInList' => -1, 'uidInList' => implode(
',', $limitLanguages)]);
         } else {
-            $where = '1=1';
+            $sysLanguage = $GLOBALS['TSFE']->cObj->getRecords($from, ['selectFields' => $select, 'pidInList' => 'root']);
         }
-        $where .= $this->cObj->enableFields('sys_language');
-        $sysLanguage = $GLOBALS['TYPO3_DB']->exec_SELECTgetRows($select, $from, $where);
 
         foreach ($sysLanguage as $value) {
             $tempArray[$value['uid']] = [
`

**Comment by cushingw** [comment]
Even with the patching failure, The current dev snapshot with the patch does seem to address this problem.

**Comment by NamelessCoder** [comment]
I think there's one or two other changes inbetween that one and the 4.3.1 tag - but thanks for the update and great to hear it solved the problem!
