### ISSUE TITLE
Serialization of closure

### ISSUE THREAD

**Issue by liayn** [FluidTYPO3/vhs#1298]
Commit f4ee5ebd373bd089c3 (#1293, #1260) causes the FE to break with an "invalid serialization of closure".

@cedricziel Maybe you can double check on your commit.

**Comment by cedricziel** [comment]
Hi @liayn , thx for the report. I'll double check the commit for sure.

**Comment by cedricziel** [comment]
@NamelessCoder can you have a look?

**Comment by NamelessCoder** [comment]
Already discussed with @liayn - we need `_sleep` and `__wakeup` on uncached template view so the entire instance allows serializing.

**Comment by liayn** [comment]
Don't know if it still an issue, but not for us, hence I close this due to inactivity.
