### ISSUE TITLE
Option includeSpacers doesn't work in BreadCrumbViewHelper (vhs 4.1.0)

### ISSUE THREAD

**Issue by Atsyn** [FluidTYPO3/vhs#1299]
How I can see this option is ignored for BreadCrumbViewHelper.
Please confirm and resolve.

**Comment by cedricziel** [comment]
Maybe I'm a little too deep into my own workflows.. but why would you create subpages for spacers?

**Comment by Atsyn** [comment]
@cedricziel we used this type like a category for child pages.
In MenuViewHelper this option works fine. But breadcrumbs look strange...

**Comment by cedricziel** [comment]
Can you use manual rendering and then skip those where the doktype property matches the spacer value?

**Comment by Atsyn** [comment]
@cedricziel I can't understand you. Why I should skip this elements if them I need? %)

**Comment by cedricziel** [comment]
Ahh, I see. My bad :)

Yes. So. Ehm. Bradcrumbs produced by the menu viewhelper are calculated by the core. I'm not sure we can change the functionality without rewriting the rootpath logic, but I'll check it.

**Comment by cedricziel** [comment]
@Atsyn can you check my patch?

**Comment by Atsyn** [comment]
@cedricziel yep, it's work perfect.

**Comment by cedricziel** [comment]
Thx for the report then :)
