### ISSUE TITLE
MenuViewHelper v:menu

### ISSUE THREAD

**Issue by timofo** [FluidTYPO3/vhs#1302]
TYPO3 8.7 and vhs 4.2:
If i use <v:menu pageUid="1" useShortcutUid="1"> the UID of the target page is not set to my shortcut page. I cant get it to work.

**Comment by bjo3rnf** [comment]
I can't reproduce the issue. Do you render the menu manually?

**Comment by timofo** [comment]
Yes. manually. 
`				<v:menu pageUid="1">
					<ul class="nav navbar-nav">
				  		<f:for each="{menu}" as="item">
			  				<f:if condition="{item.hasSubPages}">
			  					<f:then>
			  						<li class="dropdown {f:if(condition:'{item.active}',then:'active')} {f:if(condition:'{item.tx_usefulextrafields_hidemobile}',then:'hidden-sm hidden-xs')}">
					  					<a href="#" title="{item.linktext}" class="dropdown-toggle" data-toggle="dropdown">{item.linktext} <span class="caret"></span></a>
					  					<ul class="dropdown-menu">
					  						<v:menu  pageUid="{item.uid}">
					  							<f:for each="{menu}" as="subItem">
					  								<li class="{f:if(condition:'{subItem.active}',then:'active')} {f:if(condition:'{subItem.tx_usefulextrafields_hidemobile}',then:'hidden-sm hidden-xs')}">
					  									<f:link.page pageUid="{subItem.uid}" title="{subItem.linktext}">{subItem.linktext}</f:link.page>
					  								</li>
					  							</f:for>
					  						</v:menu>
					  					</ul>
				  					</li>
			  					</f:then>
			  					<f:else>
			  						<li class="{f:if(condition:'{item.active}',then:'active')} {f:if(condition:'{item.tx_usefulextrafields_hidemobile}',then:'hidden-sm hidden-xs')}">
			  							<f:link.page pageUid="{item.uid}" title="{item.linktext}">{item.linktext}</f:link.page>
			  						</li>
			  					</f:else>
			  				</f:if>
				  		</f:for>
					</ul>
				</v:menu>`

**Comment by timofo** [comment]
[menu.txt](https://github.com/FluidTYPO3/vhs/files/946407/menu.txt)

**Comment by bjo3rnf** [comment]
Aha. In this case please use `<a href="{subItem.link}" ...>...</a>` instead.

**Comment by timofo** [comment]
For all links?

**Comment by bjo3rnf** [comment]
Yes. Records generated by `v:menu` contain the correct url under the key `link` whereas the uid value is not substituted.

**Comment by timofo** [comment]
This does not work. 
`<a href="{item.link}" title="{item.linktext}">{item.linktext}</a>`
But this is the uid from shortcut page. Not from target page.

**Comment by bjo3rnf** [comment]
Well, I can't see `useShortcutUid="1"` in your code...?

**Comment by timofo** [comment]
Yes. Sorry. Now it works with <a href="{item.link}" title="{item.linktext}">{item.linktext}</a> :-)

**Comment by bjo3rnf** [comment]
Great!

**Comment by timofo** [comment]
I think we have to reopen this issue.
TYPO3 8.7.8
vhs 4.3.3

Simple use of with a page with a shortcut:
<v:menu pageUid="1" useShortcutUid="1">
</v:menu>

The ID of the target page is not there. It is the ID from the shortcut page.
