### ISSUE TITLE
v:media.video doesn't respect preload attribute

### ISSUE THREAD

**Issue by gogy27** [FluidTYPO3/vhs#1308]
Hi guys,

When I set preload attribute for v:media.video the video tag has bad preload attribute.

Check your file in `\Classes\ViewHelpers\Media\VideoViewHelper.php` line `174-176`
```php
if (true === in_array($this->arguments['preload'], $this->validPreloadModes)) {
    $tagAttributes['preload'] = 'preload';
}
```

If preload has valid value, you set it to `preload="preload"` but you should put there:
`$tagAttributes['preload'] = $this->arguments['preload'];`

**Comment by bjo3rnf** [comment]
So true, thanks for the hint @gogy27 .
