### ISSUE TITLE
Minify css and js

### ISSUE THREAD

**Issue by pixelplant** [FluidTYPO3/vhs#1312]
Hello

Am I missing something in the documentation or is css/js minification really not supported?

Based on this older closed issue, seems like it is the case: https://github.com/FluidTYPO3/vhs/issues/546

TypoScript's _config.compressJs_ and _config.compressCss_ do nothing as I assume they only touch the assets included using TypoScript.

**Comment by cedricziel** [comment]
The asset component has come a long way and much brain-juice was involved in creating and *thinking about* improving it.

As far as we are concerned, a more up-to-date asset-workflow involves minifiying the assets as part of a build step (read webpack, gulp, you name it).

Nevertheless - maybe we should at least be able to emit a signal just before `AssetService::placeAssetsInHeaderAndFooter` to allow mutations on them and writing back an updated array of filenames. What do you think, @NamelessCoder , @bjo3rnf ?

**Comment by NamelessCoder** [comment]
I'm not against adding a signal or a plain old hook in this location, so feel free to create that. But you should consider the correct advise Cedric gives, to feed VHS already minified and compressed files (VHS can merge them just fine and handle dependencies if there are any, it just can't compress or minify them). But, in any case, a signal/hook won't hurt us and you could theoretically plug on of those builders in there.

**Comment by pixelplant** [comment]
Yes, it's what I did in the end, merging my files and minifying them using some grunt tasks and then just linking to the final minified css+js file using vhs. I was under the wrong impression that compressCss/compressJs or some similar approach existed in vhs but seeing how compressCss/js is actually pointless in this day and age I'd wish they remove it alltogether from the documentation and just point us to some automation tools that we can use (if we've never used one before, for example).
