### ISSUE TITLE
Image sources doubly rawurlencoded in <v:media.image>

### ISSUE THREAD

**Issue by copitz** [FluidTYPO3/vhs#1314]
Image sources are doubly encoded in <v:media.image> srcSets (double encoding happening [here](https://github.com/FluidTYPO3/vhs/blob/development/Classes/Traits/SourceSetViewHelperTrait.php#L51)) and most likely also in other image sources (double encoding happening [here](https://github.com/FluidTYPO3/vhs/blob/development/Classes/ViewHelpers/Media/Image/AbstractImageViewHelper.php#L203))

**Comment by bjo3rnf** [comment]
This has been fixed in #1223 - at least I thought so. Are you using the current dev version or master/TER?

**Comment by copitz** [comment]
Ah, ok - the latter. Thx
