### ISSUE TITLE
v:render.uncache -> "Call to a member function get() on null"

### ISSUE THREAD

**Issue by TheNaderio** [FluidTYPO3/vhs#1317]
GHi,

I'm getting the error **Call to a member function get() on null** when i'm using v:page.uncache.

I use this im my Template:
`<v:render.uncache partial="MyPartial" section="Main"/>`

and MyPartial.html 
<div xmlns="http://www.w3.org/1999/xhtml" lang="en"
	 xmlns:f="http://typo3.org/ns/TYPO3/Fluid/ViewHelpers"
	 xmlns:v="http://typo3.org/ns/FluidTYPO3/Vhs/ViewHelpers"
	 data-namespace-typo3-fluid="true">

	<f:section name="Main">
		<v:system.timestamp />
	</f:section>

</div>

Is there anything I can do?

Thank you

Naderio

**Comment by TheNaderio** [comment]
Sorry - forgot some infos 0:-)

TYPO3 8.7.1
VHS 4.2.0

flux 8.2.1
fluidpages 4.1.0
fluidcontent 5.2.0

Thank you

**Comment by TheNaderio** [comment]
Edited typo in title

**Comment by xf-** [comment]
confirmed

**Comment by ubermanu** [comment]
See #1260

**Comment by ubermanu** [comment]
I figured it out, for some reason the given **controllerContext** in `UncacheTemplateView.php` as lost its templatePaths values

Here is a small fix, maybe someone more experienced could take a look into it
https://gist.github.com/ubermanu/b3a801aada5f229ecc6468183db3b5ae

**Comment by NamelessCoder** [comment]
Solved in dev-development, TER release is pending (note: loss of templatepaths is a different issue, closing this one which is about the object manager).
