### ISSUE TITLE
LanguageMenuViewHelper generates URLs for not configured languages.

### ISSUE THREAD

**Issue by mat-hew1** [FluidTYPO3/vhs#1319]
Assume we have a domain with 30 languages and an other one with only 2. In the second domain generates LanguageMenuViewHelper all 30 language links, and the all will be cached by RealUrl in the table  tx_realurl_urldata in the following form:
de_INT/ (L=0)
en_INT/ (L=1)
de_INT/ (L=2,3,4,...).
The RealUrl decoding mechanism matches than for de_INT/ all 29 languages and ends with page not found.

**Comment by mat-hew1** [comment]
I know, it is very strange to resolve this issue. The information, which languages are allowed for the current domain is not clean saved in some configuration. My suggestion is an additional configuration parameter which limits the language list.

**Comment by NamelessCoder** [comment]
Set `hideNotTranslated` to a non-false value.

**Comment by NamelessCoder** [comment]
Possibly also affected by https://github.com/FluidTYPO3/vhs/commit/f1c2fbf807421d1bf66b31c5c9e85e79768177aa - that patch combined with `hideNotTranslated` should do the trick also
