### ISSUE TITLE
v:content.render() do not render translated content if only contentUids defined

### ISSUE THREAD

**Issue by glucka** [FluidTYPO3/vhs#1321]
{v:content.render(contentUids:'{0:contentUid}')} works only in default language

**Comment by EdRoxter** [comment]
I tested your workaround, and it results in the content element being rendered twice - once with the translated record's uid, once with the original record's uid (as I can tell from the container div id) - but both in the correct, current (non-default) language. Guess this needs some fine tuning, but I can confirm the bug at least.

**Comment by jonaseberledmind** [comment]
In Typo 7.6.23 I still am not able to fetch translated records.

Given 
`<v:content.render contentUids="{0: 111}"/>`
where 111 is the uid of the tt_content element in the default language, it does not render anything in a non-default language.

111 is translated.

(We use Typo3 config.sys_language_overlay=1 and I tried config.sys_language_mode=default and content_fallback)
