### ISSUE TITLE
v:asset ViewHelper timestamp problems

### ISSUE THREAD

**Issue by taalas** [FluidTYPO3/vhs#1324]
Hi,

I am using v:asset in an uncached environment. When generating the final asset files the ViewHelper will append a timestamp to the file (this is a TYPO3 setting if i understand correctly). The files are generated on every page call though, leading to a new TS every call and thus preventing client-side browser caching. When importing assets through TypoScript the appended timestamps seem to be taken from the source files and therefore cache without problems. Is there a way to force v:asset to use the files timestamp (or the newest file's timestamp in case of concatenation)?

**Comment by NamelessCoder** [comment]
Not related to VHS as such - the appending of timestamp can be controlled via TYPO3's setting `$GLOBALS['TYPO3_CONF_VARS']['FE']['versionNumberInFilename']`.
