### ISSUE TITLE
<v:if does nothing or produces error

### ISSUE THREAD

**Issue by wini2** [FluidTYPO3/vhs#1328]
hello,

when i try to use v:if in TYPO3 8.7.1/ vhs 4.2.0 
i only get no output or error.

i tried various examples, e.g . https://github.com/FluidTYPO3/vhs/pull/401

{namespace v=FluidTYPO3\Vhs\ViewHelpers} inserted on top of the code-examples.

Are there more settings/prerequisites that are not mentioned there? If it's not a bug, please post a complete working example.

thanks

**Comment by NamelessCoder** [comment]
Please use `f:if` instead; `v:if` is useful only on TYPO3 7.6. Examples at https://github.com/TYPO3/Fluid/blob/master/examples/Resources/Private/Singles/Conditions.html
