### ISSUE TITLE
IfViewHelper Class 'TYPO3\CMS\Fluid\Core\Parser\SyntaxTree\BooleanNode' not found

### ISSUE THREAD

**Issue by griesi007** [FluidTYPO3/vhs#1332]
Typo3 8.7.2 LTS / VHS 4.2.0

I am facing the below mentioned error. The mentioned class is not present in Typo3 anymore. So far as I can see it must be TYPO3Fluid\Fluid\Core\Parser\SyntaxTree\BooleanNode. Also in line 113 the method BooleanNode::evaluateComparator is called which does not exist any more in Boolean Node

Class 'TYPO3\CMS\Fluid\Core\Parser\SyntaxTree\BooleanNode' not found
Error thrown in file
\typo3conf\ext\vhs\Classes\ViewHelpers\IfViewHelper.php in line 113.

**Comment by griesi007** [comment]
Fluid Standalone was not installed

**Comment by griesi007** [comment]
Reopened

**Comment by NamelessCoder** [comment]
The ViewHelper is deprecated and we're getting closer to dropping 7.6 support (at which point this VH gets removed). This probably won't be fixed, but the good news is on 8.7 you can use `f:if` which supports complex expressions as well. A few examples are given on https://github.com/TYPO3/Fluid/blob/master/examples/Resources/Private/Singles/Conditions.html.

If you need your template to be compatible with 7.6 despite this deprecation, you can assign a boolean to your template if the old boolean node class exists and then toggle between using `f:if` and `v:if` as required if that boolean is true. That also makes it easier to completely drop `v:if` when you bump your template's minimum TYPO3 requirement.

**Comment by tgaertner** [comment]
<f:if condition="{var}==1" else="{var}==2"> outputs "==2" for an empty {var} whats wrong???

**Comment by NamelessCoder** [comment]
@tgaertner Please don't use GitHub for support questions. I suggest StackOverflow with question tagged with `typo3`. The question you ask there is also in no way related to VHS so I'd appreciate if you consider if you found right right place before you post. In this case you most surely didn't ;)

**Comment by NamelessCoder** [comment]
Closing issue; suggested workaround takes care of dual version support and recommended approach on 8.7 LTS is to use `f:if`.

**Comment by SventB** [comment]
I'm also getting this error, with fluid condition
`<f:if condition="{cond1} || {cond2}">`

TYPO3 8.7.8, vhs 4.3.3
