### ISSUE TITLE
v:variable.set/get caching problem, Variable becomes NULL

### ISSUE THREAD

**Issue by jwittorf** [FluidTYPO3/vhs#1334]
Using:

* typo3-ter/vhs 4.2.0
* typo3/cms 8.7.3

What I'm doing/testcase:

```
<v:variable.set name="panelStateIndex" value="-1" />
<h1>panelStateIndex: <v:variable.get name="panelStateIndex"/></h1> <!-- should be -1 -->
<v:variable.set name="panelStateIndex" value="0" />
<h1>panelStateIndex: <v:variable.get name="panelStateIndex"/> <!-- should be 0 -->
```

This works fine when you clear the cache and open the page. The second `<v:variable.get/>` shows 0. But if you reload the page (aka get the cached version), it's empty. To be exact it's `NULL` according to `<f:debug/>`.

So the problem is, that somehow it's not possible to overwrite an already set (and cached) variable. When setting the variable, the variable becomes `NULL`.

**Comment by NamelessCoder** [comment]
Thanks for the test case - I'm assuming your actual code isn't this simple, so there could be many things inbetween which causes issues. But regardless:

* Have you tried setting this variable with `<f:variable name="panelStateIndex" />` which is the recommended way on the new Fluid engine?
* Is there a specific reason you use `<v:variable.get>` instead of simply `{panelStateIndex}`? What I'm fishing for here is: is it possible your variable name contains a dot and/or a dynamic segment? Note that body are supported on the new Fluid, for example as `{settings.{dynamicPart}}`.

The only reason to use either of these on TYPO3 8.7+ would be if your extension/template also needs to be compatible with TYPO3 7.6. If you don't need this, switching to the native ViewHelper and standard variable access should solve it. You should also expect `v:variable.set` and `get` to be deprecated fairly soon (as soon as VHS raises minimum TYPO3 requirement to 8.7+).

**Comment by jwittorf** [comment]
Thanks for the quick response. Indeed my actual code is a bit more complex.

I wasn't yet aware of the `<f:variable name="panelStateIndex" />` so now I'm using that. But the problem still occurs.

I was using `<v:variable.get/>` just to output it in the `<h1/>`, now I'm just using `{panelStateIndex}` but it's still with the same result. On first, fresh load everything is fine. On second, cached load it's `NULL`.

So it seems to be a core bug, for the record, here is more of my code:

```
<div xmlns="http://www.w3.org/1999/xhtml" lang="en"
	 xmlns:v="http://typo3.org/ns/FluidTYPO3/Vhs/ViewHelpers"
	 xmlns:flux="http://typo3.org/ns/FluidTYPO3/Flux/ViewHelpers"
	 xmlns:f="http://typo3.org/ns/fluid/ViewHelpers">

	<f:layout name="Content" />

	<f:section name="Configuration">
		<flux:form id="accordion" extensionName="nws_scaffolding" localLanguageFileRelativePath="/Resources/Private/Language/locallangContent.xlf">
			<flux:form.option name="group" value="{f:translate(key: 'LLL:EXT:nws_scaffolding/Resources/Private/Language/locallangContent.xlf:flux.advanced.elements')}"/>
			<flux:form.section name="panelAdd">
				<flux:form.object name="panelObject">
					<flux:field.input name="panelTitle" required="1" />
					<flux:field.checkbox name="panelState" />
				</flux:form.object>
			</flux:form.section>
			<flux:grid>
				<f:for each="{panelAdd}" as="panelObjectItem" iteration="iteration">
					<flux:grid.row>
						<flux:grid.column name="panelContent.{iteration.index}" label="{panelObjectItem.panelObject.panelTitle}" />
					</flux:grid.row>
				</f:for>
			</flux:grid>
		</flux:form>
	</f:section>

	<f:section name="Preview">
		<b><f:translate key="LLL:EXT:nws_scaffolding/Resources/Private/Language/locallangContent.xlf:flux.accordion"/></b><br>
		<v:condition.type.isArray value="{panelAdd}">
			<f:else>
				<f:translate key="LLL:EXT:nws_scaffolding/Resources/Private/Language/locallangContent.xlf:flux.default.message"/>
			</f:else>
		</v:condition.type.isArray>
	</f:section>

	<f:section name="Main">
		<f:variable name="panelStateIndex" value="-1" />
		<f:for each="{panelAdd}" as="panelObjectItemIterator" iteration="iteration">
			<f:if condition="{panelObjectItemIterator.panelObject.panelState}">
				<f:variable name="panelStateIndex" value="{iteration.index}" />
			</f:if>
		</f:for>
		<f:debug>{panelStateIndex}</f:debug>
		<div class="panel-group" id="accordion-{record.uid}" role="tablist" aria-multiselectable="true">
			<f:for each="{panelAdd}" as="panelObjectItem" iteration="iteration">
				<div class="panel panel-default">
					<div class="panel-heading" role="tab" id="#heading-{record.uid}">
						<h4 class="panel-title">
							<a class="accordion-toggle {f:if(condition: '{panelStateIndex} != {iteration.index}', then: 'collapsed')}"
							   role="button"
							   data-toggle="collapse"
							   data-parent="#accordion-{record.uid}"
							   href="#panel-{record.uid}-{iteration.index}"
							   aria-expanded="{f:if(condition: '{panelStateIndex} == {iteration.index}', then: 'true', else: 'false')}">
								{panelObjectItem.panelObject.panelTitle}
							</a>
						</h4>
					</div>
					<div id="panel-{record.uid}-{iteration.index}"
						 role="tabpanel"
						 aria-labelledby="#heading-{record.uid}"
						 class="panel-collapse collapse {f:if(condition: '{panelStateIndex} == {iteration.index}', then: 'in')}">
						<div class="panel-body">
							<flux:content.render area="panelContent.{iteration.index}" />
						</div>
					</div>
				</div>
			</f:for>
		</div>
	</f:section>

</div>
```

I'm rebuilding the twitter bootstrap accordion. I'm using a variable with a dot but that's just how it's supposed to be, e.g. `{iteration.index}`.

**Comment by pravin-vavadiya** [comment]
@jwittorf  if you find the solution for this, then give me suggestion how to resolved this. i have same problems in <v:variable.set > with TYPO3 8.7

**Comment by nothdurfterf** [comment]
@jwittorf and @pravin-vavadiya 
I had the same problem. I used a similar stucture as  you jwittorf.
It seem like to problem is related to something like – empty() instead of isset()
Fixed it with following code using an associative array for my custom variable:
```
<f:variable name="temp" value="{activeTabIndex:0}" />
<f:for each="{panels}" as="panel" iteration="iterator">
    <f:if condition="{panel.panel.active}">
        <f:variable name="temp" value="{activeTabIndex:iterator.index}" />
    </f:if>
</f:for>
```

**Comment by gessulatgessulat** [comment]
I had the same issue and it turnd out that setting a variable to value "0" will unset it/set it to NULL after second load.
So just set anything else as value but never "0".

<v:variable.set name="myVar" value="0"/> = Not working
<v:variable.set name="myVar" value="true"/> = Working

**Comment by tiggr** [comment]
In the compiled fluid code is of viewhelpers using CompileWithContentArgumentAndRenderStatic trait is just a check for a truethy value of the content attribute. I this is not the case the elements content will be used. See https://github.com/TYPO3/Fluid/pull/354
To work around ftm one can rewrite
<v:variable.set name="panelStateIndex" value="0" />
to
<v:variable.set name="panelStateIndex">0</v:variable.set>

**Comment by NamelessCoder** [comment]
Fix has been committed to Fluid@dev-master and will be included in the next release(s). Closing this issue as solved, but is technically not solved on your end until you can `composer update` Fluid.

Locking issue - should you encounter any further problems with assigning a variable with this VH or `f:variable` please report the problem on Fluid's bug tracker.
