### ISSUE TITLE
Subresource Integrity

### ISSUE THREAD

**Issue by dzach7442** [FluidTYPO3/vhs#1337]
I am using the ViewHelper v:asset.script and v:asset.style in conjunction with tagsAddSubresourceIntegrity. Works great, except for Firefox and Chrome.

Here you need the tag (crossorigin = "anonymous"). Could this be permanently added in the file Classes / Service / AssetService.php?

if (null !== $integrity && !empty($integrity)) {
$tagBuilder->addAttribute('crossorigin', 'anonymous');
$tagBuilder->addAttribute('integrity', $integrity);
}

**Comment by NamelessCoder** [comment]
Hi David,

This sounds reasonable and if it doesn't break anything then you're very welcome to create a pull request that adds this attribute.

**Comment by NamelessCoder** [comment]
Crossorigin=anonymous will be added automatically now if `plugin.tx_vhs.settings.prependPath` is not set in TypoScript.
