### ISSUE TITLE
IsNumericViewHelper's trait is incompatible with TYPO3 v8

### ISSUE THREAD

**Issue by xperseguers** [FluidTYPO3/vhs#1340]
The trait in use in the IsNumericViewHelper:

https://github.com/FluidTYPO3/vhs/blob/development/Classes/ViewHelpers/Condition/String/IsNumericViewHelper.php#L23

is not needed anymore for TYPO3 v8 and even leads to a clash with compiled conditions in 8.x. The base class is sufficient for the VH to work properly.

When this trait is being injected in TYPO3 v8, the VH is doing its job *right after* a full TYPO3 cache flush, for exactly one request but as soon as you refresh the page, its output content is gone!

**Comment by NamelessCoder** [comment]
Solution under review at https://github.com/FluidTYPO3/vhs/pull/1241 - sorry, I forgot about that one when we discussed this issue. I'll close this issue but please do subscribe to the PR to know when it gets merged ;)
