### ISSUE TITLE
Flags lost for LanguageMenuViewHelper in TYPO3 8.7.3

### ISSUE THREAD

**Issue by MarkusBausK** [FluidTYPO3/vhs#1342]
In my case there are no more flags shown by the LanguageMenuViewHelper after an update from TYPO3 8.7.0 to 8.7.3. Maybe they changed something with the icon path again?

**Comment by MarkusBausK** [comment]
It is because they fixed "the bug" that the flags are SVGs. Instead there are PNGs now and the old path the viewhelper is using too is not working anymore. Checkout the path to the icons in the TYPO3 Core...

**Comment by NamelessCoder** [comment]
You can use the `flagImageType` argument on the ViewHelper to work around this. Alternatively, if your project must run on multiple TYPO3 versions, have a dynamic variable for this that you set according to TYPO3 version.

We can restrict the TYPO3 requirement further at some point, but probably not until 8.7 becomes the minimum requirement (in which case we only have to consider bugfix releases for differences in such API). There's no scheduled time when this may happen but at the very least it won't be until TYPO3v9 gets released and probably not even for a good while after that. So do use the suggested workarounds ;)

**Comment by MarkusBausK** [comment]
Thank you Claus! Maybe it might be helpful to preven new issues to this case to add this information to the docs https://fluidtypo3.org/viewhelpers/vhs/master/Page/LanguageMenuViewHelper.html, isn't it?
