### ISSUE TITLE
Transparent canvasColor v:image / v:uri.image

### ISSUE THREAD

**Issue by Scarbous** [FluidTYPO3/vhs#1346]
Hi,
the `canvasWidth` and `canvasHeight` feature are very nice.
But is it Posible, that the `canvasColor` is transparent?

I know that all images musst be **PNGs** but in some cases it would be very nice.

**Comment by bjo3rnf** [comment]
Hi Sascha,

since we use ImageMagick for image manipulation this would be possible by adding a new argument `transparentColor` that expects another color value to be made transparent. I can create a PR for that at the weekend.

Cheers
Björn

**Comment by NamelessCoder** [comment]
Added as new feature thanks to @bjo3rnf :)
