### ISSUE TITLE
[BUG] v:iterator.first trait

### ISSUE THREAD

**Issue by ogrosko** [FluidTYPO3/vhs#1352]
Class `FluidTYPO3\Vhs\ViewHelpers\Iterator\FirstViewHelper` uses `TYPO3Fluid\Fluid\Core\ViewHelper\Traits\CompileWithContentArgumentAndRenderStatic` trait which is not available in typo3 7.6

**Comment by NamelessCoder** [comment]
It is available but you need 7.6.13 as minimum.
