### ISSUE TITLE
v:resource.image error with TYPO3 v.8.7

### ISSUE THREAD

**Issue by carodb** [FluidTYPO3/vhs#1353]
When using the `<v:resource.image />` ViewHelper the following error message occurs: 
`Call to undefined method TYPO3\CMS\Core\Utility\GeneralUtility::png_to_gif_by_imagemagick()`
In the changelog the function is listed as deprecated and removed. If I comment the calls to said function, it works again.

**Comment by dprecup** [comment]
I have the same issue

**Comment by bjo3rnf** [comment]
The deprecated call has been removed a while ago in #1305. Which version of vhs are you both using?

**Comment by carodb** [comment]
Still in master, can we expect it to be pushed to master soon or do you recommend updating to development?

**Comment by cedricziel** [comment]
We better ask @NamelessCoder for a new release :)

**Comment by carodb** [comment]
Yes,please! That would be awesome :) 👍

**Comment by NamelessCoder** [comment]
I may do some release cooking tonight :)
