### ISSUE TITLE
v:asset.script filename too long --> 403

### ISSUE THREAD

**Issue by filoucrackeur** [FluidTYPO3/vhs#1354]
when generated name file is too long 403 forbidden.

exemple:

https://toto.com/typo3temp/vhs-assets-smart-tribune-google-search-custom-google-search-assistanceJs-tag-commander-events-common-tag-commander-events-particuliers-wannaspeak-fdgfdgfd-gdfg-fdg-dfg-dfg-df-da97860338372130a9591679589258cb-9059bb4003d624ca3bc21101e350fc98-9409b641277256f5419b8e8eea352322.js

i think it a physical limit name file on server that can't have more than 256 caracters.

**Comment by bjo3rnf** [comment]
You may want to use
```
plugin.tx_vhs.assets {
	mergedAssetsUseHashedFilename = 1
}
```

Cheers
Björn

**Comment by filoucrackeur** [comment]
thanks you it works

**Comment by bjo3rnf** [comment]
nice.
