### ISSUE TITLE
LanguageMenuViewHelper throws Exception after update

### ISSUE THREAD

**Issue by Sebastian-Habiger** [FluidTYPO3/vhs#1363]
#1476107295: PHP Warning: Invalid argument supplied for foreach() in .../typo3conf/ext/vhs/Classes/ViewHelpers/Page/LanguageMenuViewHelper.php line 291

I think condition on line 286 schould be inverted!

``if (**!**empty($limitLanguages)) {
``    $where = 'uid IN ('.implode(',', $limitLanguages).')';
``} else {
``    $where = '1=1';
``}

**Comment by jdreesen** [comment]
This is a duplicate of #1359 which has alredy been fixed in #1361 (but has not been released yet).

**Comment by Sebastian-Habiger** [comment]
thx
