### ISSUE TITLE
htmlencoded src in Media/ImageViewHelper 

### ISSUE THREAD

**Issue by mikevinmike** [FluidTYPO3/vhs#1364]
In version 4.3 FluidTYPO3\Vhs\ViewHelpers\Media\ImageViewHelper generates htmlencoded src with 
`<v:media.image src="fileadmin/Roadtrip-LP37-two-girls-peeking-out-car.jpg" alt="AAA" class="imgWidth100HeightAuto" width="1140c" height="814c" quality="200" title=""/>`

The outcome is 
`<img class="imgWidth100HeightAuto" width="1140" height="814" src="/fileadmin%2F_processed_%2F2%2F3%2Fcsm_Roadtrip-LP37-two-girls-peeking-out-car_68cb015f58.jpg" title="">`

This does not occur with version 4.2.

**Comment by othmar52** [comment]
the value of the `srcset` attribute is also affected by this bug

**Comment by supercosh** [comment]
In /Classes/ViewHelpers/Media/AbstractMediaViewHelper.php rawurlencode() is used, which escapes slashes to %2f, therefore URI's are not working anymore. This has changed from 4.2 to 4.3 and is breaking all viewhelpers inheriting from AbstractMediaViewHelper.

**Comment by NamelessCoder** [comment]
If you have the time, please confirm if https://github.com/FluidTYPO3/vhs/pull/1367 solves the issue on your setup. Thanks :)

**Comment by cushingw** [comment]
We encountered the same issue with 4.3.1 and <v:uri.image> and #1367 resolved the issue for us.

**Comment by NamelessCoder** [comment]
Solved in dev-development, TER release is pending.
