### ISSUE TITLE
Bug for column=0 in content.render

### ISSUE THREAD

**Issue by freshman20** [FluidTYPO3/vhs#1365]
Since 4.3.0 there is not possible select column="0".
Example:
`<v:content.render column="0" pageUid="1" />`
Bug in FluidTYPO3\Vhs\ViewHelpers\Content\AbstractContentViewHelper Line 156
`
if ($this->arguments['column']) {
..
}
`

**Comment by dahaupt** [comment]
@freshman20 This got probably fixed already with #1362 but is not released yet. You can use "dev-development" in your composer.json to solve it.

@NamelessCoder  Is a hotfix version **4.3.1** possible before other devs run into this?

**Comment by freshman20** [comment]
Thank

**Comment by dev-rke** [comment]
A Hotfix release would be very helpful. :-)
