### ISSUE TITLE
v:render.uncache : Cannot instantiate interface TYPO3\CMS\Extbase\Object\ObjectManagerInterface

### ISSUE THREAD

**Issue by stephangrass** [FluidTYPO3/vhs#1369]
Hi,
I tried to use the v:render.uncache ViewHelper (TYPO3 8LTS, VHS 4.3) but I get the error:

Cannot instantiate interface TYPO3\CMS\Extbase\Object\ObjectManagerInterface

Error thrown in file
/Users/stephangrass/Documents/_Webs_/hs-mannheim.de/typo3/typo3_src-8.7.4/typo3/sysext/core/Classes/Utility/GeneralUtility.php in line 3893

**Comment by cedricziel** [comment]
Thx for reporting, I already created a pull request which fixes the bug #1368 and is open for review.
