### ISSUE TITLE
How get content image from tab "appearance" using only "ViewHelper"?

### ISSUE THREAD

**Issue by Lukaschel** [FluidTYPO3/vhs#1371]
The appearance media got his image relation to the content elements in the sys_file_reference database table.
Is it possible to get the image file by using the ViewHelper and the content.uid?

**Comment by NamelessCoder** [comment]
Please use StackOverflow or the IRC channel for support questions. I suggest posting on StackOverflow and tagging the question with `typo3` and `vhs` for maximum exposure.
