### ISSUE TITLE
EliminateViewHelper and escapeOutput

### ISSUE THREAD

**Issue by Apen** [FluidTYPO3/vhs#1373]
In the EliminateViewHelper (Classes/ViewHelpers/Format/EliminateViewHelper.php) the "escapeOutput" is missing:

```php
    /**
     * @var boolean
     */
    protected $escapeOutput = false;
```

**Comment by Apen** [comment]
Hi,

Is it possible to add this in the ViewHelper?
Do you need extra informations?

Thx

**Comment by NamelessCoder** [comment]
I think this has to be solved by enclosing with `f:format.raw` to disable the escaping intentionally, and only in the cases where you truly want an unescaped string to be allowed. Generally speaking, formatting ViewHelpers which do not themselves produce HTML, should always escape the output as any HTML it then produces, would be coming from variables that may not be safe.

Makes sense? I could be missing something about your use case...

**Comment by Apen** [comment]
No, you're totally right, i didn't this this with this point of view 👍 
You can close this, the post "format.raw" works like a charm.

Thx Claus.
