### ISSUE TITLE
Regarding the TER security breach / issue with v4.3.0

### ISSUE THREAD

**Issue by MrMooky** [FluidTYPO3/vhs#1377]
We received an urgent email from our hoster Mittwald regarding the current version of VHS, claiming of certain critical security gaps within the extension.

Also, the latest version has been removed from the TER. Are you guys aware of that and working on a fix?

**Comment by cedricziel** [comment]
Please forward the mail to me.

**Comment by MrMooky** [comment]
I just got the info that the issues were not directly related to VHS, sorry for the confusion. Apparently, the leak was with the TYPO3 TER:

> durch die TYPO3 Association wurde bekannt gegeben, dass im TYPO3 Extension Repository (TER) ein kritisches Sicherheitsproblem existierte. So könnte es im Zeitraum 23.08.2017 bis 06.08.2017 möglichichweise zu unautorisierten Änderungen an einigen Extensions im TER gekommen sein.
> Wir empfehlen dringend ein Update auf eine neue Version durchzuführen oder die Extension zu deinstallieren. Wenn Sie Ihre Installation nicht selbst verwalten, nehmen Sie bitte unbedingt Kontakt zur Ihrem Entwickler bzw. Ihrer Agentur auf! Diese können Sie bei der Prüfung Ihrer Installation unterstützen.
> Folgenden TYPO3 Extension müssen ein Update erhalten: vhs (4.3.0)

**Comment by cedricziel** [comment]
Alright, I know what they mean and they're correct - the TER had the potential for insecure uploads. @NamelessCoder can we upload a 4.3.1 patch release just to reasure our users?

**Comment by tantegerda1** [comment]
If so, please clearly state whether its just a re-upload of the same state as 4.3.0 was or whether it incorporates recent changes too (eagerly waiting for official version solving #1327).

**Comment by NamelessCoder** [comment]
Done, and yes it contains only metadata change with dummy changelog and version bump. Note that 4.3.1 also has the bug regarding colPos=0 in v:content.render and problems rendering language menus with v:page.languageMenu so you probably don't want to install it.
