### ISSUE TITLE
Uncache-Viewhelper produces Exception in TYPO3 7.6

### ISSUE THREAD

**Issue by Lumrenion** [FluidTYPO3/vhs#1378]
As already commented here:
https://github.com/FluidTYPO3/vhs/commit/94c3d77daffa0f9ad65c3b6136f26f0131bab90f#commitcomment-24065966

On TYPO3 7.6, the uncache-Viewhelper produces an exception. That is because the ObjectManager is initialized via GeneralUtility::makeInstance with "ObjectManagerInterface".

**Comment by NamelessCoder** [comment]
Already fixed in dev-development, and has at least one duplicate issue - please don't forget to check code and open issues before opening new ones.
