### ISSUE TITLE
SQL error in viewhelper LanguageMenu

### ISSUE THREAD

**Issue by morinfa** [FluidTYPO3/vhs#1379]
Tag 4.3.1.
In class LanguageMenuViewHelper, function parseLanguageMenu :
```
        if (empty($limitLanguages)) {
            $where = 'uid IN (' . implode(',', $limitLanguages) . ')';
        } else {
            $where = '1=1';
        }
```

If $limitLanguages array is empty, the following where clause is generated :
`uid IN ()`

**Comment by NamelessCoder** [comment]
This is already solved in dev-development; `!empty()` is now used.
