### ISSUE TITLE
content.get returns null

### ISSUE THREAD

**Issue by DanielRuf** [FluidTYPO3/vhs#1380]
`<f:debug>{v:content.get(pageUid:528)}</f:debug>` returns null even if there is content on the page with the given ID.

And when I change the parameters and add for example `render: 0` the debug output is suddenly missing.

```
Argument 1 passed to FluidTYPO3\Vhs\ViewHelpers\Content\AbstractContentViewHelper::getRenderedRecords() must be of the type array, null given, called in /web/typo3conf/ext/vhs/Classes/ViewHelpers/Content/AbstractContentViewHelper.php on line 111
```

**Comment by DanielRuf** [comment]
I am currently checking if we use the latest version and if it works with languages as we use translated pages.

https://github.com/FluidTYPO3/vhs/issues/1327

**Comment by DanielRuf** [comment]
Still the same with 4.3.1

**Comment by DanielRuf** [comment]
The problem is `hideNonTranslated`. See https://github.com/FluidTYPO3/vhs/issues/1327#issuecomment-325915031

**Comment by NamelessCoder** [comment]
https://github.com/FluidTYPO3/vhs/pull/1366 should be relevant here.

**Comment by DanielRuf** [comment]
> #1366 should be relevant here.

Yes, this solves it on my side, I get the needed results (an array with the content elements). :+1:

**Comment by DanielRuf** [comment]
Awesome, the 4.3.2 release fixed it, thanks =)
