### ISSUE TITLE
v:content.render column="0" does not work anymore

### ISSUE THREAD

**Issue by RosenbauerSolbach** [FluidTYPO3/vhs#1382]
I tried to update vhs 4.2 to 4.3.1 today. TYPO3 version is 8.7.6.

<v:content.render column="0"/>
This renders every column, not only colPos=0 in new version 4.3.1

If I set any value, except 0 it work as it should
<v:content.render column="2" />

Maybe that 0 acts like a FALSE?

**Comment by InvisibleKind** [comment]
Related to #1327

**Comment by dogawaf** [comment]
Fixed by #1362

**Comment by NamelessCoder** [comment]
Solved in dev-development, TER release is pending.
