### ISSUE TITLE
v:content.render Zero not possible anymore

### ISSUE THREAD

**Issue by RozbehSharahi** [FluidTYPO3/vhs#1387]
Hello,

i think there is a logical error in the following commit:

https://github.com/FluidTYPO3/vhs/commit/490404e3a627a3c5f72ae4dea6e0b999c63ed2d4

This way it is not possible to render only contents from column id 0 anymore.

The argument column should be `null` on default and the condition should check for `is_null($this->arguments['columns'])`.

Kind regards,
Rozbeh Chiryai Sharahi (Robert)

**Comment by NamelessCoder** [comment]
Duplicates:

https://github.com/FluidTYPO3/vhs/issues/1382
https://github.com/FluidTYPO3/vhs/issues/1380
https://github.com/FluidTYPO3/vhs/issues/1365

Please check recently closed issues before opening new ones. Thanks!
