### ISSUE TITLE
LanguageMenuViewhelper $inactive is always true

### ISSUE THREAD

**Issue by EnzephaloN** [FluidTYPO3/vhs#1391]
The LangaugeMenuViewhelper is broken, because $inactive in row 323 is always 1.
I debugged a lot, but wasn't able to find why inactive is always "true".

Something with 
 $inactive = in_array($key, $languageUids) || (integer) $key === $this->defaultLangUid ? 0 : 1;

**Comment by EnzephaloN** [comment]
I debugged the SQL for $sysLang (which is empty) - generated by getRecords() at row 318:

`SELECT sys_language_uid, pages_language_overlay.uid as uid, pages_language_overlay.pid as pid, pages_language_overlay.t3ver_state as t3ver_state FROM pages_language_overlay WHERE pages_language_overlay.pid IN (1) AND (pages_language_overlay.sys_language_uid = 0) AND pages_language_overlay.deleted=0 AND pages_language_overlay.t3ver_state<=0 AND pages_language_overlay.pid<>-1 AND pages_language_overlay.hidden=0 AND pages_language_overlay.starttime<=1506403500 AND (pages_language_overlay.endtime=0 OR pages_language_overlay.endtime>1506403500)`

Here we see that there is a faulty where-part: **pages_language_overlay.sys_language_uid = 0**

I will investigate the other problem "$inactive always true" - I think thats because the OR-conjunction-result is always true if both values are false... maybe...

**Comment by EnzephaloN** [comment]
I think this whole part has to be:

'
foreach ($languageMenu as $key => $value) {
            $current = $GLOBALS['TSFE']->sys_language_uid === (integer) $key ? 1 : 0;
            $inactive = !in_array($key, $languageUids) || (integer) $key === $this->defaultLangUid ? 0 : 1;
            $url = $this->getLanguageUrl($key);
            if (true === empty($url)) {
                $url = GeneralUtility::getIndpEnv('REQUEST_URI');
            }
            $languageMenu[$key]['current'] = $current;
            $languageMenu[$key]['inactive'] = $inactive;
            $languageMenu[$key]['url'] = $url;
            $languageMenu[$key]['flagSrc'] = $this->getLanguageFlagSrc($value['flag']);
            if (true === (boolean) $this->arguments['hideNotTranslated'] && true === (boolean) $inactive && !$current) {
                unset($languageMenu[$key]);
            }
        }
'

**Comment by EnzephaloN** [comment]
Broken LanguageMenu is in version 4.3.2 - version 4.3.0 works fine without problems - with hideNotTranslated=1

**Comment by EnzephaloN** [comment]
One problem is:

`$sysLang = $GLOBALS['TSFE']->cObj->getRecords($table, ['selectFields' => 'sys_language_uid', 'pidInList' => $this->getPageUid()]);`

results in

`SELECT 
   sys_language_uid, 
   pages_language_overlay.uid as uid, 
   pages_language_overlay.pid as pid, 
   pages_language_overlay.t3ver_state as t3ver_state 
FROM 
   pages_language_overlay 
WHERE 
   pages_language_overlay.pid IN (1) 
   AND 
     (pages_language_overlay.sys_language_uid = 0) 
   AND 
     pages_language_overlay.deleted=0 
   AND 
     pages_language_overlay.t3ver_state<=0 
   AND 
     pages_language_overlay.pid<>-1 
   AND
     pages_language_overlay.hidden=0 
   AND 
     pages_language_overlay.starttime<=1506413700 
   AND 
     (pages_language_overlay.endtime=0 OR pages_language_overlay.endtime>1506413700)`

but I think **(pages_language_overlay.sys_language_uid = 0)** is wrong here, because we need all rows (all languages) for pages_language_overlay.pid IN (1)

**Comment by EnzephaloN** [comment]
This is old-school, but works:
`$res = $GLOBALS['TYPO3_DB']->exec_SELECTquery('sys_language_uid',$table , 'pid IN ('.$this->getPageUid(). ') '.$this->cObj->enableFields('pages_language_overlay'));
        while($row = $GLOBALS['TYPO3_DB']->sql_fetch_assoc($res)){
        	$sysLang[] = $row;
        }`

**Comment by xf-** [comment]
confirmed

**Comment by RozbehSharahi** [comment]
By setting the languageField in line 318 of the view helper to 0 the problem seems to be solved. Still im not sure if this is the right configuration for getRecords.
```
$table = 'pages_language_overlay';
$sysLang = $GLOBALS['TSFE']->cObj->getRecords($table, ['selectFields' => 'sys_language_uid', 'pidInList' => $this->getPageUid(), 'languageField' => 0]);
$languageUids = array_column($sysLang, 'sys_language_uid');
```
Kind regards 
Rozbeh Chiryai Sharahi and Joao Cunha
