### ISSUE TITLE
Since 4.0.0 CType shortcut doesn't work anymore

### ISSUE THREAD

**Issue by Atomschinken** [FluidTYPO3/vhs#1395]
Hi,

im seeing some sort of strange behaviour:
Although the Container Template doesn't even use vhs directly, when the grid.column is filled with referenced items (CType "shortcut"), nothing is rendered. "Normal" content elementes seem to work correctly.

This is a part of our teaser container template:
```
<f:switch expression="{teaser_count}">
	<f:case value="1">
		<div class="col-xs-12">{flux:content.render(area: 'teaser', limit: 1, offset: 0)}</div>
	</f:case>
	<f:case value="2">
		<div class="col-xs-12 col-md-6">{flux:content.render(area: 'teaser', limit: 1, offset: 0)}</div>
		<div class="col-xs-12 col-md-6">{flux:content.render(area: 'teaser', limit: 1, offset: 1)}</div>
	</f:case>
	<f:case value="2_66_33">
		<div class="col-xs-12 col-md-8">{flux:content.render(area: 'teaser', limit: 1, offset: 0)}</div>
		<div class="col-xs-12 col-md-4">{flux:content.render(area: 'teaser', limit: 1, offset: 1)}</div>
	</f:case>
	<f:case value="3">
		<div class="col-xs-12 col-md-4">{flux:content.render(area: 'teaser', limit: 1, offset: 0)}</div>
		<div class="col-xs-12 col-md-4">{flux:content.render(area: 'teaser', limit: 1, offset: 1)}</div>
		<div class="col-xs-12 col-md-4">{flux:content.render(area: 'teaser', limit: 1, offset: 2)}</div>
	</f:case>
	<f:case default="TRUE">
		<div class="col-xs-12">{flux:content.render(area: 'teaser', limit: 1, offset: 0)}</div>
	</f:case>
</f:switch>
```

And this is the corresponding configuration part:
```
<flux:grid>
	<flux:grid.row>
		<flux:grid.column name="teaser"></flux:grid.column>
	</flux:grid.row>
</flux:grid>
```

Versions used:
TYPO3 7.6.23
Flux 7.4.0
Fluidpages 4.0.0
Fluidcontent 5.0.0
Fluidcontent_core 1.4.0
Vhs 4.0.0

A downgrade to version 3.1.0 seems to work for now.

Cheers,

**Comment by NamelessCoder** [comment]
Have you confirmed this problem on 4.3.2?

I sincerely doubt it has any relation to VHS, or perhaps the template code you echoed above isn't the code responsible for this problem. VHS simply isn't involved in any of the code you have there. Flux is, however, and it's also out in version 8.2.1 which is a lot newer than the one you have there.

In short: please confirm this problem on the most recent versions of the extensions, preferably on dev-development, because we don't prepare bug fix releases for unsupported versions. FYI, Flux no longer supports TYPO3 7.6.

**Comment by Atomschinken** [comment]
Sadly we cannot use any version of flux greater than 7.4.0 because of the need for fluidcontent_core until we manage to switch to fsc (Is there any migration path?).
I initially tried 4.3.2 with no luck. After trying different versions of vhs, it seems to be broken since 4.0.0
I quite agree with you: It makes no sense at all. I tried several times to switch between different versions, 3.1 works, 4.x does not.
Will try dev-development and give feedback.

**Comment by Atomschinken** [comment]
So this is interesting:
Branch "development" works, 4.3.2 via composer not.
I guess i'll be waiting for 4.3.3 and see if it works there.

**Comment by NamelessCoder** [comment]
Assuming this is no longer an issue ;)
