### ISSUE TITLE
v:content.render doesn't work in 4.3.2

### ISSUE THREAD

**Issue by rafu1987** [FluidTYPO3/vhs#1396]
This used to work in version 4.3.1 but not in 4.3.2 anymore:

`<v:content.render contentUids="{0: 164}" />`

**Comment by NamelessCoder** [comment]
Please always check the `dev-development` branch before opening new issues: https://github.com/FluidTYPO3/vhs/commit/7156e917ab88a7464892bf45b5063b4b168e355a

Closing as already solved.
