### ISSUE TITLE
Eliminate not working properly in 4.3.2 with TYPO3  8.7.7

### ISSUE THREAD

**Issue by GhanshyamBhava** [FluidTYPO3/vhs#1397]
@NamelessCoder I created a variable which stores the string. I need to remove all the special character from the string and return output plain lower case.

`<v:variable.set name="var" value="{v:format.eliminate(content: '@string with special-charecter. !', characters:'@,!,#,$,%,^,*,-,:,?,.,ß' whitespace: 1, nonAscii: 1)}" />
<v:variable.set name="id" value="{v:format.case(string:'{var}',case:'lower')}" />`

I debug variable {id} but still return content value as it is

`<f:debug>{id}</f:debug>`

**Comment by tantegerda1** [comment]
btw. the `characters` argument is described as

> Characters to remove. Array or string, i.e. {0: 'a', 1: 'b', 2: 'c'} or 'abc' to remove all occurrences of a, b and c

thus you don't need the comma separation (doing so will add _the comma_ to the list of eliminated characters).
