### ISSUE TITLE
Same set of assets may produce many identical concatenated asset files

### ISSUE THREAD

**Issue by dmitryd** [FluidTYPO3/vhs#1402]
If you specify some assets without the `name` attribute, `\FluidTypo3\Vhs\Asset` will use `spl_object_hash()` function on the object to [generate](https://github.com/FluidTYPO3/vhs/blob/development/Classes/Asset.php#L257) the name. This is not the right way because `spl_object_hash()` [does not use](https://github.com/php/php-src/blob/master/ext/spl/php_spl.c#L823) object properties to calculate the hash. Rather it returns something like a representation of the internal pointer to the instance of the object. It will give different value for identical objects between executions. This function can **only** be used to check if two variables point to the same object. Even if you clone the same object, values will be different.

Here is a sample program that outputs the `spl_object_hash()` of the object and its clone multiple times. All values are different:

```php
mt_srand();
$unused = array();
for ($i = 0; $i < 10; $i++) {
    $a = new stdClass();
    $a->value = '12345';
    $objectHash = spl_object_hash($a);
    $clonedObject = clone $a;
    $clonedObjectHash = spl_object_hash($clonedObject);
    echo "[O] $objectHash\n[C] $clonedObjectHash\n\n";

    for ($j = 0; $j < mt_rand(100, 500); $j++) {
        $unused[$j] = new stdClass();
        $unused[$j]->text = str_repeat("$i", $j);
    }
}
```

Here is what I am getting:
```
[O] 000000000dea801b0000000027f3237b
[C] 000000000dea80180000000027f3237b

[O] 000000000dea809c0000000027f3237b
[C] 000000000dea801b0000000027f3237b

[O] 000000000dea80640000000027f3237b
[C] 000000000dea809c0000000027f3237b

[O] 000000000dea80900000000027f3237b
[C] 000000000dea80640000000027f3237b

[O] 000000000dea80610000000027f3237b
[C] 000000000dea80900000000027f3237b

[O] 000000000dea80760000000027f3237b
[C] 000000000dea80610000000027f3237b

[O] 000000000dea80830000000027f3237b
[C] 000000000dea80760000000027f3237b

[O] 000000000dea80790000000027f3237b
[C] 000000000dea80830000000027f3237b

[O] 000000000dea80910000000027f3237b
[C] 000000000dea80790000000027f3237b

[O] 000000000dea806b0000000027f3237b
[C] 000000000dea80910000000027f3237b
```

These results change completely from invocation to invocation.

So when it is used to generate the name, it will always produce multiple files for the same set of assets.

Possible solution would be to use `md5()` of the content or the path. I had to solve the issue for the previous version of vhs, there I used `path`. Before I solved it, we got new identical asset files generated every minute. Now I rarely see one in an hour and according to my debug log, their list of concatenated asset is truly different.

**Comment by NamelessCoder** [comment]
Thanks for the detailed error report Dmitry - you are of course correct!

The linked pull request hopefully solves the issue.

**Comment by dmitryd** [comment]
Thanks! This should fix the issue! 👍
