### ISSUE TITLE
Assets in version 4.3.1 are added in metaseo sitemap.xml

### ISSUE THREAD

**Issue by rafu1987** [FluidTYPO3/vhs#1405]
Since version 4.3.1, vhs assets are generated in metaseo extension sitemap.xml output. With version 4.2.0 there is no such error. I wasn't sure what to look for in existing issues, sorry.

**Comment by NamelessCoder** [comment]
I think you'll have to take this one to the `metaseo` extension. VHS contains no integration with it and does not register assets in any way that would make them show up as neither pages nor records that might be included in a generated sitemap.

Why the assets end up there I can't say, but as far as I understand, things don't end up in the sitemap unless you explicitly configured them to do so. I don't know the extension that well so please do ask them why it might be reading VHS or PageRenderer assets into the sitemap...

**Comment by mkempe** [comment]
Hey there,

maybe it is the same problem i described in https://github.com/FluidTYPO3/vhs/pull/1404.

@rafu1987 Can you please try out my branch to see if the pull request fixes the problem.

**Comment by NamelessCoder** [comment]
Ah I did not make that connection. I thought your assets were being rendered as target URLs in the sitemap alongside normal pages and records. If you mean the `<script>` tags end up in the sitemap then definitely, sounds like exactly the same problem as #1404.

**Comment by rafu1987** [comment]
Hey,

yes, sorry I wasn't specific enough before, it's the exact same problem as in #1404 and your fix @mkempe is working fine in my case, thank you :-)

**Comment by NamelessCoder** [comment]
#1404 is merged
