### ISSUE TITLE
VHS Version 4.3.0-4.3.2 - breadcrumb not working correctly with nav_hide pages

### ISSUE THREAD

**Issue by media-arts** [FluidTYPO3/vhs#1408]
Since Version 4.3.0 of VHS there is a problem with the viewhelper for <v:page.breadCrumb>.

It is not possible to use the breadcrumb menu correctly so that the hidden pages are not displayed in the menu. ( Typo3 BE Page Property <input value="1" data-formengine-input-name="data[pages][5][nav_hide]" onclick="document.editform['data[pages][5][nav_hide]'].value=this.checked?(document.editform['data[pages][5][nav_hide]'].value|1):(document.editform['data[pages][5][nav_hide]'].value&amp;0);TBE_EDITOR.fieldChanged('pages','5','nav_hide','data[pages][5][nav_hide]');" checked="checked" 1="" id="data_pages_5_nav_hide_0" type="checkbox"> )

Pages with page property hidden in menu will still be displayed. The option <v:page.breadCrumb showHiddenInMenu="0"> has no effect. It seems that the page property nav_hide is not processed. All pages are displayed, whether hidden in the menu or not.

The last correctly working Version is 4.2.0

**Comment by xf-** [comment]
confirmed

**Comment by xf-** [comment]
`$GLOBALS['TYPO3_CONF_VARS']['FE']['addRootLineFields'] .= ',nav_hide';` solves it. Field is not in core list for RootLineFields
