### ISSUE TITLE
v:format.replace should have default value for substring or support "constant:NAMEOFCONSTANT"

### ISSUE THREAD

**Issue by Atsyn** [FluidTYPO3/vhs#1413]
Will be better if this ViewHelper start support constants.
But will be fine if you switch argument "substring" to not require and set default value like PHP_EOL.

**Comment by NamelessCoder** [comment]
Possible to achieve with `v:const`:

`substring="{v:const(name: 'PHP_EOL')}"`

Supports all constants and works for any ViewHelper argument.

**Comment by NamelessCoder** [comment]
Closing the issue - referring to `v:const` will be the preferred solution when you need access to PHP constants in output or as arguments for other ViewHelpers.
