### ISSUE TITLE
[FEATURE] Creation of "asset-map" file to use Grunt for processing

### ISSUE THREAD

**Issue by typoworx-de** [FluidTYPO3/vhs#1415]
It would be a great (optional) feature to enable the creation of an "asset-map" file to use gulp for processing.

Using tools like Grunt is fine, but it would be much more comfortable being able to combine typo3-based assets with the Grund processing. One advantage would be to have a pre-sorted asset keeping all dependencies in mind and delivering a ready-to-process file-map for grunt css/js processors.

**Comment by bjo3rnf** [comment]
Hi,

I can't figure out how the intended workflow might look like. Would you mind elaborating on this a little please? How should grunt as a client-side tool interact with vhs as a server-side implementation?

Cheers
Björn

**Comment by NamelessCoder** [comment]
Closing due to 2 years without feedback.

**Comment by typoworx-de** [comment]
@NamelessCoder sorry lost this ticket out of focus. For a project I once made a prototype hooking into vhs to export a json-file for post-processing and skipping asset-processing inside vhs. If there is any interest drop me a message and I'll publish my prototype to github for further discussion. I think it would be best to separate such optional features in separate extension anyway.
