### ISSUE TITLE
EliminateViewHelper caseSensitive option not working

### ISSUE THREAD

**Issue by MarkusBausK** [FluidTYPO3/vhs#1416]
Hi,

I tried to use the EliminateViewHelper to eliminate whitespace and uppercase letters inline:

{v:format.eliminate(content: '{bauelement}', whitespace: 1, caseSensitive: 1)}

Whitespace is doing the job, caseSensitive is doing nothing (0 or 1).

**Comment by NamelessCoder** [comment]
You have to tell the ViewHelper which characters to eliminate or caseSensitive quite naturally has no function at all. Your ViewHelper call above explicitly only removes whitespace which by nature isn't case sensitive.

Take a look at the ViewHelper documentation for a list of supported elimination types (most of which support case sensitive elimination).
