### ISSUE TITLE
[BUGFIX] SlideCollect feature no longer works

### ISSUE THREAD

**Issue by Tuurlijk** [FluidTYPO3/vhs#1417]
The slideCollect feature on content.render broke in this commit:

https://github.com/FluidTYPO3/vhs/commit/1814e76aef4c78a086e083886c75ffde3caeead7#diff-417cbf158abab1e6739515aa2bb66ff7

I expect this code to work: `<v:content.render column="2" render="true" slideCollect="4" limit="1" />`

**Comment by NamelessCoder** [comment]
Use `slide` to control levels and `slideCollect="1"` - the `slideCollect` argument is boolean now, the slide level must be defined with `slide` and collection behavior toggled with `slideCollect`.
