### ISSUE TITLE
Image ViewHelper: Cropping naming incorrect

### ISSUE THREAD

**Issue by Karthons** [FluidTYPO3/vhs#1420]
Your concept of cropping does not align with the terminology or the functionality is wrong.

`<f:image width="1140c" image="{image}"/>`

The does a scaling and not a cropping.

`<f:image width="1140c" height="200" image="{image}"/>`

The does a cropping, but it crops the height, even though I asked the width to be cropped. The height should be resized (thus stretched) in this case.

If I am wrong, please correct me.

**Comment by tantegerda1** [comment]
The namespace `f` suggests you are using the TYPO3 CMS core Image ViewHelper, not the one from VHS, which would be:
```
{namespace v=FluidTYPO3\Vhs\ViewHelpers}
…
<v:media:image width="1140c" height="200" image="{image}"/>
```

**Comment by Karthons** [comment]
Does the functionality change?

**Comment by tantegerda1** [comment]
As far as I know the `v:media.image` ViewHelper implements advanced features like `srcset` and a canvas feature compared to the TYPO3 CMS Core Image ViewHelper. Unless you aim for that features I'd always prefer core viewhelpers.
Regarding the actual problem with cropping you should then seek help at the TYPO3 CMS project: [Slack](https://typo3.slack.com/), [Mailing List](http://lists.typo3.org/cgi-bin/mailman/listinfo), [Bug tracker](https://forge.typo3.org/)
