### ISSUE TITLE
VHS has a dependency on typo3/cms instead of typo3/cms-core

### ISSUE THREAD

**Issue by bmack** [FluidTYPO3/vhs#1429]
With TYPO3 v9, the TYPO3 core cannot be installed via composer and `composer req typo3/cms` but only using the single system extensions. Thus, EXT:vhs is not compatible with TYPO3 v9/master.

VHS` composer.json needs to be adapted to be checked against `typo3/cms-core` instead of `typo3/cms` in line 35: https://github.com/FluidTYPO3/vhs/blob/development/composer.json#L35

This change also works for TYPO3 v7 and TYPO3 v8.

**Comment by verdure-peuser** [comment]
Any updates when this gets merged ?

**Comment by Outdoorsman** [comment]
6 month later I'm seconding this too... kind of hard to use DDEV or automation with you have conflicting packages. Need `typo3-core` in our TYPO3 8.7 instance.

**Comment by foobar13372** [comment]
When will this be merged and released? This blocks a lot of deployment improvements in our projects.

**Comment by lochmueller** [comment]
Would be cool to get this feature because EXT:vhs is not usable in Composer Subtree Split configurations anymore...

**Comment by NamelessCoder** [comment]
Applied and released with 5.0.0.
