### ISSUE TITLE
Disable automatic rendering of v:menu

### ISSUE THREAD

**Issue by Domtaholic** [FluidTYPO3/vhs#1436]
Our customer want´s a fancy MainNavigation where we had to split the levels of menus.

Right now i have following markup:

```
<v:menu pageUid="{page.uid}" as="subPages">
    <f:for each="{subPages}" as="subPage" iteration="iterator">
           <v:condition.page.hasSubpages pageUid="{subPage.uid}">
                 ...
            </v:condition.page.hasSubpages>
     </f:for>
</v:menu>
``` 

cause of the condition now every subPage does have Subpages, so kinda nothing should happen. Cause of the automatic rendering, i get a ul > li list.

I really don´t get why this is implemented, turn this off as soon there is content in the <v:menu> tag, as soon i write something between the <v:menu></v:menu> i do not wan´t to use this or implement a option: disableAutomaticRendering="1" cause we ran into this problem many times before and i´m pretty sure we are not the only ones using the viewhelper this way.

The only walkaround right now would be an else where we write hidden content...

Thx for any reply on this. 

Cheers

**Comment by Domtaholic** [comment]
@NamelessCoder Thanks for the answer on this, can you show this on my example above? I don´t get what you try to explain there. As far as i understand, i should write "something" like " for every page that doesn´t have a subpage? Like 20 times in a row in a worst case scenario, which would obvious be pretty shitty... right?

**Comment by NamelessCoder** [comment]
```xml
<v:menu pageUid="{page.uid}" as="subPages">
    <!-- this comment makes v:page.menu see content and not render auto -->
    <f:for each="{subPages}" as="subPage" iteration="iterator">
           <v:condition.page.hasSubpages pageUid="{subPage.uid}">
                 ...
            </v:condition.page.hasSubpages>
     </f:for>
</v:menu>
```

**Comment by Domtaholic** [comment]
@NamelessCoder thanks for the fast replys on this. Helped me a lot.

Could you think about that option i´ve mentioned above or as soon as there is content between <v:menu></v:menu> to disable the automatic rendering, cause these feels a bit like a bad workaround.

I close this for now, cause my problem is solved.

**Comment by bjo3rnf** [comment]
I'd like to point out that
 
`<v:condition.page.hasSubpages pageUid="{subPage.uid}">...</v:condition.page.hasSubpages>`

can be replaced by

`<f:if condition="{subPage.hasSubPages}">...</if>`

Global warming you know ;)

**Comment by Domtaholic** [comment]
@bjo3rnf Thanks for that information, changed my code to this solution ;) 

Let´s save the world :)
