### ISSUE TITLE
v:uri.image and v:image do not use quality settings from install tool

### ISSUE THREAD

**Issue by maechler** [FluidTYPO3/vhs#1438]
Even though stating so in the description, the image related ViewHelpers do not respect the quality settings set in the install tool. This can easily be understood by looking at how the argument quality is used in the AbstractImageViewHelper:

https://github.com/FluidTYPO3/vhs/blob/development/Classes/ViewHelpers/Media/Image/AbstractImageViewHelper.php#L98-L103
https://github.com/FluidTYPO3/vhs/blob/development/Classes/ViewHelpers/Media/Image/AbstractImageViewHelper.php#L140
https://github.com/FluidTYPO3/vhs/blob/development/Classes/ViewHelpers/Media/Image/AbstractImageViewHelper.php#L169-L172

A simple fix would be to set the default value for this argument like this:

```php
$this->registerArgument(
    'quality',
    'integer',
    'Quality of the processed image. If blank/not present falls back to the default quality defined in ' . 'install tool.',
    false,
    $GLOBALS['TYPO3_CONF_VARS']['GFX']['jpg_quality']
);
```

Is there a special reason why this is not done? I would suggest to either add this or if not possible for some reason, change the argument description. If we can come up with a solution, I would be happy to create a pull request.

**Comment by Nemo64** [comment]
Typo3's image handling has a bug in which it will ignore the quality setting in the install tool if the source format wasn't a jpeg (I wasn't using vhs, just typoscript images). I haven't traced that one back though but I noticed one day that all my jpg's on a site had unreasonable quality. Always forcing the quality is the way to go. The default value method would probably be the best solution.
