### ISSUE TITLE
v:media.video preload doesn't work

### ISSUE THREAD

**Issue by Williwurstig** [FluidTYPO3/vhs#1443]
If you set the argument preload, the output is preload="preload".
`<v:media.video src="{image.originalFile.publicUrl}" preload="none"
                                                   width="1150" height="476"`
output: 
`<video width="1150" height="476" preload="preload"><source src="Headervideo_Farbauflo__sung_kl.mp4" type="video/mp4" /></video>`

VideoViewHelper.php Line 175:
`$tagAttributes['preload'] = 'preload'`
must be changed to:
`$tagAttributes['preload'] = $this->arguments['preload'];`

**Comment by neufeind** [comment]
For video that is already fixed. Duplicate of #1308.
Unresolved for audio.
