### ISSUE TITLE
Translated content rendered twice for sys_language_overlay = 1

### ISSUE THREAD

**Issue by rupasix** [FluidTYPO3/vhs#1444]
related: #1366 

We are trying to achieve behavior that non translated content elements should render anyway. I've set that attribute (https://docs.typo3.org/typo3cms/TyposcriptReference/Setup/Config/Index.html#sys-language-overlay): 
```
sys_language_overlay = 1
sys_language_mode = content_fallback
```
... and i'm getting all content elements twice. Is it possible that vhs resolves "hideNonTranslated" but not 1 for sys_language_overlay?

Edit: I forget to mention that this issue is connected with `<v:content.render column="0" />` used in fluidpages template. I switched my code to `<f:cObject typoscriptObjectPath="styles.content.get" />` and everything seems to work fine.

**Comment by NamelessCoder** [comment]
Please do try this on the `development` branch of VHS.

**Comment by rupasix** [comment]
It's working.
