### ISSUE TITLE
StringFrontend is deprecated

### ISSUE THREAD

**Issue by bmack** [FluidTYPO3/vhs#1455]
VHS is using the StringFrontend for caching. This has been deprecated in TYPO3 v9 in favor of using the VariableFrontend. Could you please update VHS to use VariableFrontend? Or are there any issues with VariableFrontend?

**Comment by NamelessCoder** [comment]
No issues that I can foresee, switching to VariableFrontend.

**Comment by NamelessCoder** [comment]
Fixed a good long while ago by switching to VariableFrontend - but forgot to close the issue. Thanks for reporting!
