### ISSUE TITLE
random.number is not really random (no CS[P]RNG)

### ISSUE THREAD

**Issue by DanielRuf** [FluidTYPO3/vhs#1462]
https://github.com/FluidTYPO3/vhs/blob/9f5166ea8df9f09f916a05f0294e3cc7781695f5/Classes/ViewHelpers/Random/NumberViewHelper.php#L88

We should use `random_int`.

**Comment by cedricziel** [comment]
Nice find - care to provide a quick patch?

**Comment by DanielRuf** [comment]
What is the PHP versions that should be supported at least?

I will provide a PR if I find the time.

**Comment by cedricziel** [comment]
Our composer manifest says we require 7, so it's fine.

**Comment by DanielRuf** [comment]
Will also change https://github.com/FluidTYPO3/vhs/blob/9f5166ea8df9f09f916a05f0294e3cc7781695f5/Classes/ViewHelpers/Random/StringViewHelper.php then as `rand` and `mt_rand` have no good seeding and `random_bytes` should be used.

**Comment by cedricziel** [comment]
Please go ahead! :)
