### ISSUE TITLE
Consider deactivating output encoding for some more ViewHelpers

### ISSUE THREAD

**Issue by JostBaron** [FluidTYPO3/vhs#1475]
Currently, the output of most ViewHelpers is escaped automatically by fluid. In some cases, this is not what is wanted most of the time.

Candidates (not complete, just top of my head!):
 * `v:format.trim` (I use it frequently to trim generated HTML)
 * `v:format.eliminate` (Whitespace removal between HTML tags)
 * `v:format.tidy` (The whole point is to output HTML)

**Comment by NamelessCoder** [comment]
I agree in the case of `v:format.tidy` but not the other ones. The cutoff point has to be with "ViewHelpers which are exclusively meant to generate or consume and then show XHTML" as the only type that is allowed to not escape by default. If a ViewHelper generates trusted HTML or escaping is in effect from children being rendered (for example, content record rendering) it's fine to not escape. But if the ViewHelper takes arbitrary strings and outputs arbitrary strings, we absolutely want it to escape by default.

Don't forget that Fluid is a lot more secure now than it was before, for this exact reason (escaping is now opt-out and will be done by default). If you remove this escaping, *security becomes opt-in in all those cases*. The common aspect of all those ViewHelpers that are risky, is that they take one or more variables which may contain XHTML from arbitrary sources and we have no way to distinguish between trusted and not trusted sources. Therefore, the default should be to not trust and instead require you to explicitly say you trust that variable, by using `f:format.raw`.

Alternatively but not recommended: if you've created a system that never needs to escape anything, `{escaping off}` can be put in the template file header to disable escaping across an entire template file - or you can remove the `EscapingInterceptor` in TYPO3 configuration to remove escaping completely and globally.

But we have to be very, very selective about these. We don't want it to be less secure to use a VHS ViewHelper around a variable than it would be to output the variable directly, unless there's a very good reason.
