### ISSUE TITLE
Migrate to Doctrine for v9 compatibility

### ISSUE THREAD

**Issue by pkerling** [FluidTYPO3/vhs#1477]
Hi,

the extension is marked compatible with TYPO3 v9, but it still uses `$GLOBALS['TYPO3_DB']`, so it will not work without the `typo3db_legacy` extension.

Might be on your roadmap already, but it would be cool to migrate to doctrine at some point.

**Comment by NamelessCoder** [comment]
100% agree about this one, @pkerling - and now would be the ideal time to do so, since we're about to drop TYPO3 7.6 compatibility.

**Comment by tantegerda1** [comment]
See #1491 and #1492

**Comment by glucka** [comment]
solved by #1492
