### ISSUE TITLE
Wrong dependency to typo3/cms instead to typo3/cms-core

### ISSUE THREAD

**Issue by lochmueller** [FluidTYPO3/vhs#1485]
The extension use "typo3/cms" as composer dependency, but extension should use "typo3/cms-core" so the developer have the choice which typo3 packages are used. If VHS require "typo3/cms" the complete TYPO3 have to be in the installation.

Regards,
Tim

**Comment by foobar13372** [comment]
Duplicate: https://github.com/FluidTYPO3/vhs/issues/1429
