### ISSUE TITLE
composer update not working

### ISSUE THREAD

**Issue by derghostface** [FluidTYPO3/vhs#1489]
I can not update the extension from 4.4.0 to 5.0.0 via composer when I use "fluidtypo3/vhs" as namespace, see error message below. When I use "typo3-ter/vhs" it works.

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - don't install fluidtypo3/vhs 5.0.0|don't install typo3/cms v8.7.16
    - don't install fluidtypo3/vhs 5.0.0|remove typo3/cms v8.7.16
    - Installation request for fluidtypo3/vhs 5.0.0 -> satisfiable by fluidtypo3/vhs[5.0.0].
    - Installation request for typo3/cms 8.7.16 -> satisfiable by typo3/cms[v8.7.16].
```

In the past I always used "fluidtypo3/vhs" as namespace, which worked.

**Comment by cedricziel** [comment]
I think we're missing the latest commit on development in a release.

@NamelessCoder care to tag 5.0.1?

**Comment by NamelessCoder** [comment]
New release coming in a moment.
