### ISSUE TITLE
v.iterator.sort does not work since v5 when using "subject"

### ISSUE THREAD

**Issue by foobar13372** [FluidTYPO3/vhs#1490]
This works:
`{objectStorage -> v:iterator.sort(sortBy: 'sorting')}`

This does not anymore:
`{v:iterator.sort(subject: objectStorage, sortBy: 'sorting')}`

I assume the error in Classes/ViewHelpers/Iterator/SortViewHelper.php:116:
`$subject = static::arrayFromArrayOrTraversableOrCSVStatic(!empty($arguments['as']) ? $arguments['subject'] : $renderChildrenClosure());`

The empty check should check for `subject`, not for `as`, isn't it?

**Comment by NamelessCoder** [comment]
It needs the same check as https://github.com/FluidTYPO3/vhs/blob/development/Classes/ViewHelpers/Iterator/RandomViewHelper.php#L62 - and I think there may be one or two other cases as well.

**Comment by NamelessCoder** [comment]
Solved by making the sort ViewHelper content-argument based like the other iterator ViewHelpers. Thanks for reporting this so quickly! A new release is coming right up.
