### ISSUE TITLE
The type attribute is unnecessary for JavaScript resources.

### ISSUE THREAD

**Issue by Gitsko** [FluidTYPO3/vhs#1493]
Hi,

the validator.w3.org say the type attribute is unnecessary for js ans css. Please remove them.

> Warning:  The type attribute is unnecessary for JavaScript resources

**Comment by NamelessCoder** [comment]
Will not be removed; serves a purpose with integrations like OneTrust (cookie opt-in) which among other ways, works by setting the `type` property of scripts which may set cookies, to `text/plain` until cookies are accepted.
