### ISSUE TITLE
v:content.resources.fal returns empty array in preview section

### ISSUE THREAD

**Issue by kimchristiansen** [FluidTYPO3/vhs#1500]
After updating to flux 9.0.0, fluidpages 4.2.0 and vhs 5.0.1, the v:content.resources.fal returns an empty array in the preview section. In the Main section (frontend) everything works fine.

```HTML
<f:section name="Configuration">
  <flux:form id="imageteaser" label="ImageTeaser" >
    <flux:field.inline.fal name="settings.falimage" label="Teaser Image" multiple="0" maxItems="1" 
  </flux:form>
</f:section>

<f:section name="Preview">
  <f:if condition="{settings.falimage}">
    {v:content.resources.fal(field: 'settings.falimage') -> v:iterator.first() -> v:variable.set(name: 'image')}
    <f:if condition="{image}">
      <f:image src="{image.id}" alt="{image.alternative}" treatIdAsReference="1"  width="200"/>
    </f:if>
  </f:if>
</f:section>

<f:section name="Main">
  <f:if condition="{settings.falimage}">
    {v:content.resources.fal(field: 'settings.falimage') -> v:iterator.first() -> v:variable.set(name: 'image')}
      <f:if condition="{image}">
          <f:image class="LazyLoadImage-previewImage js-lazyloadimage-small" treatIdAsReference="1" src="{image.id}" alt="{image.alternative}" width="76" height="43c"/>
      </f:if>
  </f:if>
</f:section>
```

**Comment by dahaupt** [comment]
Something definitively has changed here, I also ran into this behavior yesterday. 

The fix or workaround is pretty easy as inserting `record="{record}"` or `uid={record.uid}` will return the correct array again. For some reason the standard snippet you can find in the documentation doesn't work in the backend anymore. Unfortunately I had no time to debug this.

**Comment by yesjoar** [comment]
Got the same error. `record="{record}"` works only for me when there is just one image. So the following code doesn't work.

```
<f:for each="{v:content.resources.fal(record: '{record}')}" as="image">
	<f:image treatIdAsReference="1" src="{image.uid}" />
</f:for>
```

**Comment by NamelessCoder** [comment]
`<f:if condition="settings.falimage">` will always be true. I think you meant `<f:if condition="{settings.falimage}">`.

**Comment by NamelessCoder** [comment]
And I think @chriskrj nailed it - you probably need to pass the record explicitly in this case.

**Comment by kimchristiansen** [comment]
@NamelessCoder You're right. I have edited the example above.

**Comment by intertain** [comment]
Today I have still an error by using exactly the code above in preview section of a content element. "Call to a member function exec_SELECTgetRows() on null" error happens in T3 9.5.1 in preview mode. Any idea?

**Comment by intertain** [comment]
problem ist solved with https://github.com/FluidTYPO3/vhs/commit/c160676c3663643b28780c5fe01fda0dcc9a2a6c .

**Comment by RKlingler** [comment]
I'm having the same problem.
Since I'm rendering my images in a partial, adding the record is not a great solution in my case though. 

Here is a simplified example.

Preview section:
```html
<f:render partial="PartialName" arguments="{images: 'imagesField'}"/>
```

Partial:
```html
{namespace v=FluidTYPO3\Vhs\ViewHelpers}

<f:for each="{v:content.resources.fal(field: images)}" as="img">
	<f:image treatIdAsReference="1" src="{img.id}" />
</f:for>
```

I'm using flux 9.1.0 and vhs 5.1.1. The error occured after updating from older versions.

**Comment by NamelessCoder** [comment]
Closing the issue - make sure you pass `record` to the ViewHelper when using it in BE context, as there is no way VHS can assume which record is being rendered.
