### ISSUE TITLE
 LanguageMenuViewHelper still selects records from pages_language_overlay table

### ISSUE THREAD

**Issue by jgrp** [FluidTYPO3/vhs#1504]
Hello, 
I am trying to use the `<v:page.languageMenu>` in TYPO3 v9 and receive this error: 

```
There is no entry in the $TCA array for the table "pages_language_overlay". This means that the function enableFields() is called with an invalid table name as argument
```

I've noticed, that the table `pages_language_overlay` is still in use. 
https://github.com/FluidTYPO3/vhs/blob/development/Classes/ViewHelpers/Page/LanguageMenuViewHelper.php#L317

I guess that must be changed for compatibility to v9.

**Comment by foobar13372** [comment]
What is the status here? We are totally stuck in a large project because of this...

**Comment by pmuelhaupt** [comment]
Changing $tablename to 'pages' should do the trick
