### ISSUE TITLE
math.sum throws exception when a is array, b is null (not set) and fail is 1

### ISSUE THREAD

**Issue by timri** [FluidTYPO3/vhs#1505]
In my template I have:
`{v:math.sum(a: { 0:some,
                                                            1:different,
                                                            2:fields,
                                                            3:and,
                                                            4:variables}, fail: 1)}`
According to the documentation https://fluidtypo3.org/viewhelpers/vhs/master/Math/SumViewHelper.html, this should sum up the fields:
> If $a is an array and $b is not provided then array_sum is used to return a single numeric value.

and
> fail: If TRUE, throws an Exception if argument "a" is not specified

(a is specified, b is missing)

Changing that to "fail: 0" works, however a missing $a would go undetected.

I would guess that line 47-49 https://github.com/FluidTYPO3/vhs/blob/ab4a37cc272db659f08bfe44030a4ccb94956746/Classes/ViewHelpers/Math/SumViewHelper.php#L47-L49 should be moved after  https://github.com/FluidTYPO3/vhs/blob/ab4a37cc272db659f08bfe44030a4ccb94956746/Classes/ViewHelpers/Math/SumViewHelper.php#L50  and changed to:
```php
        if (!$aIsIterable && $b === null && (boolean) $arguments['fail']) {
            ErrorUtility::throwViewHelperException('Required argument "b" was not supplied', 1237823699);
        }
```

**Comment by NamelessCoder** [comment]
Hi @timri - the fix sounds like the exact right solution. Would you mind creating a pull request that changes that? I'm sure there are also other ViewHelpers that need the same thing done.

**Comment by neufeind** [comment]
Suggested PR unifies the handling so we have the "guard-clause" first.
