### ISSUE TITLE
Assets rendered twice

### ISSUE THREAD

**Issue by rafu1987** [FluidTYPO3/vhs#1507]
I'm experiencing that assets (css and js both) are rendered twice with the same content, but slightly different timestamps. It's kind of random, but it's happening on a reload of page with cache. If I reload without cache, the assets are only rendered once. And I think it has to do with uncachable plugins on the page as well (i.e. indexed_search plugin search results / search form is working fine).

Also, when I deactivate realurl rewriting for indexed_search it works. Strange...

Any ideas?

TYPO3 8.7.x
PHP 7.2.x
vhs 5.0.1

**Comment by rafu1987** [comment]
Okay, I had to set `/tx_solr|tx_indexed_search|(?:^|\?|&)q=/` acording to realurl documentation here: https://github.com/dmitryd/typo3-realurl/wiki/Configuration-reference#cache-section

**Comment by rafu1987** [comment]
I again have the problem of assets rendered twice. 
I'm setting some GET params for powermail to prefill a form field and assets (css and js) are rendered twice. Even with the realurl setting, they are rendered twice. This is a major problem, because of JavaScript errors, etc.

Any suggestions?

**Comment by rafu1987** [comment]
Okay, after further investigation it has something to do with cHash. When I add useCacheHash=1 to my link to the powermail form, the error is gone. 

The same happens, when I add this parameter i.e. to the Install Tool setting `cHashExcludedParameters`: `tx_powermail_pi1[field][name]`

**Comment by NamelessCoder** [comment]
I'm going to risk it and say: solved by https://github.com/FluidTYPO3/vhs/commit/4c49ee36d9c3b74f44f3a815a014f933b45ae242 :)
