### ISSUE TITLE
problems with v:render.uncache

### ISSUE THREAD

**Issue by gbartolucci** [FluidTYPO3/vhs#1510]
Hello,
I'm trying to use the uncached partial  <v:render.uncache partial="home_header_img" arguments="{_all}" /> but I've this exception: 

#1225709595: The Fluid template files "" could not be loaded. (More information)
TYPO3Fluid\Fluid\View\Exception\InvalidTemplateResourceException thrown in file
/dati/htdocs/typo3/typo3-8.7/typo3_src-8.7.10/vendor/typo3fluid/fluid/src/View/TemplatePaths.php in line 722.

15 TYPO3Fluid\Fluid\View\TemplatePaths::resolveFileInPaths(array, "Home_header_img")
/dati/htdocs/typo3/typo3-8.7/typo3_src-8.7.10/vendor/typo3fluid/fluid/src/View/TemplatePaths.php:
00689:             $paths = $this->getPartialRootPaths();
00690:             $partialName = ucfirst($partialName);
00691:             self::$resolvedFiles[self::NAME_PARTIALS][$partialKey] = $this->resolveFileInPaths($paths, $partialName);
00692:         }
00693:         return self::$resolvedFiles[self::NAME_PARTIALS][$partialKey];
......

With XDebug I've these values:
- $partialKey: home_header_img.html
- $paths: Array[0]
- $partialName: Home_header_img 

So the problem is $paths that has an empty array

I've no problems with cached partial <f:render partial="home_header_img" arguments="{_all}" />

PHP: PHP 7.0.30
Typo3: 8.7.10
VHS: 5.0.1

**Comment by NamelessCoder** [comment]
Hi @gbartolucci - can you paste how you defined your template paths, and where (in an Extbase controller, in FSC, custom FLUIDTEMPLATE or other) you are using the ViewHelper?

Hints: The ViewHelper depends on an extension context and will render partials from that specific extension. The paths it will read from base template paths of that extension. The error you're getting looks like a missing extension context.

**Comment by gbartolucci** [comment]
I'm not very expert about typo script. I have a typo script template with this setup and it is is included in my root template:

lib.contentElement {
  layoutRootPaths {
     200 = templates/fluid_styled_content/Resources/Private/Layouts/
   }
   templateRootPaths {
      200 = templates/fluid_styled_content/Resources/Private/Templates/
   }
   partialRootPaths {
      200 = templates/fluid_styled_content/Resources/Private/Partials/
   }
}

page = PAGE
page.typeNum = 0
page.10 = FLUIDTEMPLATE
page.10 {
    format = html
    file = templates/my-design/Layouts/Main_layout.html
    partialRootPath = templates/my-design/Partials/
    layoutRootPath = templates/my-design/Layouts/
    variables {
        content_main < styles.content.get
        content_main.select.where = colPos = 0
        content_column_1 < styles.content.get
        content_column_1.select.where = colPos = 1
        content_column_2 < styles.content.get
        content_column_2.select.where = colPos = 2
     }
}

**Comment by BWdevelop01** [comment]
naja vergiss einfach

**Comment by gbartolucci** [comment]
Hello,
  sorry, but I don't understand your reply. The problem persists but, because it was an important feature, I had to use a plugin to implement it.

**Comment by NamelessCoder** [comment]
Solved by https://github.com/FluidTYPO3/vhs/commit/530649c52bc5629ecae7a22b428c7c09a17a3769
