### ISSUE TITLE
SourceSetViewHelperTrait encodes image URI twice

### ISSUE THREAD

**Issue by luzat** [FluidTYPO3/vhs#1512]
When using images containing umlauts (e.g. `zubehör.jpg`) with `v:media.image` and `srcset` the `src` is set correctly, but in `srcset` the file name is double-encoded, that is `ö` => `%C3%B6` => `%25C3%25B6`. It seems that this happens because of this line in SourceSetViewHelperTrait.php:

    $srcsetVariantSrc = static::preprocessSourceUri(GeneralUtility::rawUrlEncodeFP($srcsetVariantSrc), $this->arguments);

`static::preprocessSourceUri` encodes the string as does `GeneralUtility::rawUrlEncodeFP`. Just changing the line to

    $srcsetVariantSrc = static::preprocessSourceUri($srcsetVariantSrc, $this->arguments);

gets rid of a deprecated call and outputs both `src` and `srcset` correctly with `%C3%B6`.

**Comment by NamelessCoder** [comment]
Removed in https://github.com/FluidTYPO3/vhs/commit/9af62c4c73330e99393729cbf3d873a4307ed92c

**Comment by luzat** [comment]
`GeneralUtility::rawUrlEncodeFP` is removed, but the encoding is still superfluous (and breaks image references where double encoding breaks the URI).
