### ISSUE TITLE
Side-Effect related to Commit c160676c3663643b28780c5fe01fda0dcc9a2a6c

### ISSUE THREAD

**Issue by tobiasgraeber** [FluidTYPO3/vhs#1524]
Hi,

by adding Commit c160676c3663643b28780c5fe01fda0dcc9a2a6c 
you changed the method "getRecord()" in file \vhs\Classes\ViewHelpers\Resource\Record\AbstractRecordResourceViewHelper.php

After this change the query uses the query builder which uses "getRestrictions" 

If you change the page visibility in typo3 backend as an editor to "disabled" there is now a fatal error (in the frontend) if you view the (still disabled) page in "preview" mode (from backend) ...it hink this is cause the (by default!) set restrictions when using the query builder are NOT removed (as they need to?) see:

(see: https://docs.typo3.org/typo3cms/CoreApiReference/8.7/ApiOverview/Database/RestrictionBuilder/Index.html#examples)

**Comment by NamelessCoder** [comment]
Hi Tobias - you are right, QueryBuilder will enforce restrictions by default, yet we need to remove the `hidden` restriction from the queries when TSFE is in preview mode (which is then set as a flag in `$GLOBALS['TSFE']` which means the check has to also check if that object exists to prevent problems in BE).

Do you want to prepare a pull request for this? Sounds like you know exactly how and where we need to get these hidden records included ;)

**Comment by tobiasgraeber** [comment]
Hi, thanks for copy. I wish i could provide a pull request, but at the moment i dont have time to provide a pull request, sorry. 

Just got into this and tried to hunt it down to the source ;-). 

Please be so kind and provide a fix as soon as possible, now that you are aware of this.

**Comment by glucka** [comment]
Solved by #1525
