### ISSUE TITLE
v:iterator.explode tag-usage throws error. (5.1.0)

### ISSUE THREAD

**Issue by TheNaderio** [FluidTYPO3/vhs#1527]
Im doing an upgrade to TYPO 9.5 and updated Flux and vhs too.
Now all templates that uses `iterator.explode` with tags explodes :D 
* TYPO3 9.5
* vhs 5.1.0
* Flux 9.1.0

This:
```
<v:iterator.explode content="1,2,3,4,5" glue="," as="record">
    <f:for each="{record}" as="rec">
        {rec}<br>
    </f:for>
</v:iterator.explode>
```
Causes this error in backend (Flux preview section) and frontend:
`Call to undefined method TYPO3\CMS\Fluid\Core\Rendering\RenderingContext::getTemplateVariableContainer()`

I solved it in my case by using `v:variable.set` and write the array to a variable:
`{v:variable.set(name: 'record', value:'{v:iterator.explode(content: '1,2,3,4,5', glue: \',\')}')}`

This works perfect for me - but I think tag-usage should still be possible?

**Comment by jdreesen** [comment]
See #1522

**Comment by TheNaderio** [comment]
Thank you @jdreesen - missed that issue :)
