### ISSUE TITLE
v:variable.set fails inside partials nested inside partials

### ISSUE THREAD

**Issue by DonGissel** [FluidTYPO3/vhs#1538]
Using TYPO3 9.5.1 and the bugfixes for `getVariableProvider()` from PR1530, I can't seem to set variables if I try from a partial that's rendered from within another partial. Observe:

`<v:variable.set name="imgUri" value="{f:uri.image(width: width, height: height, src: '{f:uri.resource(path:\'img/myFile.png\')}')}" />`

This works fine when done from within a "first-level" partial (the "chain" is `Layout` -> `Partial`). But if that partial instead uses `<f:render>` to render _another_ partial (the "chain" becomes `Layout` -> `Partial` -> `Partial`) and I move `<v:variable.set>` in _there_, I just get the dreaded `Oops, an error occurred!`

I don't know if this is a bug in TYPO3 or VHS, but since the error since to be tied to code by you guys, I'm filing it here. ;-)

**Comment by DonGissel** [comment]
The plot thickens: my TYPO3 has a "sites" profile with an entry point that matches my domain name (funny enough). If I change that, so the entry point is different from my actual domain name (say `derp.domain.com` for a site actually running on `www.domain.com`), or if I delete the site profile entirely, it works fine.

**Comment by DonGissel** [comment]
Okay. Okay, okay okay. It actually DOES sort of work. But the set variable can **only** be accessed using `{v:variable.get(name: 'imgUri')}`, and not `{imgUri}` inside the partial.

I'm not sure this is a bug at this point, or just me being rusty at this. Feel free to kill the issue at your discretion.

**Comment by DonGissel** [comment]
God damnit. The issue is something completely different. Forget I was ever here.

**Comment by NamelessCoder** [comment]
Although I didn't see anything and nobody was here, if someone were to have problems with f:uri.image in some circumstances v:resource.image can help! https://viewhelpers.fluidtypo3.org/fluidtypo3/vhs/5.0.1/Resource/Image.html

**Comment by DonGissel** [comment]
Actually, `f:uri.image` worked just fine. The problem is that it returned a path beginning with a slash (because I have a site configuration), and that in turn broke `v:media.image.width()`. Now you know, and knowing is half the battle. Why would they want the duke's son killed?
