### ISSUE TITLE
New release needed for TYPO3 9 compatibility

### ISSUE THREAD

**Issue by taalas** [FluidTYPO3/vhs#1541]
Hi,

currently the package states compatibility with TYPO3 9 but certain parts aren't in the latest release (e.g. AbstractRecordResourceViewHelper.php had deprecated calls to $GLOBALS['TYPO3_DB']).

As this is fixed now is there any chance for a new release version?

**Comment by NamelessCoder** [comment]
VHS updated to 9.x compatibility a while ago.
