### ISSUE TITLE
UncacheViewHelper: getTemplateVariableContainer removed in Typo3 9.0

### ISSUE THREAD

**Issue by jumpinP** [FluidTYPO3/vhs#1543]
I am using vhs release 5.1.0 and Typo3 9.5.1, I think I found a bug:
Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to undefined method TYPO3\CMS\Fluid\Core\Rendering\RenderingContext::getTemplateVariableContainer() | Error thrown in file
.../vhs/Classes/ViewHelpers/Render/UncacheViewHelper.php in line 57

Searching the code for getTemplateVariableContainer() in an old typo3-version I found:
```
     * Get the template variable container (DEPRECATED; use getVariableProvider instead)
     *     
     * @deprecated since TYPO3 CMS 8, will be removed in TYPO3 CMS 9 - use getVariableProvider instead
     * @see getVariableProvider
     * @return \TYPO3\CMS\Fluid\Core\ViewHelper\TemplateVariableContainer The Template Variable Container
```

**Comment by jdreesen** [comment]
Should already be fixed by #1530 but there's no release including this fix, yet.

**Comment by LukasVice** [comment]
Same problem. Could you please release the new version to fix this?

**Comment by Zillion01** [comment]
+1

**Comment by OliverRWeiss** [comment]
Same problem.

**Comment by typo3ua** [comment]
I use TYPO3 9.5.3 and PHP 7.2.6

I have the same problems with `v:render.uncache`

**Comment by NamelessCoder** [comment]
Fixed in most recent release.
