### ISSUE TITLE
Broken v:resource.record ViewHelper in VHS 5.1.0 and TYPO3 9.5.1 LTS

### ISSUE THREAD

**Issue by eckonator** [FluidTYPO3/vhs#1545]
Hi, i use the v:resource.record ViewHelper in same way i used it in TYPO3 8.7 and VHS 5.0.1. But the ViewHelper v:resource.record thorws an error:

Oops, an error occurred!
Call to a member function quoteStr() on null

My FluidTemplate looks like this:
{v:resource.record(table: 'tx_myext_domain_model_myexticons', uid: '{data_item.tx_mask_icon}', field: 'myexticon')}

Hope someone can help?

**Comment by skdmind** [comment]
The $GLOBALS['TYPO3_DB'] Database Connection got deprecated in TYPO3 8 and removed in TYPO3 9.  
Deprecation Log Entry: https://docs.typo3.org/typo3cms/extensions/core/Changelog/8.5/Deprecation-78244-DeprecateTYPO3_DBAndPreparedStatementClass.html

I created a patch for the AbstractRecordResourceViewHelper and the FalViewHelper(will create a Pull Request later with all $GLOBALS['TYPO3_DB'] occurrences), so in case it's urgent it would be one option until an official updates comes out:


[patches.zip](https://github.com/FluidTYPO3/vhs/files/2576087/patches.zip)

**Comment by jdreesen** [comment]
Sounds like this was already fixed by #1519 (which wasn't released yet).

**Comment by eckonator** [comment]
Yes, i switched to the current development branch - this solved the problem for me so far. Thanks!
