### ISSUE TITLE
On clear cache vhs-asset files will not deleted

### ISSUE THREAD

**Issue by beardcoder** [FluidTYPO3/vhs#1546]
If you use the system clear cache mechanism the timestamp of all vhs-assets* files will be set to 0 and the fille will not be deleted.

<img width="543" alt="bildschirmfoto 2018-11-13 um 10 24 39" src="https://user-images.githubusercontent.com/9371658/48403559-6c857e80-e72e-11e8-88d3-ae7cb9c35d00.png">

**Comment by NamelessCoder** [comment]
This is by design - see https://github.com/FluidTYPO3/vhs/issues/1509 for more details.
