### ISSUE TITLE
Call to a member function getUriBuilder() on null

### ISSUE THREAD

**Issue by golserma** [FluidTYPO3/vhs#1548]
I'm migrating my site from 8.x.x to 9.5.1 and I get this error message if I try to load the frontend.
I asked on slack and they suggested filling a bug on VHS.

VHS from git commit 613d7da259bcb3f407c7702d834ed02ac4ceda33
exception backtrace: [Upgrade_problem_.txt](https://github.com/FluidTYPO3/vhs/files/2603668/Upgrade_problem_.txt)

**Comment by NamelessCoder** [comment]
Solved by https://github.com/FluidTYPO3/vhs/commit/5b4dafd6bd9e0966ce7f0ca55e3d69f54b0e7a08
