### ISSUE TITLE
GeneralUtility::rawUrlEncodeFP is deprecated and was removed in V9

### ISSUE THREAD

**Issue by Forestsoft-de** [FluidTYPO3/vhs#1549]
See: https://api.typo3.org/typo3cms/current/html/class_t_y_p_o3_1_1_c_m_s_1_1_core_1_1_utility_1_1_general_utility.html#aa328760fafaf2d2d5414f1fc96b6293d

https://github.com/FluidTYPO3/vhs/blob/613d7da259bcb3f407c7702d834ed02ac4ceda33/Classes/Traits/SourceSetViewHelperTrait.php#L52

**Comment by luzat** [comment]
This specific usage could probably be removed as already noted in #1512.

**Comment by NamelessCoder** [comment]
Solved by https://github.com/FluidTYPO3/vhs/commit/9af62c4c73330e99393729cbf3d873a4307ed92c
