### ISSUE TITLE
MimetypeViewHelper: Wrong return value

### ISSUE THREAD

**Issue by devtroll** [FluidTYPO3/vhs#1554]
The view helper "MimetypeViewHelper" returns the wrong return value. Instead of the "mimetype" only the "type" is returned.

TYPO3: 8.7.20 Composer
VHS: 5.1.0

File:  Classes/ViewHelpers/Media/Image/MimetypeViewHelper.php
Line: 23
`return true === isset($info['type']) ? $info['type'] : '';`

should be

`return true === isset($info['mimetype']) ? $info['mimetype'] : '';`

Greetings from Germany.

**Comment by neufeind** [comment]
But info comes from AbstractImageInfoViewHelper::getInfo() and that returns: width, height, type (the latter which comes from $imageSize['mime']. Hmm?

**Comment by NamelessCoder** [comment]
Hi @devtroll,

Pretty sure it returns the mime type, as the name indicates. [There's even a test for it](https://github.com/FluidTYPO3/vhs/blob/development/Tests/Unit/ViewHelpers/Media/Image/MimetypeViewHelperTest.php#L47).

**Comment by NamelessCoder** [comment]
Closing issue, the correct mime type is indeed returned. See test case linked above.
