### ISSUE TITLE
CanonicalViewHelper controllerContext is null

### ISSUE THREAD

**Issue by tgriessbach** [FluidTYPO3/vhs#1555]
TYPO3: 9.5.3
VHS: 5.1.0

When I insert `<v:page.header.canonical />` into a Template I get this error:

`Call to a member function getUriBuilder() on null`
in CanonicalViewHelper.php line 72:
`$uriBuilder = $this->controllerContext->getUriBuilder();`

other Viewhelpers use:
`$uriBuilder = $this->renderingContext->getControllerContext()->getUriBuilder();`

**Comment by Abdul-Hafiz** [comment]
I have tried solution from this https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.0/Breaking-82414-RemoveCMSBaseViewHelperClasses.html 

I have replaced $this->controllerContext with $this->renderingContext->getControllerContext() in file vhs/Classes/ViewHelpers/Page/Header/AlternateViewHelper.php 

VHS Version : 5.1.1
TYPO3 Version : 9.5.4
