### ISSUE TITLE
LanguageMenuViewHelper is still broken in TYPO3 9.5

### ISSUE THREAD

**Issue by dmitryd** [FluidTYPO3/vhs#1556]
Fetching of page language overlays is still not working right with TYPO3 9.5 because it uses wrong conditions to fetch translations. The PR provides a method that works in all TYPO3 versions.

**Comment by pkerling** [comment]
Fix works for me (on 9.5)

**Comment by NamelessCoder** [comment]
Merged in https://github.com/FluidTYPO3/vhs/pull/1523

**Comment by kvonspiczak** [comment]
is that fix available for version 8.x as well?

**Comment by dmitryd** [comment]
@kvonspiczak It is not needed for v8
