### ISSUE TITLE
FalViewHelper error in draft workspace since upgrade to version 5.1.1

### ISSUE THREAD

**Issue by responseinformationsdesign** [FluidTYPO3/vhs#1561]
Since update to version 5.1.1 I get the following error in the page preview in draft workspace - but only for new pages:

Argument 3 passed to TYPO3\CMS\Frontend\Page\PageRepository::getFileReferences() must be of the type array, boolean given, called in ...\typo3conf\ext\vhs\Classes\ViewHelpers\Resource\Record\FalViewHelper.php on line 111

Version 5.1.0 works flawlessly.

**Comment by dogawaf** [comment]
Related to #1524, introduced by #1525

**Comment by dogawaf** [comment]
Fixing the issue would be to handle properly the fetching of hidden records in preview mode (`TSFE->fePreview === 1`, already done by #1525), and hidden/non-yet-existing records in workspace preview mode (`TSFE->fePreview === 2`).

But, as it seems a pretty easy fix, maybe also a `false` returned by `\FluidTYPO3\Vhs\ViewHelpers\Resource\Record\AbstractRecordResourceViewHelper::getRecord()` should be properly handled.
