### ISSUE TITLE
FalViewHelper error since 5.1.1

### ISSUE THREAD

**Issue by darthnorman** [FluidTYPO3/vhs#1562]
When using 
`{v:resource.record.fal(table: 'tt_news', field: 'tx_mktools_fal_images', uid: news.uid)}`
an exception occurs: 

> UID of related record has to be an integer. UID given: ""

It does work with 5.1.0, seems to me that in [this commit](https://github.com/FluidTYPO3/vhs/commit/c160676c3663643b28780c5fe01fda0dcc9a2a6c#diff-483bb1e8b46b9340f483e0bc253bab7a ) something went wrong.

**Comment by naturefund-falk** [comment]
This is caused by the changes to getRecord function in AbstractRecordResourceViewHelper.
