### ISSUE TITLE
IsLanguageViewHelper is not compatible with typo3fluid/fluid 2.6.0

### ISSUE THREAD

**Issue by robert-heinig** [FluidTYPO3/vhs#1564]
The argument "condition" is no longer defined due to the fluid change
https://github.com/TYPO3/Fluid/commit/a67b31f9e6ecb015d0f47892fce46cf64110fd15#diff-382423d364dfe7dd9c28f8b390992b62
which removed this argument.
The vhs docs state it is still supported:
https://fluidtypo3.org/viewhelpers/vhs/master/Condition/Page/IsLanguageViewHelper.html

**Comment by NamelessCoder** [comment]
ViewHelper itself is compatible, even if argument was present it would be ignored. Not sure if ViewHelper docs will be regenerated retroactively - but in any case, proper use of the ViewHelper would never involve using this argument.
