### ISSUE TITLE
 Call to undefined method TYPO3\CMS\Core\Utility\GeneralUtility::rawUrlEncodeFP() 

### ISSUE THREAD

**Issue by t3Golden** [FluidTYPO3/vhs#1570]
Example image render 

`<v:media.image
        maxW="{data.imagewidth}"
        treatIdAsReference="1"
        title="{file.title}"
        alt="{file.alternative}"
        src="{file}"
        class="img-responsive"
        srcset="{320,480,768,992,1200}"
        srcsetDefault="698"
        additionalAttributes="{sizes: '(max-width: 992px) 50vw, 100vw'}"

/>`

Error  Call to undefined method TYPO3\CMS\Core\Utility\GeneralUtility::rawUrlEncodeFP() 
Typo3  version : 9.5.4
Vhs version :5.1.1

**Comment by MisterMarlu** [comment]
TYPO3 removed this method in version 9.

File: typo3/sysext/core/Classes/Utility/GeneralUtility.php in Typo3 version 8
```php
    /**
     * rawurlencode which preserves "/" chars
     * Useful when file paths should keep the "/" chars, but have all other special chars encoded.
     *
     * @param string $str Input string
     * @return string Output string
     * @deprecated since TYPO3 v8, will be removed in TYPO3 v9, use the PHP methods directly instead
     */
    public static function rawUrlEncodeFP($str)
    {
        static::logDeprecatedFunction();
        return str_replace('%2F', '/', rawurlencode($str));
    }
```

vhs didn't replaced it.

File: Classes/Traits/SourceSetViewHelperTrait.php in vhs version 5.1.1 (and 5.2.0 too)

```php
public function addSourceSet($tag, $src)
    {
        // ...

            $srcsetVariantSrc = rawurldecode($srcsetVariant[3]);
            $srcsetVariantSrc = static::preprocessSourceUri(GeneralUtility::rawUrlEncodeFP($srcsetVariantSrc), $this->arguments);

        // ...
    }
```

**Comment by NamelessCoder** [comment]
@davdenic Because the method call no longer exists, as per commit https://github.com/FluidTYPO3/vhs/commit/9af62c4c73330e99393729cbf3d873a4307ed92c which closed the issue via annotation. I'm also not sure which PR you are referring to that isn't closed - it doesn't appear to be linked to this issue.

**Comment by davdenic** [comment]
@NamelessCoder sorry, i got confused, now i don't see this error anymore but i see a different one 

Error
Call to undefined method TYPO3\CMS\Core\Utility\GeneralUtility::rawUrlEncode()

in /var/www/html/web/typo3conf/ext/vhs/Classes/Traits/SourceSetViewHelperTrait.php line 52

sorry again. should i open a different bug?
thanks

**Comment by NamelessCoder** [comment]
@davdenic It is solved and merged (there are no more calls to the mentioned method at all in VHS) but not yet released. Until the next release is made you can use the `dev-development` branch. No need for another issue :)

**Comment by davdenic** [comment]
Hi @NamelessCoder do you know if the new release will happen soon? 
I'd like to not use dev-development in production if it's possible. thanks 😊

**Comment by NamelessCoder** [comment]
@davdenic Today! ;)
