### ISSUE TITLE
VHS Bootstrap-Navbar

### ISSUE THREAD

**Issue by orhan-v** [FluidTYPO3/vhs#1576]
I have a problem with TYPO3 VHS. I want to declare a navbar within my own extension which I created with builder-extension. It works perfectly, when I look on the source code of my page, everything is like my own html code. But when I click on the mother-page of my subpages nothing happens. 
Like: ![3](https://user-images.githubusercontent.com/25508369/54707503-8ce0a200-4b41-11e9-8001-71c176a186e8.png)
I think I have the wrong TYPO3 settings, because the mother-page also has an href. On my example HTML Code what I created at the beginning, all pages had href="#".

My HTML Code for The Navbar: https://pastebin.com/6j6iPbsA?fbclid=IwAR1QgK2AQKB9VjHWqebZa_TBbi2Gh0JZL9a2clYky6_y9rTe1_ZJ3_dTL5Q This is how the sourcecode from my Page looks: https://pastebin.com/NgG0T0m9?fbclid=IwAR2f6TMuI6Q4tOPHPHw8FFv2Zs827vt9HN2_UI4V1KhHbfLYMQ1DD6zmBjM

And these two images show how the PHPStorm and the Pagetree looks:
![1](https://user-images.githubusercontent.com/25508369/54707500-8a7e4800-4b41-11e9-9307-56c85f565c1c.png)
![2](https://user-images.githubusercontent.com/25508369/54707502-8ce0a200-4b41-11e9-8d08-f498efa91107.png)

**Comment by rupasix** [comment]
You have issue with your frontend so it's not connected with vhs. You should looking for help somewhere else, stackoverflow maybe :)

Anyway, you can check two things:
- JS error blocking bootstrap dropdown to work propertly - then you don't have event for .dropdown-toggle and after click page should reload to "index.php?id=3".
- everything actually works fine but you have overflow:hidden for parent nodes so your dropdown list is cutted

**Comment by orhan-v** [comment]
I thought maybe it looks correct nevertheless its wrong. But i think you re right. I am sorry, should I delete this Issue?

**Comment by NamelessCoder** [comment]
@orhan-v The problem you have does not appear to be related to VHS, @rupasix's suggestion to ask on StackOverflow is good ;)

Hope you find a solution!
