### ISSUE TITLE
v:asset.script duplicates and renders first instance only

### ISSUE THREAD

**Issue by Scopestyle** [FluidTYPO3/vhs#1586]
Using `v:asses.script` on 2 modules (using DCE, in TYPO3 9) VHS sees there are 2 instances, and compiles the code accordingly. Only it renders the first instance twice.

**Code example:**

```	
<v:asset.script name="inlinejs{contentObject.uid}">
	$(document).ready(function () <f:format.raw>{</f:format.raw>
		$('#accordion{contentObject.uid}').accordion(<f:format.raw>{</f:format.raw>
			collapsible: true, 
			heightStyle: 'content',
			active: {field.active}
		<f:format.raw>}</f:format.raw>);
	<f:format.raw>}</f:format.raw>);
</v:asset.script>
```

**Rendered Filename:**

`/typo3temp/assets/vhs-assets-inlinejs90-inlinejs94.js?1560930251`

**Output:**
```	
$(document).ready(function () {
	$('#accordion90').accordion({
		collapsible: true, 
		heightStyle: 'content',
		active: 0
	});
});

$(document).ready(function () {
	$('#accordion90').accordion({
		collapsible: true, 
		heightStyle: 'content',
		active: 0
	});
});
```

Because the ID is the same, the output is broken.

**Comment by GuidoJansen** [comment]
What is your issue here? Do you want two different scripts? Or do you want only one script?

**Comment by Scopestyle** [comment]
Yeah there should be 2 different scripts, with 2 different IDs. In the output above however, the same script gets rendered twice.

**Comment by NamelessCoder** [comment]
@Scopestyle please check if https://github.com/FluidTYPO3/vhs/pull/1516 solves your issue!

**Comment by NamelessCoder** [comment]
Closing due to lack of feedback; assuming that #1516 solved this issue.
