### ISSUE TITLE
format.substring does not support a negative length

### ISSUE THREAD

**Issue by naturefund-falk** [FluidTYPO3/vhs#1587]
This one is related to #1350 because the now used mb_substr does not support a negative length as the old substr function does.

**Comment by NamelessCoder** [comment]
>  mb_substr does not support a negative length

I think this may be a misunderstanding? As far as I can test (php 7.2) `mb_substr` supports both negative offsets and negative length, and has done so since the beginning?

**Comment by naturefund-falk** [comment]
The negative length is not mentioned in the official doc on php.net.

>  length
>  Maximum number of characters to use from str. If omitted or NULL is passed, extract all characters to the end of the string.

And from my own template, if i use v:format.substring("foobar", 2, -2) it returns "obar" and not "ob" as it should.

**Comment by NamelessCoder** [comment]
Ah - thanks for the info. I tested this with pure UTF strings and there, it works with negative offsets and counts correctly.
