### ISSUE TITLE
v:format.eliminate removing multiple whitespaces

### ISSUE THREAD

**Issue by linawolf** [FluidTYPO3/vhs#1598]
We are using v:format.eleminate to format class lists for containers via fluid. However our project settings are using multiple whitespaces and not tabs. It would be cool if multiple whitespaces could be reduced to one.

Example::
 `<f:section name="containerClass"><v:format.eliminate  tabs="1" unixBreaks="1" windowsBreaks="1">
        container-fluid
        <f:for each="{classes}" as='singleClass'>
            {singleClass}
        </f:for>
        {classadditional}
        {f:if(condition: parallax, then: 'container-parallax')}
     </v:format.eliminate></f:section>`

outputs
class="            container-fluid                            bg-blue                             "

desired:
class="container-fluid bg-blue"

**Comment by NamelessCoder** [comment]
Hi @linawolf,

Check out `v:format.pregReplace` for this purpose. A pattern of `\s{2,}` replaced with a space should work. Also, check out `v:format.trim` and `v:iterator.implode` ;)
