### ISSUE TITLE
Make Pages Ressource Viewhelper for sys_categories 

### ISSUE THREAD

**Issue by linawolf** [FluidTYPO3/vhs#1607]
Analogally to https://fluidtypo3.org/viewhelpers/vhs/2.1.2/Page/Resources/FalViewHelper.html I think it would be great to have a viewhelper that returns an array of the sys_categories attached to the page. 

Also 
    <v:page.info as="xyz" field="categories">

returns me just the number of categories attached not the data of the categories. 

there are some viewhelper being suggested in the web like
http://www.typo3-probleme.de/2017/09/08/typo3-sys-category-via-typoscript-und-fluid-viewhelper-auslesen-2129/

however these will just output a category selected by uid not by being attached to a page

**Comment by NamelessCoder** [comment]
Generally speaking, ViewHelpers which access DB data are discouraged (except when there are no good alternatives) to preserve the separation between storage and view. In the case of resolving categories my primary suggestion is to read these categories in a controller or data-processor, in whichever format you require (array, iterator, generator, filtered, etc.) and assign them to the template. It does require a bit of manual work, and even though they're handy, ViewHelpers should not be used as a go-to solution for every use case.

VHS aims to avoid adding more ViewHelpers that read from DB, and to remove existing ones that do this, as core alternatives become available.

**Comment by iiiich** [comment]
I'm with Linawolf. Categories should be available. I should not need a custom controller to display standard data from my page. I don't find it useful to have the number of categories, but no way to get the IDs. The categories are core functionality, and you should be able to display them with the core-like functionality via VHS or Fluid. Although I agree with NamelessCoder of course, ViewHelper should not replace database queries.

**Comment by TatjanaEsin** [comment]
> I'm with Linawolf. Categories should be available. I should not need a custom controller to display standard data from my page. I don't find it useful to have the number of categories, but no way to get the IDs. The categories are core functionality, and you should be able to display them with the core-like functionality via VHS. Although I agree with NamelessCoder of course, ViewHelper should not replace database queries.

I see it exactly the same way.
