### ISSUE TITLE
Current documentation?

### ISSUE THREAD

**Issue by stoppeye** [FluidTYPO3/vhs#1608]
When updating a site yesterday, we ran into errors with the Condition / Iterator / ContainsViewHelper, because our old templates still used the condition argument, which seems to have been dropped.

However, I couldn't find any hint to that in the available documentation (https://fluidtypo3.org/viewhelpers/vhs/master.html as per this Git repository). According to that documentation, the condition argument is still available.

Is there a newer documentation available somewhere? Updating, getting errors and then having to check the viewhelper source code (because no up-to-date docs are available) just doesn't seem to be a very sustainable process...

**Comment by NamelessCoder** [comment]
Newest generated docs are on https://viewhelpers.fluidtypo3.org/fluidtypo3/vhs/ but unfortunately aren't completely up to date. It still takes significant manual work to produce the right XSD files so the updates follow some time after releases.

**Comment by stoppeye** [comment]
Oh thanks! I didn't know about this link. I'd suggest to update the link in Documentation/README.md, because that still points to https://fluidtypo3.org/viewhelpers/vhs/master.html, where the docs end at 4.2.0...
