### ISSUE TITLE
v:if broken in TYPO3 8.x+

### ISSUE THREAD

**Issue by electricretina** [FluidTYPO3/vhs#1609]
It looks like there are breaking changes to TYPO3\CMS\Fluid\Core\Parser\SyntaxTree in version 8+ that remove a dependancy in the v:if view helper class. 

They have removed the BooleanNode class which breaks this view helper. Any template using v:if will throw an error. 

The only workaround is to use nested f:if statements in your fluid templates.

**Comment by NamelessCoder** [comment]
`v:if` is long deprecated and should not be used. Fluid on TYPO3v8 and above supports complex boolean expressions with `&&`, `||` and parenthesis grouping - nested conditions are not necessary. For the record, the `BooleanNode` class still exists in namespace `TYPO3Fluid\Fluid\Core\Parser\SyntaxTree`, just in case you need to use it somewhere.

**Comment by electricretina** [comment]
Thanks for clarifying this.  I ran into the issue while working on migrating some older fluid templates that used v:if.
