### ISSUE TITLE
<v:page.header.meta 'http-equiv' and 'content' reversed

### ISSUE THREAD

**Issue by tsurfer84** [FluidTYPO3/vhs#1615]
In Typo3 9.5 

<v:page.header.meta http-equiv="imagetoolbar" content="no" />

outputs

`<meta content="no" http-equiv="imagetoolbar" />`

It rather must be:

`<meta http-equiv="imagetoolbar" content="no" />`

**Comment by NamelessCoder** [comment]
Hi @tsurfer84,

Are you sure this order matters? I tried finding the relevant documentation but none of the sources (W3C) seem to declare that order matters (although their examples do list "content" last).

**Comment by tsurfer84** [comment]
Hi!

You are absolutely right, this order does not matter. It seem probably a little bit pedantic, but it is just unusual. And thus, the other viewhelper options have the ordinary order.
