### ISSUE TITLE
 When using vhs (6.0.0) and hiding an own Flux/Fluid-Content-Element an exception appears

### ISSUE THREAD

**Issue by de4123** [FluidTYPO3/vhs#1618]
I also found an error when I installed vhs (6.0.0) in TYPO3 8.7.30. When I hide a self written Flux/Fluid-Content-Element and call the Page Module in the TYPO3-Backend (When I call the List Module no error appears.) the following exception appears: 

```
Uncaught TYPO3 Exception
#1384611413: No record was found. The "record" or "uid" argument must be specified. (More information)

TYPO3Fluid\Fluid\Core\ViewHelper\Exception thrown in file
/usr/www/users/sabuco/sabuco-website-typo3/htdocs/typo3conf/ext/vhs/Classes/Utility/ErrorUtility.php in line 25.

44 FluidTYPO3\Vhs\Utility\ErrorUtility::throwViewHelperException("No record was found. The "record" or "uid" argument must be specified.", 1384611413)

/usr/www/users/sabuco/sabuco-website-typo3/htdocs/typo3conf/ext/vhs/Classes/ViewHelpers/Resource/Record/AbstractRecordResourceViewHelper.php:

00209: 
00210:         if (null === $record) {
00211:             ErrorUtility::throwViewHelperException('No record was found. The "record" or "uid" argument must be specified.', 1384611413);
00212:         } 
```

I am not sure if this exeption has something to do with the extensions "fluidpages (5.2.0)" and "flux (9.2.0)"? But in another TYPO3-Site with the same TYPO3-Core (8.7.30) and same installed extensions the error also appears. 

If I install the version "vhs (5.2.0)" everything works fine. 
Do you have any idea? Thanks a lot! 

(I attached the full exception stack and a screenshot of the hidden content element "Bigband Eselsberg") 

![exception-typo3-8 7 30-and-vhs-6 0 0](https://user-images.githubusercontent.com/19813055/73263054-f7398880-41cf-11ea-8bf4-0d3b25c5ac24.jpg)
![hiding-own-content-element](https://user-images.githubusercontent.com/19813055/73263055-f7d21f00-41cf-11ea-8fff-675ec76c44c2.jpg)

**Comment by rupasix** [comment]
Can you paste "Preview" section of that broken Flux content? Something's wrong with your fal resource there...

**Comment by NamelessCoder** [comment]
If you use FAL resource ViewHelpers in the Preview section, make sure you *do not use the `uid` argument*. Instead, use the `record` argument and pass the entire record. This bypasses visibility restrictions that normally apply when you attempt to load a record by UID through TYPO3's PageRepository, which is what the resource ViewHelpers if you only pass `uid`.

This by the way applies to any BE usage of these ViewHelpers, not just Flux.

**Comment by de4123** [comment]
Thank you very much for your answer! Here I paste you the "Preview" section of my Flux content: 

```
<f:section name="Preview">
        <h5>Content-Element: Karte (gelb)</h5>
        <div style="border-bottom: 1px solid #000; width=100%;"></div>
        <table width="100%" >
        <tr>
           <td>
               {v:content.resources.fal(field: 'bild', uid: '{record.uid}') -> v:iterator.first() -> v:variable.set(name: 'image')}
              <f:image treatIdAsReference="1" src="{image.id}" title="{image.title}" alt="{image.alternative}" maxWidth="64" height="" crop="{image.crop}"/>
           </td>
        </tr>
        <tr>
           <td>
               <f:format.crop maxCharacters="40"><b>{headline}</b><br /></f:format.crop>
           </td>
        </tr>
        <tr>
           <td>
               <f:format.crop maxCharacters="120">{text -> f:format.html()}</f:format.crop>
           </td>
        </tr>
    </table>
</f:section>
```

**Comment by NamelessCoder** [comment]
`{v:content.resources.fal(field: 'bild', record: record) -> v:iterator.first() -> v:variable.set(name: 'image')}` might help.

**Comment by de4123** [comment]
Thanks a lot! It was helpful. Now it is working! I wish you a good an sunny day!
