### ISSUE TITLE
Call to undefined method PageRepository::getFileReferences()

### ISSUE THREAD

**Issue by stefanweisswange** [FluidTYPO3/vhs#1626]
Setup
TYPO3 10.2
VHS 6.0

We use `v:page.resources.fal` to retrieve ressources from pages and get an exception:

`Call to undefined method TYPO3\CMS\Core\Domain\Repository\PageRepository::getFileReferences()
in /var/www/html/typo3conf/ext/vhs/Classes/ViewHelpers/Resource/Record/FalViewHelper.php line 128`

since the method `PageRepository::getFileReferences()` was deprecated in TYPO3 9 and was removed in TYPO3 10: [9.4 Changes » Deprecation: #85699 - Various methods in PageRepository](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.4/Deprecation-85699-MethodsInPageRepository.html).

I think the changes for the TYPO3 core are in this commit: [[TASK] Move PageRepository to EXT:core](https://github.com/TYPO3/TYPO3.CMS/commit/0cdab109a59b62c832ed61fe08c2a629865b52f7#diff-5161300c1ff6d717ac1fd764ac3304d6).

**Comment by Flimmerkiste** [comment]
Ran into this issue as well. The Class `TYPO3\CMS\Frontend\Page\PageRepository` was moved to `TYPO3\CMS\Frontend\Page\PageRepository`. Also the method `getFileReferences()` itself was deprecated and removed from the PageRepository Class in TYPO3 10.
