### ISSUE TITLE
Typo3 v10 - Asset Style Viewhelper can't map/process font paths | Deprcated Constants dropped

### ISSUE THREAD

**Issue by masonen** [FluidTYPO3/vhs#1628]
## Environment/Steps to Reproduce
- Typo3 version 10.3.0
- Flux latest development Version
- A provider Extension Implementing at least a simple Page Template rendering a CSS file via v:asset.style Viewhelper
- CSS file is located in EXT:xxx/Resources/Public/css
- Font Files located EXT:xxx/Resources/Public/fonts
- css contains font-face definitions like follows:
```/* alegreya-sans-regular - latin */
@font-face {
  font-family: 'Alegreya Sans';
  font-style: normal;
  font-weight: 400;
  src: local('Alegreya Sans Regular'), local('AlegreyaSans-Regular'),
       url('../fonts/alegreya-sans-v10-latin-regular.woff2') format('woff2'), /* Chrome 26+, Opera 23+, Firefox 39+ */
       url('../fonts/alegreya-sans-v10-latin-regular.woff') format('woff'); /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
}

body {
   font-family: "Alegreya Sans";
}

```

## Expected Behavior
CSS is Processed and fontfiles are processed for frontendrendering

## Actual Behavior
v:asset.style can not be rendered due to the usage of the deprecated constant PATH_site in AssetService (rel.: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/GlobalValues/Constants/Index.html#paths-constants)

The fix is pretty straight forward, hotfixed this in test environment today and got it working. Will try to provide a working PR within the week.

**Comment by Gitsko** [comment]
@masonen, you have a solution for the problem, I have integrated my assets via v:asset ?

**Comment by masonen** [comment]
Hey Claus
bug still persists when importing fontfaces of local fonts in css file via vhs:asset

see https://github.com/FluidTYPO3/vhs/blob/ab6acc1cf068f8087bcb8c1f577c41cc06be973a/Classes/Service/AssetService.php#L643

**Comment by NamelessCoder** [comment]
@masonen If you have time, would you mind helping with a PR to correct any `constant('PATH_site')` occurrences that I may have overlooked?

**Comment by masonen** [comment]
Sure thing. Expect sth within the week.

Claus Due <notifications@github.com> schrieb am Di., 2. Juni 2020, 15:09:

**Comment by NamelessCoder** [comment]
Thanks! :)

**Comment by masonen** [comment]
@NamelessCoder see #1657

**Comment by masonen** [comment]
@Gitsko PR is merged. Current development branch should fix the issue
