### ISSUE TITLE
Typo3 v10 and constants

### ISSUE THREAD

**Issue by MediKathi** [FluidTYPO3/vhs#1629]
Hello,

the deprecated constants are dropped in Typo3 v10.

The for example AssetService still uses PATH_site 
```PHP Warning: constant(): Couldn't find constant PATH_site in```

vhs 6.0

**Comment by masonen** [comment]
https://github.com/FluidTYPO3/vhs/issues/1628 related. Already on a fix in AssetService class. Probably a global problem in other classes. Can't put efford into big refactoring right now. Will probably supply a working PR for AssertService within the week

**Comment by NamelessCoder** [comment]
Solved via https://github.com/FluidTYPO3/vhs/commit/d1e3912b4070d6be9a751da7c6b20eec54dd7b04
