### ISSUE TITLE
Error in menu viewhelper and TYPO3 8.7.32

### ISSUE THREAD

**Issue by lstephanws** [FluidTYPO3/vhs#1637]
Hello,

Updating TYPO3 from 8.7.31 to 8.7.32 causes the following error 
`Fatal error: Declaration of FluidTYPO3\Vhs\ViewHelpers\Menu\AbstractMenuViewHelper::getArguments() must be compatible with TYPO3\CMS\Fluid\Core\ViewHelper\AbstractViewHelper::getArguments(): TYPO3Fluid\Fluid\Component\Argument\ArgumentCollection`

EXT:vhs : 4.3.3
TYPO3 : 8.7.32

Best regards

**Comment by AMartinNo1** [comment]
Hi,
this is a confirmed bug and the official way to go is upgrading to v6. However, there's a small backport which you can integrate.

> Unfortunately you'll have to upgrade VHS since the change in core is a cornerpiece of Fluid 3.0 support (which you can actually get in 8.7 by aliasing Fluid 3.0 to a 2.x version). There will not be any more releases of VHS in the 5.x branches. The good news is that there are no really breaking changes unless you use third-party ViewHelpers that extend from the abstract menu ViewHelper
>
> _Originally posted by @NamelessCoder in https://github.com/FluidTYPO3/vhs/issues/1632#issuecomment-608314333_

See #1632 for the issue and this PR for the backport #1636 Thus the PR is for v5, I can imagine it will work for v4 either.

PS: I did not test the backport either yet, but I feel like it's good to link it anyway.

**Comment by NamelessCoder** [comment]
Solution is to upgrade to VHS 6.0 which supports the same TYPO3 versions as the 5.x branch did. As @AMartinNo1 quotes, no further releases will be made in the 5.x and earlier branches.
