### ISSUE TITLE
useShortcutUid not retrieves the link from the target page

### ISSUE THREAD

**Issue by mhirdes** [FluidTYPO3/vhs#1639]
Related to the discussion #1422 Sry, but I could not reopen the issue.

This is the documentation to the useShortcutUid parameter:

> If TRUE, substitutes the link UID of a shortcut with the target page UID (and thus avoiding redirects) but does not change other data - which is done by using useShortcutData

This is currently not the case. The link is still the link of the current page, not the shortcut.

**Comment by ndurchx** [comment]
Same issue after upgrading to 6.0.4 (from <6.0.0). This issue is nearly a year old :(

**Comment by ndurchx** [comment]
Update: the fix would be one change.
https://github.com/FluidTYPO3/vhs/blob/e8c3cb24de088744a746a558d9f12e26996a78b0/Classes/ViewHelpers/Menu/AbstractMenuViewHelper.php#L464
should be:
`$pages[$index]['uid'] = $targetPage['uid'];`

**Comment by NamelessCoder** [comment]
Fixed in https://github.com/FluidTYPO3/vhs/pull/1704
