### ISSUE TITLE
Update v:page.header.canonical to use setMetaTag() for TYPO3 10

### ISSUE THREAD

**Issue by Flimmerkiste** [FluidTYPO3/vhs#1643]
**Setup**
TYPO3 10.4.1
VHS 6.0.0

Using the `v:page.header.canonical` viewhelper results in an exception: `Call to undefined method TYPO3\CMS\Core\Page\PageRenderer::addMetaTag()`

The `addMetaTag()` method was deprecated in TYPO3 9 and removed in TYPO3 10. The new method to be used is `TYPO3\CMS\Core\Page\PageRenderer::setMetaTag()`

**Comment by NamelessCoder** [comment]
Solved via linked PR.
