### ISSUE TITLE
Replace $GLOBALS['TSFE']->sys_language_uid in PageService.php

### ISSUE THREAD

**Issue by Flimmerkiste** [FluidTYPO3/vhs#1648]
There is a reference to `$GLOBALS['TSFE']->sys_language_uid`, which was removed in TYPO3 10, in `./Classes/Service/PageService.php` which seems to prevent menus (`<v:menu ...>`) from rendering in my project. Please replace this with language aspect.

**Comment by breakone** [comment]
#1650

**Comment by NamelessCoder** [comment]
@breakone Would you mind adding a `Close: #1648` line to your commit message for PR #1650? That way this current issue will be closed when the PR is merged ;)
