### ISSUE TITLE
Call to a member function get() on null after update to 6.0.1 or 6.0.2

### ISSUE THREAD

**Issue by tobiasschaeferptb** [FluidTYPO3/vhs#1655]
Hello,

after the update from 6.0.0 to 6.0.1 or 6.0.2 on a 8.7.34 installation I get this error in BE and FE:
Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to a member function get() on null | Error thrown in file typo3cms/typo3_src-8.7.34/typo3/sysext/extensionmanager/Classes/Utility/ConfigurationUtility.php in line 126.
Clearing typo3temp/var/Cache doesn't help, but only to go back to 6.0.0.

Cheers, Tobias

**Comment by NamelessCoder** [comment]
New release expected tomorrow, sorry for the inconvenience!

**Comment by tobiasschaeferptb** [comment]
With 6.0.3 the error doesn't occur anymore. Thanks for the quick fix.
Cheers, Tobias
