### ISSUE TITLE
How to restrict data in the arguments of ViewHelper?

### ISSUE THREAD

**Issue by typo3ua** [FluidTYPO3/vhs#1656]
I want to pass only `uid` of the page and nothing more.

`<v:render.uncache partial="Part" arguments="{uid: data.uid}"/>`
OR
`<f:render partial="Part" arguments="{uid: data.uid}"/>`

Is it possible?

**Comment by NamelessCoder** [comment]
It is that way by default - the reason you're seeing a different behavior (in context of https://github.com/FluidTYPO3/vhs/issues/1647) is that the variable named `settings` is always copied when you use `v:render.uncache`. See https://github.com/FluidTYPO3/vhs/blob/development/Classes/ViewHelpers/Render/UncacheViewHelper.php#L61. This is done since `settings` is usually expected to be transferred automatically when rendering a template. If you *must* avoid it you can recreate whichever parts of the `settings` array that you *do* need to use, e.g.:

```xml
<v:render.uncache partial="MyPartial" arguments="{foo: 'bar', settings: '{settingFoo: settings.settingFoo}'}" />
```

**Comment by typo3ua** [comment]
Thanks!

Now I did so...

`<v:render.uncache partial="Detail/Uncache" arguments="{page: pageData.uid, news: newsItem.uid, content: contentObjectData.uid, settings: '{startingpoint: settings.startingpoint}'}"/>`

![debug_vhs](https://user-images.githubusercontent.com/638022/83627064-0fb31880-a59f-11ea-9edb-f923ae04ddc7.png)

Yes, the array becomes smaller...but it does not resolve the problem #1647

**Comment by typo3ua** [comment]
> @NamelessCoder in #1647 wrote:
> Create a new partial to contain the call to v:render.uncache and then use f:render to render that partial, but limit the settings array. This will make the context inside the new partial contain a limited set of variables in {settings}, hopefully avoiding the unserializable ones.

**I did it:**

Install a clean system last version TYPO3 and `ext:bootstrap_package` and `ext:news`

1 step:
In the  `/ext/news/Resources/Private/Templates/News/Detail.html` I added
```
<f:render partial="Detail/RenderWithoutUncache" arguments="{
	page: pageData.uid,
	news: newsItem.uid,
	content: contentObjectData.uid,
	settings: '{startingpoint: settings.startingpoint}'
}"/>
```
2 step:
in the `/ext/news/Resources/Private/Partials/Detail/RenderWithoutUncache.html` I added
```
{_all->f:debug(title:'Render Without Uncache Partial')}

<v:render.uncache partial="Detail/RenderWithUncache" arguments="{
    page: page,
    news: news,
    content: content,
    settings: settings
}"/>

<h3>Render Partial - "f:render"</h3>
<ul>
    <li>Page UID == {page}</li>
    <li>News UID == {news}</li>
    <li>Content UID == {content}</li>
    <li>News settings (startingpoint) == {settings.startingpoint}</li>
</ul>
```
3 step:
In the `/ext/news/Resources/Private/Partials/Detail/RenderWithUncache.html` I added
```
{_all->f:debug(title:'Render With Uncache Partial')}

<h3>Render Partial - "v:render.uncache"</h3>
<ul>
    <li>Page UID == {page}</li>
    <li>News UID == {news}</li>
    <li>Content UID == {content}</li>
    <li>News settings (startingpoint) == {settings.startingpoint}</li>
</ul>
```
## Results:
**Debug:**
![render_partials](https://user-images.githubusercontent.com/638022/84400902-4c1fed80-ac0b-11ea-8bdf-8bd600c636d2.png)
### Render
I go to the `list news` then click record of news and go to the `detail news` all work well I see detail news and my technical information
**News->List->News->detail**

**Render Partial - "v:render.uncache"**
```
- Page UID == 2
- News UID == 4
- Content UID == 2
- News settings (startingpoint) == 3
```
 
**Render Partial - "f:render"**
```
- Page UID == 2
- News UID == 4
- Content UID == 2
- News settings (startingpoint) == 3
```
**But that is where it all well ends.... when I revisit again the same page I get this error**

![cannot_unserialize](https://user-images.githubusercontent.com/638022/84403681-a4a4ba00-ac0e-11ea-9b92-ef1cdb7b12d9.png)

This error appears when I revisit again the same page where the TYPO3 first `can unserialize` but then `cannot unserialize`.

When I first-time visite the page, where the happening "**unserialize**" and the TYPO3 can "**unserialize**" something then all works well and this error does not appear.

This error appears when I revisit again the same page where the TYPO3 first **can unserialize** but then **cannot unserialize**.

**Comment by NamelessCoder** [comment]
Happy to report that `v:render.uncache` was fixed to avoid the serialization problem!
