### ISSUE TITLE
deprecated code in ViewHelpers/Resource/AbstractImageViewHelper.php

### ISSUE THREAD

**Issue by almfisch** [FluidTYPO3/vhs#1664]
Hi,

this 2 lines forced a deprecated error:
205: $template->init();
206: constant('PATH_site');

Because of:
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.4/Deprecation-85408-TemplateServiceInitDeprecated.html
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.4/Deprecation-85285-DeprecatedSystemConstants.html

I replaced the 2 lines with:
$template;
$template->getFileName_backPath = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

Regards from Bavaria
Andi

**Comment by AMartinNo1** [comment]
I experienced same with 
> public/typo3conf/ext/vhs/Classes/Service/AssetService.php:643

Seems like this ext. is not compatible with T3 v10 even though it claims to be. Correct me if my impression is wrong.

```
$ ddev composer info typo3/cms-core | grep version
$ versions : * v10.4.5
```

```
$ ddev composer info fluidtypo3/vhs | grep version
$ versions : * 6.0.3
$ typo3-ter/vhs self.version
```

**Comment by AMartinNo1** [comment]
@NamelessCoder informed me that there's a pending release within [development](https://github.com/FluidTYPO3/vhs/tree/development)

> @AMartinNo1 fix is pending but release has not yet been made, see https://github.com/FluidTYPO3/vhs/commits/development - until release is made you can req `fluidtypo3/vhs:dev-development as 6.0.4`
> - Claus Due, 16.07.2020 in [Slack-Channel fluidtypo3](https://app.slack.com/client/T024TUMLZ/C03MQ0PLW)

In order to use an alias this repository needs to be registered manually in your composer.json

```
{
  "repositories": [
    {
      "type": "composer",
      "url": "https://composer.typo3.org"
    },
    {
      "type": "vcs",
      "url": "https://github.com/FluidTYPO3/vhs"
    }
  ],
}
```

[Here's a link](https://getcomposer.org/doc/articles/aliases.md) to the official documentation of composer alias.

**Comment by NamelessCoder** [comment]
Has been solved for quite some time - forgot to close the issue back then.
