### ISSUE TITLE
v:media.pdfThumbnail doesn't render thumbnail in frontend

### ISSUE THREAD

**Issue by tahnova** [FluidTYPO3/vhs#1666]
Hi guys, anyone got the problem in TYPO3 9, that vhs viewhelper for PDF thumbnails are not create and/or render anything in FE (works in BE - section preview)? - GM or IM + image clean up task makes no difference.

`<v:media.pdfThumbnail src="{f:uri.typolink(parameter: link)}" forceOverwrite="1" width="120" alt="{description}" background="#ffffff" />`

Do i miss or overlook something?

TYPO3 9.5.19
GraphicsMagick -> 1.3.24
ImageMagick -> 7.0.7-26
Ghostscript -> 9.23
vhs -> 6.0.3
flux -> 9.4.0 
Tests in install tool are working

Thanks in advance

Tah

**Comment by NamelessCoder** [comment]
Closing due to age. For the record: the file extension `pdf` must be added to the list of image-type file extensions in `$GLOBALS['TYPO3_CONF_VARS']['GFX']['imagefile_ext']`.
