### ISSUE TITLE
can not create og:title with v:page.header.metatag anymore

### ISSUE THREAD

**Issue by MoppieMop** [FluidTYPO3/vhs#1668]
I want to create with fluid opengraph-Metatags. For og:title it should look like this:
`<meta property="og:title" content="Open Graph Title/>`

But it looks like the property-Attribute is not used and the name field is now mandatory.

**Comment by NamelessCoder** [comment]
Fixed since 885f5465adc494cf7384b8d9277145a555d55587 - forgot to relate and close this issue.
