### ISSUE TITLE
Missing composer support information on TER page

### ISSUE THREAD

**Issue by markuspoerschke** [FluidTYPO3/vhs#1669]
Within the TYPO3 Extension Repository (TER), the information that this extension can be installed via composer is missing.

Link to the extension page: https://extensions.typo3.org/extension/vhs/

In the section »My Extensions« ist can be activated using the following options:

*  Published on Packagist 
*  Composer name of extension 

Setting the correct values here can help developers to install this extension via composer.

**Comment by NamelessCoder** [comment]
Thanks for the hints - this was solved some time ago :)
