### ISSUE TITLE
v:resource.record.fal: Respect page language

### ISSUE THREAD

**Issue by froehlit** [FluidTYPO3/vhs#1670]
Setup
TYPO3 9.5.19
VHS 6.0.3

After the commit [f70baf9](https://github.com/FluidTYPO3/vhs/commit/f70baf9eede41f7f4a4287b7af66130767127a1a), the `v:page.resources.fal` viewhelper only provides the fal resources of the main language.
I think the problem cause by the methode `getFileReferences` in class `\FluidTYPO3\Vhs\ViewHelpers\Resource\Record\FalViewHelper`. It doesn't use the language overlay of the page, to get the correct files from file reprository.

**Comment by froehlit** [comment]
#1671

**Comment by froehlit** [comment]
I opened a pull request #1671

**Comment by rupasix** [comment]
We also have this problem.

**Comment by pulponair** [comment]
confirmed, super annyoing needed to downgrade

**Comment by alexstocker** [comment]
@froehlit Seems this https://github.com/FluidTYPO3/vhs/issues/1626 Bugfix (Remove @deprecated method calls, establish T3 10 compatibility) causing this Problem.

vhs >=6.0.1 breaks page translations file reference lookup on T3 9.5

**Comment by fnagel** [comment]
Can confirm for TYPO3 10.4.28 and VHS 6.0.5.

**Comment by stefanheinrich** [comment]
Still not working for TYPO3 11.5.16 and VHS 6.1.2. @froehlit 's pull request would fix this issue. Currently only available in branch [development](https://github.com/FluidTYPO3/vhs).
