### ISSUE TITLE
Bug: Error "Couldn't find constant PATH_site" in TYPO3 10

### ISSUE THREAD

**Issue by janisint** [FluidTYPO3/vhs#1675]
**Setup:**
TYPO3 = 10.4.5
vhs = 6.0.3

I have a TYPO3 installation where I use vhs. Today I ran into the following error:
![image](https://user-images.githubusercontent.com/65291198/88392101-ba83ce00-cdbb-11ea-893a-fc2aac29d98f.png)

I think this is a bug since this constant was marked deprecated in TYPO3 10: [TYPO3 Constants](https://docs.typo3.org/m/typo3/reference-coreapi/9.5/en-us/ApiOverview/GlobalValues/Constants/Index.html#path-site)

In my opinion this error shouldn't appear.

**Temporary workaround**
create constant by yourself:
`if(!defined("PATH_site")) {
    define("PATH_site", \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/');
}`

**Comment by NamelessCoder** [comment]
Solved in dev-development, release is still pending. See https://github.com/FluidTYPO3/vhs/issues/1664 for further info and temporary workaround.
