### ISSUE TITLE
Broken link to documentation

### ISSUE THREAD

**Issue by remonator** [FluidTYPO3/vhs#1689]
The link in the file [Documentation/README.md](https://github.com/FluidTYPO3/vhs/blob/development/Documentation/README.md) points to a "Not found" page:

![image](https://user-images.githubusercontent.com/54318829/94791870-81c62d80-03d8-11eb-8c5d-277cbfc6dfca.png)

**Comment by NamelessCoder** [comment]
Fixed, thanks for reporting!
