### ISSUE TITLE
Argument Error for Meta Property v:page.header.meta property=".."

### ISSUE THREAD

**Issue by kledo-34** [FluidTYPO3/vhs#1694]
Hey there,
I updated to Typo3 10 and also to the latest vhs version.
v:page.header.meta throws an error for property="..."

Argument 2 passed to TYPO3\CMS\Core\Page\PageRenderer::setMetaTag() must be of the type string, null given, called in C:\xampp\htdocs\www\blocalhost\typo3conf\ext\vhs\Classes\ViewHelpers\Page\Header\MetaViewHelper.php on line 71

The following code throws an error now, it didn't on other versions before, so I think the property value gets lost somewhere.
<v:page.header.meta property="og:site_name" content="MySite"/>

I would be happy for a small fix ;)

**Comment by kledo-34** [comment]
I deubgged a little and found that in this line in side of the viewhelper
 $pageRenderer->setMetaTag('name', $this->arguments['name'], $content, $properties);
in the arguments array the values belong to the wrong keys. It doesnt find a value for name, because the name value is under the key 'scheme' and the property value is under the key 'content', so something got messed up there, maybe that information helps a little bit

**Comment by NamelessCoder** [comment]
https://github.com/FluidTYPO3/vhs/commit/885f5465adc494cf7384b8d9277145a555d55587 was pushed to `development` a couple of days ago to address precisely this VH. Would be great if you could test with the `development` branch if all works as expected!

**Comment by kledo-34** [comment]
THank you very much, works again as expected. I will report if I recognize anything else, thanks a lot for your work, vhs and flux are my top typo3 extensions and I have a lot of stuff depending on it, so thanks a lot for your work to maintain it, I really appreciate it :)
