### ISSUE TITLE
ContainsViewHelper causes deprecation Message in Typo3 7.4 when needle or haystack is numeric

### ISSUE THREAD

**Issue by christophrunkel** [FluidTYPO3/vhs#1699]
Adding strval fixes the problem 

protected static function evaluateCondition($arguments = null)
    {

        return false !== strpos(strval($arguments['haystack']), strval($arguments['needle']));
    }

**Comment by NamelessCoder** [comment]
Resolved by https://github.com/FluidTYPO3/vhs/commit/9eb59c6ab04adb38d53b87e7b4b169048e3c17d2
