### ISSUE TITLE
Missing TYPO3 v11.3/PHP 8 compatibility

### ISSUE THREAD

**Issue by samowitsch** [FluidTYPO3/vhs#1729]
Hi. I am playing around to update a TYPO3 instance to v11 and i see there is no matching version of vhs. Regards

**Comment by NamelessCoder** [comment]
Since https://github.com/FluidTYPO3/vhs/commit/c8c6c80c06d02253d3b208862daa6b71ef801218 you can use VHS with TYPO3 11.x - but for the time being only in `@dev` stability.

**Comment by samowitsch** [comment]
Ah, ok. Thx for info.
