### ISSUE TITLE
variable.extensionConfiguration not working with TYPO3 10

### ISSUE THREAD

**Issue by codingnik** [FluidTYPO3/vhs#1731]
Is anyone using variable.extensionConfiguration with TYPO3 10? I suppose this viewhelper isn't working currently due to  _Deprecation: #82254 - Deprecate $GLOBALS[‘TYPO3_CONF_VARS’][‘EXT’][‘extConf’]_, https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.0/Deprecation-82254-DeprecateGLOBALSTYPO3_CONF_VARSEXTextConf.html

$GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf'] is empty under TYPO3 10.

**Comment by NamelessCoder** [comment]
Solved by https://github.com/FluidTYPO3/vhs/pull/1732
