### ISSUE TITLE
About v:iterator.shift

### ISSUE THREAD

**Issue by typo3ua** [FluidTYPO3/vhs#1734]
I have array 
```
array(3 items)
   0 => ''
   1 => 'Item 1'
   2 => 'Item 2'
```
I need to delete `0 => ''` I added `{array -> v:iterator.shift(as: 'foo') -> v:variable.set(name: 'too')}`
...and I get the same
```
array(3 items)
   0 => ''
   1 => 'Item 1'
   2 => 'Item 2'
```
What is wrong?

**Comment by tantegerda1** [comment]
The `iterator.shift` viewhelper does not change the input data, it merely returns the _value_ of the first element.

https://github.com/FluidTYPO3/vhs/blob/development/Classes/ViewHelpers/Iterator/ShiftViewHelper.php#L17
> Shifts the first value off $subject (but does not change $subject itself as array_shift would).
If I'm correct, in your code the variable `foo` should hold the _value_ of the first array element, i.e. an empty string '', whereas the text output of the whole operation (none, an empty string again) is set in the variable `too`. The variable `array` is unchanged all the time.

You might want to have a look at `iterator.slice`.

**Comment by typo3ua** [comment]
Hello, @tantegerda1 
> 
> You might want to have a look at `iterator.slice`.

Thank you for reply... can you give me example

**Comment by typo3ua** [comment]
```
{v:variable.set(name: 'arr', value: '{0: \'\', 1: \'Item 1\', 2: \'Item 2\'}')}
{v:iterator.slice(haystack: '{arr}', start: 1, length: 2) -> v:variable.set(name: 'foo')}
```
Thanks! I did it...
