### ISSUE TITLE
Replace any PHP references to work in typo3 11.5

### ISSUE THREAD

**Issue by Liverson** [FluidTYPO3/vhs#1737]
Replace any PHP references of TYPO3\CMS\Frontend\Page\PageRepository to TYPO3\CMS\Core\Domain\Repository\PageRepository in any custom PHP code.

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Deprecation-88746-PageRepositoryPHPClassMovedFromFrontendToCoreExtension.html

**Comment by jtraulle** [comment]
#1738
