### ISSUE TITLE
TYPO3 v11 compatibility

### ISSUE THREAD

**Issue by mhirdes** [FluidTYPO3/vhs#1742]
Is there any plan to have a extension version ready for TYPO3 v11 LTS? Do you need help?

**Comment by coffeecode-de** [comment]
> Is there any plan to have a extension version ready for TYPO3 v11 LTS? Do you need help?

I can help too.

**Comment by NamelessCoder** [comment]
Thanks for the offer to help! The most important issue is https://github.com/FluidTYPO3/vhs/pull/1738 but if you know about anything else that also needs to be updated, then pull requests for those things would be *very* appreciated!

**Comment by velletti** [comment]
mabe rising the required version from ^11.1@dev to ^11 instead of : 
   
    "typo3/cms-core": "^8.7 || ^9 || ^10 || ^11.1@dev || dev-master",

**Comment by robsonrobi** [comment]
Yes, a new version would be great. I have vhs locally added and https://github.com/FluidTYPO3/vhs/pull/1738 ist the only necessary change...

**Comment by sneopu** [comment]
A v11 release would be great. Thanks for your efforts.

**Comment by msollmann** [comment]
I would be happy too about a v11 version :-)

**Comment by tomashavner** [comment]
Our upgrade to Typo3 v.11 depends on a new version of vhs. Would really appreciate it.

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
+1 for an official v11 release. Don't like to work with dev branches.

**Comment by wayheyha** [comment]
If you guys need some extra coffee i could donate some!! :-) 
This is finaly the only dependency left for me to update some systems. 

You guys are awesome!

**Comment by phifa** [comment]
can clients help to speed this up by sponsoring for example?

**Comment by mrk131324** [comment]
The biggest hurdle is to get a full list. The most common issue is an undefined array key in `$this->arguments` (a PHP8 issue). It happens so often, that we need the test suite to find them all.

**Comment by phifa** [comment]
is it safe to use the dev version in prod, when only using the `v:uri.image` viewhelper? I just need the `canvas` functionality.

**Comment by fgerards** [comment]
can we support your efforts to make vhs v11 compatible ?

**Comment by NamelessCoder** [comment]
It took a while but it's finally here - VHS 6.1 is now released, with v11 support.
