### ISSUE TITLE
Call to undefined method TYPO3\CMS\Extbase\Reflection\ReflectionService::getPropertyTagValues()

### ISSUE THREAD

**Issue by cbunhok** [FluidTYPO3/vhs#1747]
My Environment: 

- TYPO3 version 10.4.22
- Vhs version 6.0.5
![Uploading Screen Shot 2021-12-19 at 9.31.29 PM.png…]()

**Comment by NamelessCoder** [comment]
Hi @cbunhok - I don't see the screenshot you uploaded (upload appears to have failed). I would need at least a stack trace to be able to do something aobut this one.
