### ISSUE TITLE
"External manual" link from TER leads to "Page not found" error

### ISSUE THREAD

**Issue by remonator** [FluidTYPO3/vhs#1755]
[TER](https://extensions.typo3.org/extension/vhs) links to https://fluidtypo3.org/viewhelpers/vhs/, which leads to:

```
The page did not exist or was inaccessible. Reason: The requested page does not exist
```

![image](https://user-images.githubusercontent.com/54318829/153578926-1fd01f78-0266-41cd-9202-6ee3a095266b.png)

**Comment by NamelessCoder** [comment]
Thanks for the heads-up - this was fixed a while ago :)
