### ISSUE TITLE
Error when switching on TYPO3 debug mode when using v:render.uncache

### ISSUE THREAD

**Issue by h-e-l-l-o-w-o-r-l-d** [FluidTYPO3/vhs#1756]
Hi,

I know problems with v:render.uncache have been already reported. But this is a bit different.

I get the following error when I switch on the TYPO3 debug mode in the frontend via 
![typo3_debug_swicth](https://user-images.githubusercontent.com/51790093/154695179-1136e314-9e97-4bdd-8fa4-fe38b7b463bb.png)

(1/1) Error
Object of class TYPO3\CMS\Extbase\Mvc\Controller\ControllerContext could not be converted to string
in /var/www/intranet-ar/public/typo3/sysext/fluid/Classes/ViewHelpers/TranslateViewHelper.php line 147

There are no view helper arguments provided and I even cleared the settings variable to make sure it's not releated to faulty arguments like written in some issues. Still no luck.

Of course only happens on pages where v:render.uncache is present. The pages work as expected with debug mode off.

What can I do?

TYPO3 10.4.23
VHS 6.0.5

**Comment by Oktopuce** [comment]
Same problem for me with `v:render.uncache` when I activate the  Admin Panel in the Frontend.

`Object of class TYPO3\CMS\Extbase\Mvc\Controller\ControllerContext could not be converted to string`

TYPO3 10.4.25
VHS 6.0.5

**Comment by NamelessCoder** [comment]
Almost certainly fixed with https://github.com/FluidTYPO3/vhs/commit/78bdaf50a20329f243cd755a12cb12f61d1ed901 but just in case you still have troubles, please ask for this issue to be reopened!

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Works, thank you!

**Comment by X-Tender** [comment]
Can I apply this fix on the 6.0.5 Version? I currently cant upgrade the php to 7.4 which is required for the higher versions.

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Hi,

@NamelessCoder can I ask for reopening this? The exactly same error happens again from 7.0.0 onwards and does not happen with 6.1.3.

TYPO3 11.5.33
VHS 7.0.1
PHP 7.4

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Error is gone with TYPO3 12.
