### ISSUE TITLE
Fluid PageViewHelper error since vhs 6.1.0 : uriBuilder is null

### ISSUE THREAD

**Issue by itekne** [FluidTYPO3/vhs#1766]
Hello,

Since vhs 6.1.0, Fluid PageViewHelper throws an error as shown in the screenshot.

<img width="1196" alt="Capture d’écran 2022-05-03 à 10 34 11" src="https://user-images.githubusercontent.com/309381/166819271-7341ba9c-e6ca-4b9f-a189-f00eb450a24d.png">

Resolved by falling back to vhs 6.0.5

TYPO3 10.4.27

Thank you
Thomas

**Comment by NamelessCoder** [comment]
Hi @itekne - can you tell a bit more about the context, most importantly where you are using the ViewHelper (content element, page template, inside v:render.uncache, etc.)?

**Comment by itekne** [comment]
Hi @NamelessCoder ^^

Thanks Claus pour your quick answer.
I just tested the thing and the context is : in a page template, a v:render.uncache of a partial containing a f:security.ifAuthenticated with a f:link.page inside.
If I remove the v:render.uncache, everything works again.

Cheers
Thomas

**Comment by Ceremony64** [comment]
I can confirm this issue.
It seems like it is unable to get a uriBuilder, as the request is basically lost in the uncached variant of f:render.

f:render:
![image](https://user-images.githubusercontent.com/5873369/168264879-7437cf5c-437d-4213-bffe-216bb1e410b7.png)

v:render.uncache:
![image](https://user-images.githubusercontent.com/5873369/168265003-bf00fb80-748f-48ed-82d4-1a950614940c.png)
