### ISSUE TITLE
Automatic conversion of false to array is deprecated in PHP 8.1

### ISSUE THREAD

**Issue by tastensolo** [FluidTYPO3/vhs#1767]
Hi,

I get the following message with the TYPO3 v11 in PHP 8.1:

PHP Runtime Deprecation Notice: Automatic conversion of false to array is deprecated in /var/www/html/www/web/typo3conf/ext/vhs/Classes/ViewHelpers/Render/RequestViewHelper.php line 176

Thanks

**Comment by NamelessCoder** [comment]
Should be solved in current development branch - but if not, ping me here to reopen.
