### ISSUE TITLE
v:render.uncache leads to PHP Warning: Undefined array key "controllerExtensionName"

### ISSUE THREAD

**Issue by tastensolo** [FluidTYPO3/vhs#1773]
Hi,

I get the following message with the TYPO3 v11 in PHP 8.1 with v:render.uncache partial="MiniBookmark"/>

PHP Warning: Undefined array key "controllerExtensionName" in /var/www/html/www/web/typo3conf/ext/vhs/Classes/View/UncacheTemplateView.php line 87

Thanks!

**Comment by tastensolo** [comment]
Unfortunately that is not the case. VHS 6.1.1 is in use.

**Comment by kiwi2101** [comment]
Hi,
I get following error message with VHS 6.1.2, PHP 8.0.19 and v:render.uncache 

PHP Warning: Undefined array key "extensionName" in /var/www/html/_htdocs/typo3/sysext/extbase/Classes/Mvc/ExtbaseRequestParameters.php line 154

**Comment by kiwi2101** [comment]
comment out line 96

$request->setControllerObjectName($conf['controllerContext']['controllerObjectName']);

solve the issue

**Comment by NamelessCoder** [comment]
Solved in `dev-development`. VHS 6.1.x will no longer be updated.

**Comment by andreknieriem** [comment]
But why? We are getting this on v11 LTS with latest vhs availabled. So how should we fix it, if we have a composer based installation and CI chain? This is a really user unfriendly answer

**Comment by NamelessCoder** [comment]
@andreknieriem You can either use `dev-development` temporarily as composer constraint for the dependency. Or you can apply a specific patch with `composer-patches`. Or you can wait for the next VHS version to be released (which will be v7.0).

Same as with any other composer dependency ;)
