### ISSUE TITLE
Setting typolink.useCacheHash has no effect in TYPO3v9+

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/vhs#1774]
vhs uses the `useCacheHash` when generating links in two places:
- PageService::getItemLink https://github.com/FluidTYPO3/vhs/blob/44394a7ac79561487ae164399ad7ed9ce1e5b01c/Classes/Service/PageService.php#L246
- LanguageMenuViewHelper::getLanguageUrl https://github.com/FluidTYPO3/vhs/blob/12ee8cc2675929b9999f8f034298b7a1f6844ec3/Classes/ViewHelpers/Page/LanguageMenuViewHelper.php#L436

This generates deprecation notices:
> TYPO3 Deprecation Notice: Setting typolink.useCacheHash has no effect anymore. Remove the option in all your TypoScript code and Fluid templates. in typo3/sysext/frontend/Classes/Typolink/PageLinkBuilder.php line 155

This option
- has no effect since TYPO3v9: https://docs.typo3.org/c/typo3/cms-core/9.5/en-us/Changelog/9.5/Feature-86365-RoutingEnhancersAndAspects.html#impact
- has been removed in v10: https://docs.typo3.org/c/typo3/cms-core/10.4/en-us/Changelog/10.0/Breaking-87193-DeprecatedFunctionalityRemoved.html

But vhs still supports TYPO3 v8.7, so just removing it is not possible.

Shall we add a core version specific check for that parameter?

**Comment by NamelessCoder** [comment]
> Shall we add a core version specific check for that parameter?

Yes, that is exactly the solution I would choose - e.g. `version_compare(VersionNumberUtility::getCurrentTypo3Version(), '9.5', '<=')`. I would then also make a note in the registerArgument() description that the argument has no effect on TYPO3 9.5 and above.
