### ISSUE TITLE
$TSFE->fePreview not usable anymore in TYPO3v11+

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/vhs#1775]
vhs uses `$TSFE->fePreview` in ``AbstractRecordResourceViewHelper::getRecord`: https://github.com/FluidTYPO3/vhs/blob/12ee8cc2675929b9999f8f034298b7a1f6844ec3/Classes/ViewHelpers/Resource/Record/AbstractRecordResourceViewHelper.php#L170

This generates a deprecation notice on TYPO3 10:
> TYPO3 Deprecation Notice: Property $TSFE->fePreview is not in use anymore as this information is now stored within the FrontendPreview aspect. in typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php line 4101

This property has been
- deprecated in TYPO3v10: https://docs.typo3.org/c/typo3/cms-core/10.4/en-us/Changelog/10.0/Feature-88791-IntroducePreviewAspectInContext.html
- removed in TYPO3v11: https://docs.typo3.org/c/typo3/cms-core/11.3/en-us/Changelog/11.0/Breaking-91473-DeprecatedFunctionalityRemoved.html

Since vhs supports TYPO3 v8 and v9, how should this be handled?
Version-specific code for 8-9 and 10+?

**Comment by NamelessCoder** [comment]
May be solvable with an additional `isset()` - if not, then a `version_compare` makes sense.
