### ISSUE TITLE
Call to protected method TYPO3\CMS\Core\Domain\Repository\PageRepository::init() from context 'FluidTYPO3\Vhs\Service\PageService'

### ISSUE THREAD

**Issue by dennismetz** [FluidTYPO3/vhs#1782]
In the page module I get the following error message when I try to open some pages:

Call to protected method TYPO3\CMS\Core\Domain\Repository\PageRepository::init() from context 'FluidTYPO3\Vhs\Service\PageService'

VHS 6.1.0 / 6.1.1 (works fine in 6.0.5)
TYPO3 10.4.28
PHP 7.4.6

**Comment by jwittorf** [comment]
Same overhere, maybe this indicator can help: I'm calling `{v:page.rootline(pageUid: '{pageUid}')}` inside the `<f:section name="Preview"></f:section>`

**Comment by NamelessCoder** [comment]
Solved in current development branch. The `init()` method will only be called on TYPO3 8.7.
