### ISSUE TITLE
Call to undefined method TYPO3\CMS\Core\Utility\GeneralUtility::getApplicationContext()

### ISSUE THREAD

**Issue by bavarianbytes** [FluidTYPO3/vhs#1783]
`v:condition.context.isDevelopment` in TYPO3 11 seems to use deprecated method and causes this exception in `ext/vhs/Classes/ViewHelpers/Condition/Context/IsDevelopmentViewHelper.php` line 32:
`Call to undefined method TYPO3\CMS\Core\Utility\GeneralUtility::getApplicationContext()`

**Comment by mediaessenz** [comment]
I can confirm this issue.
