### ISSUE TITLE
v:content render not working in v11 ?

### ISSUE THREAD

**Issue by Seitenmacher** [FluidTYPO3/vhs#1787]
Seems like v:content.render doesn't render anything right now ?
Installation is based on flux with custom elements, but v:content.render doesn't render a content element by colPos/column and also not rendering a content element by using <v:content.render contentUids="{0: 1}"/>

Not getting any output in frontend - anybody else has this issues ?

Same workflow in v10 is working perfect.

**Comment by NamelessCoder** [comment]
I tested this just now on v11 and it appears to be working like it should. Is there anything special about the content/column setup, e.g. not in the default language, fallback rendering mode, content sliding, workspace active or other? Shot from the hip: did you perhaps forget to install the `fluid_styled_content` extension (or another "content rendering" extension that provides basic `tt_content` TS setup)?

**Comment by JonasHaas** [comment]
having the same issue without flux. fluid_syled_content is installed and working

the content element with uid: 3 exists.

`<v:content.render contentUids="{0: 3}"/>`

`PHP Warning: Undefined array key "tt_content:3" in /var/www/html/public/typo3conf/ext/vhs/Classes/ViewHelpers/Content/AbstractContentViewHelper.php line 222`

**Comment by mediaessenz** [comment]
Can confirm.

`if (0 < $GLOBALS['TSFE']->recordRegister['tt_content:' . $row['uid']] ?? 0) {`

... should also do the job.

**Comment by dirnbauer** [comment]
I can confirm this bug on TYPO3 11.5.14, PHP 8.0.22

`if (0 < isset($GLOBALS['TSFE']->recordRegister['tt_content:' . $row['uid']]) ? $GLOBALS['TSFE']->recordRegister['tt_content:' . $row['uid']] : 0) {`

**Comment by hhchrizzo** [comment]
I can confirm this bug also with
PHP 8.1
TYPO3 11.5.17
VHS 6.1.2

**Comment by nabossha** [comment]
confirm this as well using:

- PHP 8.0.24
- TYPO3 11.5..18
- VHS 6.1.2

the code from @ecosmox36 worked for me as well.

**Comment by t3touch** [comment]
Same problem with
PHP 8.0.21
T3 11.5.19
VHS 6.1.2

**Comment by NamelessCoder** [comment]
Fixed via https://github.com/FluidTYPO3/vhs/commit/f76456a340b05d14ebc720c92adaf3dd34f93984#diff-943e93d35eada4f1bef5a2f95f81740f338fde28a0431fc9d733d1a106c1d51bL183

**Comment by ako-3004** [comment]
I got another unexpected exception in line 239:
`PHP Warning: Undefined array key "tt_content:2835" in /var/www/fohhn_live/typo3conf/ext/vhs/Classes/ViewHelpers/Content/AbstractContentViewHelper.php line 239`

```
238        if (false === empty($parent)) {
239            ++$GLOBALS['TSFE']->recordRegister[$parent];
240        }
```

TYPO3 11.5.22
VHS 6.1.3
PHP Version 8.0.27

**Comment by RKlingler** [comment]
I'm getting the same same exception from line 239 after upgrading to PHP 8.

`PHP Warning: Undefined array key "tt_content:38796" in /srv/www/public/typo3conf/ext/vhs/Classes/ViewHelpers/Content/AbstractContentViewHelper.php line 239`

TYPO3 11.5.24
VHS 6.1.3
PHP 8.1.15

**Comment by MarcoHaase** [comment]
compare to the other issues, "PHP Warning: Undefined array key"

you need to fix the parent too.

line ~235:
old:
`++$GLOBALS['TSFE']->recordRegister[$parent];`

new:
```
        if (false === empty($parent)) {
            if (0 < isset($GLOBALS['TSFE']->recordRegister[$parent]) ? ++$GLOBALS['TSFE']->recordRegister[$parent] : 0) {
                return null;
            }
        }
```

**Comment by cmichael-de** [comment]
Still got the error PHP Warning: Undefined array key "tt_content: ..." inside an gridelements Template. 

    # Flyout Sidebar
    # TSconfig: 47.flexformDS = FILE:typo3conf/ext/my/Resources/Private/Flexforms/Ext/Grid_Elements/flyout_sidebar.xml
    47 < lib.gridelements.defaultGridSetup
    47 {
        cObject = FLUIDTEMPLATE
        cObject {
            file = {$templatePath}Ext/Grid_Elements/flyout_sidebar.html
        }
    }

inside flyout_sidebar.html I'am calling:

` <v:content.render contentUids="{0: 1764}" ></v:content.render>`


In my partial Footer.html the same line of code is working.

**Comment by cmichael-de** [comment]
PHP Warning: Undefined array key "tt_content:8393" in /www/htdocs/blablabla/typo3conf/ext/vhs/Classes/ViewHelpers/Content/AbstractContentViewHelper.php line 239

**Comment by NamelessCoder** [comment]
This is line 239 in `dev-development`: https://github.com/FluidTYPO3/vhs/blob/development/Classes/ViewHelpers/Content/AbstractContentViewHelper.php#L239C63-L239C63

That code would not raise the error in question. And the statement that _might_ raise the error is guarded by an `isset()` check.

Please make sure you verify whether the issue exists in `dev-development` before you report it. That branch is always the most current development state and if a bug does not exist in there, it is already solved and will be included in the next release.

**Comment by MarcoHaase** [comment]
common! you fixed it at Jul 12 --> https://github.com/FluidTYPO3/vhs/commit/6f8c743e2e078afa0bed3c0511ec87dad28365fd
I wrote it at Jul 12 --> https://github.com/FluidTYPO3/vhs/issues/1787#issuecomment-1632223615

@cmichael-de: please get the last version of vhs.

@cmichael-de: Hol Dir die neuste VHS Version. Sie haben den bug gefixt seit 12. Juli https://github.com/FluidTYPO3/vhs/commit/6f8c743e2e078afa0bed3c0511ec87dad28365fd

**Comment by cmichael-de** [comment]
Yes it is working in development branch. 

@MarcoHaase  Thanks for your hints!
