### ISSUE TITLE
v:menu not working in v11

### ISSUE THREAD

**Issue by JonasHaas** [FluidTYPO3/vhs#1791]
i have a page with 3 subpages and the id 13

when i use

`<v:menu pageUid="13" />`

 it throws this error:
![image](https://user-images.githubusercontent.com/81745301/174785363-3c16a858-f2d3-4231-9212-bd405a97d0bb.png)

It worked fine in older versions

**Comment by hhchrizzo** [comment]
This should fix it
`
$content = $this->renderChildren();
-            if (0 < mb_strlen(trim($content))) {
+            if (0 < mb_strlen(trim($content ?? ''))) {
`

**Comment by NamelessCoder** [comment]
Fixed in current development branch.
