### ISSUE TITLE
Temporary asset path as distinct vhs folder inside of typo3temp/assets/

### ISSUE THREAD

**Issue by tastendruecker** [FluidTYPO3/vhs#1800]
https://github.com/FluidTYPO3/vhs/blob/c962d0dce84ad9b1cb2091ba716befab98be34ec/Classes/Service/AssetService.php#L346

Would be nice if the vhs assets were stored inside a distinct folder within typo3temp/assets. Two benefits:
1. No more need to check for TYPO3 version in AssetService->getTempPath()
2. Back-end users could manually remove the asset files using the Install Tool

The directory for the temporary assets just has to be defined within ext_emconf.php like e.g.
`'createDirs' => 'typo3temp/assets/tx_vhs',`

**Comment by NamelessCoder** [comment]
This seems very reasonable and I have no objections. It's even easier now since `AssetService::getTempPath` no longer needs a version detection to use different dirs on different versions.
