### ISSUE TITLE
LanguageMenuViewHelper can trigger a caching problem with URL parameters

### ISSUE THREAD

**Issue by ako-3004** [FluidTYPO3/vhs#1805]
vhs 6.1.2 / TYPO3 10.4.32

Situation:
- Page cache has just been cleared.
- A bot makes the first call with additional URL parameters
Then these URL parameters are taken over by the LanguageMenuViewHelper and also end up in the page cache. I found e.g. &utm_source=x parameters in the URLs of the language navi.

Could replicate this on different webs with different VHS and TYPO3 versions.
Cause here is the 'addQueryString' => 1 in getLanguageUrl() in ViewHelper.

I wouldn't consider this a bug but an additional difficulty in dealing with the 
LanguageMenuViewHelper.

I see possible workarounds:
1. the LanguageMenuViewHelper must be called from an uncached plugin.
2. the addQueryString should be set to 0, but then necessary URL parameters from the system must be explicitly allowed.

**Comment by NamelessCoder** [comment]
You are supposed to use the `excludeQueryVars` argument on the ViewHelper to list the arguments you do NOT want to append to the URL of each language option. By default, the arguments `id,L,cHash` are excluded.

See also the section "Excluding GET Parameters from Page Variants" on https://b13.com/blog/caching-in-typo3-part-2-cache-variants-of-a-page-with-chash.  You may want to assign the value of `$TYPO3_CONF_VARS[FE][cacheHash][excludedParameters]` to your template and use this as value of the `excludeQueryVars` argument for `v:languageMenu` (this option is designed precisely for various `utm_*` and similar types of URL parameters).
