### ISSUE TITLE
PHP Warning: Undefined array key "anyBackendUserGroup"

### ISSUE THREAD

**Issue by mvinaj** [FluidTYPO3/vhs#1808]
PHP Warning: Undefined array key "anyBackendUserGroup" in /var/www/html/dev/typo3conf/ext/vhs/Classes/ViewHelpers/Security/AbstractSecurityViewHelper.php line 174

TYPO3 11.5 php 8.1
-> missing isset

**Comment by NamelessCoder** [comment]
Fixed via https://github.com/FluidTYPO3/vhs/commit/f76456a340b05d14ebc720c92adaf3dd34f93984#diff-4f4d1dd01fdd344f4298bc8a96379c83d851e17aa4656c2d8bad66b106a6ffd1L153
