### ISSUE TITLE
[BUG] - v:content.render with slide="-1"

### ISSUE THREAD

**Issue by ogrosko** [FluidTYPO3/vhs#1819]
Hello

I've noticed bug with a `<v:content.render column="1" slide="-1" />` then content is not rendered. Neither from current page nor from parent pages. 

I'm suspecting from this behaviour this [line](https://github.com/FluidTYPO3/vhs/blob/development/Classes/Traits/SlideViewHelperTrait.php#L112) code. If argument `limit` is not set then limit is `$limit = null` and [this](https://github.com/FluidTYPO3/vhs/blob/development/Classes/Traits/SlideViewHelperTrait.php#L149) piece of code is broken.

I fixed it temprarily with adding `limit="0"` attribute to VH

Typo3 v 11.5.18
VHS dev-development

**Comment by grischpel** [comment]
another temp fix for this issue is: slideCollect="1" but as @ogrosko said, the old behavior does not work anymore

**Comment by mkrappitz** [comment]
Can confirm. This breaks with EXT:vhs 6.1.3. Bug or Feature?

**Comment by kszymukowicz** [comment]
Confirm.

**Comment by denislorch** [comment]
Related [condition](https://github.com/FluidTYPO3/vhs/blame/05bec6cab8e8fba2d29fbed9ee1ab99ab12cd1fe/Classes/Traits/SlideViewHelperTrait.php#L149)

**Comment by MediKathi** [comment]
stil present it VHS 6.1.3 from TER

**Comment by ogrosko** [comment]
same problem with `<v:page.resources.fal(slide:'-1') />`

**Comment by NamelessCoder** [comment]
Fixed in `dev-development`.
