### ISSUE TITLE
After update to 6.1.3 page.resources.fal don't work

### ISSUE THREAD

**Issue by max951** [FluidTYPO3/vhs#1849]
After update from 6.1.2 to 6.1.3 this code doen't work.

`{v:page.resources.fal( field:'heroimage', slide:'{v:condition.variable.isNull(value:heroslide,then:\'-1\',else:heroslide)}' ) -> v:variable.set(name: 'media')}
`

Is there a deprecation that I haven't found? Or is here a bug inside?

TYPO3 9.5.40
PHP 7.4

**Comment by BenKruft** [comment]
i had the same with T3 10.4 and T3 11.5. 

This code didn't work anymore:
` <v:resource.resources.fal table="pages" field="media" uid="{data.uid}" as="images" slide="-1" >
    <f:if condition="{images}">
        <div class="teaser">...</div>
    </f:if>
</v:resource.resources.fal>`

switched to a different solution.

**Comment by NamelessCoder** [comment]
Fixed since https://github.com/FluidTYPO3/vhs/commit/9b64157959d6237efd8d4d8c0aeb510e10b9fc36 and https://github.com/FluidTYPO3/vhs/commit/3b4c8e04649ad9de523b4413b1fab0ca24d53a22.
