### ISSUE TITLE
v:page.languageMenu: missing array key 'flag'

### ISSUE THREAD

**Issue by tcrass** [FluidTYPO3/vhs#1851]
Hi there,

after debugging why 'English' (the GB.png flag, to be precise) was no longer rendered as option in my language menu, I ended up implementing pretty much the same solution as mentioned by [lsascha](https://github.com/lsascha) in #1788 as https://github.com/lsascha/vhs/commit/dc25edcf95dc06a59569eb9a2006159abee45bff.diff. I therefore suggest to merge lsascha's patch into the official vhs tree.

Cheers --
Torsten

**Comment by NamelessCoder** [comment]
Referenced issue is solved.
