### ISSUE TITLE
PHP Warning: Undefined array key in /var/www/html/dev/typo3conf/ext/vhs/Classes/ViewHelpers/Content/AbstractContentViewHelper

### ISSUE THREAD

**Issue by mvinaj** [FluidTYPO3/vhs#1852]
Hi,
i get this Error
TYPO3 11
PHP 8.1
VHS 6.1.3
Core: Error handler (FE): PHP Warning: Undefined array key "tt_content:2392" in /var/www/html/dev/typo3conf/ext/vhs/Classes/ViewHelpers/Content/AbstractContentViewHelper.php line 239

**Comment by dpCPO** [comment]
Same Problem here:

`<v:content.render contentUids="{0: '1907'}"/>`

Leads to this error message:

PHP Warning: Undefined array key "tt_content:2082" in /var/www/typo3/typo3conf/ext/vhs/Classes/ViewHelpers/Content/AbstractContentViewHelper.php line 239

TYPO3 11.5.22
PHP 8.1.2
VHS 6.1.3

**Comment by dpCPO** [comment]
Propably a Solution:
`diff ./Classes/ViewHelpers/Content/AbstractContentViewHelper.php ../../ext/vhs/Classes/ViewHelpers/Content/AbstractContentViewHelper.php 
239c239,244
<             ++$GLOBALS['TSFE']->recordRegister[$parent];
---
>             if( !key_exists($parent, $GLOBALS['TSFE']->recordRegister) ){
>                 $GLOBALS['TSFE']->recordRegister[$parent] = 1;
>             }
>             else {
>                 ++$GLOBALS['TSFE']->recordRegister[$parent];
>             }
`

**Comment by NamelessCoder** [comment]
Has been fixed since Mar 16 2023 - https://github.com/FluidTYPO3/vhs/commit/938780d27d108561624a478dba68286cedfca60f
