### ISSUE TITLE
PHP 8 Warning in Classes/Provider/PageProvider.php line 402

### ISSUE THREAD

**Issue by ako-3004** [FluidTYPO3/vhs#1854]
another undefinded array index warning by php8 in Classes/Provider/PageProvider.php line 402

TYPO3\CMS\Core\Error\Exception
PHP Warning: Undefined array key "settings.something" in [...]/flux/Classes/Provider/PageProvider.php line 402

only got this when adding a new field to a existing page flux form configuration.
Not quite sure what happens here, but for me this fixes the warning:

changed
`        $empty = (true === empty($values[$name]) && $values[$name] !== '0' && $values[$name] !== 0);`

to
```
        if (empty($values)) {
            $empty = true;
        } else if (!isset($values[$name])) {
            $empty = true;
        } else {
            $empty = (true === empty($values[$name]) && $values[$name] !== '0' && $values[$name] !== 0);
        }
```

**Comment by NamelessCoder** [comment]
Hi @ako-3004,

This error concerns Flux - but you reported it to VHS. Would you mind recreating it in Flux's issue tracker https://github.com/FluidTYPO3/flux/issues so it can be processed there? Thanks!

**Comment by ako-3004** [comment]
:D Sorry for that... I do...
