### ISSUE TITLE
PHP 8 Deprecation in v:resource.record.fal

### ISSUE THREAD

**Issue by rk-mxp** [FluidTYPO3/vhs#1857]
The `v:resource.record.fal` ViewHelper throws the following PHP 8 deprecation:

```
PHP Runtime Deprecation Notice: PDOStatement::fetch(): Passing null to parameter #1 ($mode) of type int is deprecated in /.../vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php line 138
```

Reason is the `FluidTYPO3\Vhs\ViewHelpers\Resource\Record\AbstractRecordResourceViewHelper::getRecord` function. The function uses the deprecated `fetch` function of the Doctrine `ResultStatement` with no parameter for `fetchMode` (making it `null`). The `null` value gets propagated in Doctrine to the PHP class [PDOStatement](https://www.php.net/manual/de/pdostatement.fetch.php) that defines `fetchMode` as int, resulting in the above mentioned error.

Solution:
- Use one of the non deprecated functions `fetchNumeric(), fetchAssociative() or fetchOne()` as described in the deprecation notice
- Explicitly set the fetchMode to the correct Doctrine\DBAL\FetchMode

**Comment by NamelessCoder** [comment]
There are no more usages of deprecated Doctrine function calls.
