### ISSUE TITLE
Typo 3 version 12

### ISSUE THREAD

**Issue by RZivaralam** [FluidTYPO3/vhs#1858]
I would like to know when will the plugin be compatible with Typo 3 version 12 be released.

**Comment by linawolf** [comment]
Good Question, I have the same. Is anyone working on it yet?

**Comment by SvenJuergens** [comment]
The development branch is already TYPO3 12 compatible, maybe there are some stoppers before a final release, @NamelessCoder ? It's possible to help with it?

**Comment by cyrakoenig** [comment]
What is the current situation here? Need vhs for my TYPO3 12 project ;)

**Comment by NamelessCoder** [comment]
1. I'm working on it and have been for a couple of weeks now.
2. Yes, there are show-stoppers. TYPO3 12.4 contains several breaking changes with no backwards compatibility, in some cases even without alternatives.
3. I currently don't have a precise idea about when it will be done, but we're likely talking weeks not days.
4. You can help by using `dev-development` and reporting or solving and pull-request'ing any problems you may find.
