### ISSUE TITLE
v:asset.script doesn’t work anymore after update to 6.1.3

### ISSUE THREAD

**Issue by klodeckl** [FluidTYPO3/vhs#1862]
After updating vhs from 6.1.2 to 6.1.3 the viewhelper v:asset.script does not work anymore. Downgrading resolves the problem. TYPO3 10.4.36 (11 not tested). Non composer mode.

**Comment by NamelessCoder** [comment]
@jgreiner Your problem is almost certainly not the same as @klodeckl  (yours is about TS-defined assets, his is about ViewHelper-defined assets). Regardless: the linked commit should solve your issue.

@klodeckl Can you elaborate a bit about _how_ the ViewHelper doesn't work?

**Comment by NamelessCoder** [comment]
Closing as probably solved and due to lack of feedback on request for specifics.
