### ISSUE TITLE
TYPO3 v12/v11 - Cannot render contents with last commit

### ISSUE THREAD

**Issue by Apen** [FluidTYPO3/vhs#1864]
In your last commit, i think there is a bug wich avoid content rendering in frontend.

https://github.com/FluidTYPO3/vhs/blob/1bede66ecc9fc8d294feb08d6feeab0b6126cd25/Classes/ViewHelpers/Content/AbstractContentViewHelper.php#L117

The $pageUid is a parameter of the function, wich in my case is correct.
But your ovewrite it with `$this->arguments['pageUid']`, wich in my case is always 0.

If i delete this line, everything if fine.

**Comment by NamelessCoder** [comment]
Confirmed - and I actually stumbled on this one myself yesterday before I looked at the bug tracker!
