### ISSUE TITLE
v:menu.list pages dynamicly generated

### ISSUE THREAD

**Issue by wtdesign** [FluidTYPO3/vhs#1867]
Is there a way to generate a menu based only on the parentID? At the moment I have do write all page-IDs in a comma seperated list.

`
      <v:menu.list levels="4" pages="{pid}"  entryLevel="0" showHiddenInMenu="false" as="sections">
      </v:menu.list>
`

**Comment by NamelessCoder** [comment]
```
<v:menu.list levels="4" pages="{pid}"  entryLevel="0" showHiddenInMenu="false" />
```

(leave out the `as` argument and omit any tag content)

**Comment by wtdesign** [comment]
Thank you for respond, but TYPO3 shows me an error as you can see in screenshot below.
I used the Beta-Version of VHS 6.1.3. Is that the reason, why it doesn't work?
`
<v:menu levels="4" pageUid="{parentPageUid}" as="sections" />
    <f:for each="{sections}" as="section" iteration="iteration">
        <section id="{section.uid}" class="sections">
            <v:content.render pageUid="{section.uid}" />
        </section>
    </f:for>
 </v:menu>
`

![image](https://github.com/FluidTYPO3/vhs/assets/45423295/eb3566d5-906a-4989-8f48-f3c068ef2be9)
