### ISSUE TITLE
v:content.render with contentUids not working anymore. typo3 11, latest commit: 47be782

### ISSUE THREAD

**Issue by jgreiner** [FluidTYPO3/vhs#1868]
example: <v:content.render contentUids="{0:40}"/>
no error but also no content.
It works if I switch back to version 6.1.3

**Comment by NamelessCoder** [comment]
I am not able to reproduce this problem. Please re-check and if still not working for you, provide additional information about how to reproduce it.

**Comment by martin-git-kristensen** [comment]
in php 8.0.11 <v:content.render contentUids="{0:743}"/> works fine - but not in php version 8.028 
- I get in errorlog: Exception: PHP Warning: Undefined array key "tt_content:743" in /var/www/html/docs/typo3conf/ext/vhs/Classes/ViewHelpers/Content/AbstractContentViewHelper.php line 239, in file /var/www/html/docs/typo3/sysext/core/Classes/Error/ErrorHandler.php:137

**Comment by martin-git-kristensen** [comment]
in php 8.0.11 <v:content.render contentUids="{0:743}"/> works fine - but not in php version 8.028 BUT this is in the 6.1.3 version

**Comment by PLACEBOBRO** [comment]
This is also a problem in the dev-development branch. We are using this branch and no content is rendered.

**Comment by NamelessCoder** [comment]
I need additional information about how to reproduce the problem. In all of my tests, on all supported TYPO3 versions, content is rendered correctly when specifying which specific content UIDs to render.

**Comment by kraemer-igroup** [comment]
Hi there, I just had the same issue (TYPO3 12.4.4, PHP 8.2, vhs@dev) with an update project coming from TYPO3 8.7 (vhs 5.2.0). In my case I had to add the pageUid manually (`<v:content.render contentUids="{0:40}" pageUid="123"/>`) since the contentUids are taken from another page - but this seemed to work in older versions. The parameter "pageUid" is described as follows: _If set, selects only content from this page UID_

Maybe this helps.

**Comment by NamelessCoder** [comment]
> In my case I had to add the pageUid manually

That helped a lot. Solving another bug where `content_from_pid` would be ignored, meant that the content selection would always have a page UID either from TSFE or from the argument. The page UID used for selecting content would therefore never be zero, which in turn meant that any content element specified in `contentUids` would have to exist on the same page that was currently being rendered or on the page specifried as `content_from_pid` in the page record.
