### ISSUE TITLE
PHP Type error after upgrading to Typo3 11.5

### ISSUE THREAD

**Issue by olinox14** [FluidTYPO3/vhs#1869]
I just upgraded our Typo3 installation from version 10.4 to version 11.5 on a local server, and I get this error :

```
Cannot autowire service "FluidTYPO3\Vhs\ViewHelpers\Resource\CollectionViewHelper": argument "$collectionRepository" of method "injectCollectionRepository()" has type "TYPO3\CMS\Core\Collection\RecordCollectionRepository" but this class was not found.
```

VHS version is 6.1.3

Do you have an idea about this error?

**Comment by NamelessCoder** [comment]
Install extension `legacy_collections` until VHS 7.0 is released, or use VHS `dev-development`. The 6.1.x branch of VHS will no longer be updated.
