### ISSUE TITLE
v:content.render with slide="-1" does not work in version 6.1.3

### ISSUE THREAD

**Issue by raphael-ilea** [FluidTYPO3/vhs#1874]
Tested in both TYPO3 9.5.31 and 9.5.43 ELTS.

It only works when setting limit="0" or downgrading to 6.1.2.

Issue seems to come from the `if` statement in this file `Classes/Traits/SlideViewHelperTrait.php:L149`
```php
            if (0 !== $limit) {
``` 

In version 6.1.2 $limit is compared to `null` so this issue does not happen.

**Comment by Konafets** [comment]
I can confirm this issue with TYPO3 11.5. I got it working by adding `limit="0"` to the viewhelper.

**Comment by felixrupp** [comment]
I can confirm this issue with TYPO3 10.4.37. I got it working with using `slideCollect="1"`instead of `slide="-1"` in the ViewHelper.

**Comment by felixrupp** [comment]
`slideCollect` alone did not work in all of my columns, but I found a duplicate Issue: https://github.com/FluidTYPO3/vhs/issues/1844#issuecomment-1439934741 with a temporary workaround.

**Comment by cweiske** [comment]
This bug in 6.1.3 concerns the `v:page.resources.fal` view helper.
