### ISSUE TITLE
BUG: "Call to a member function getConfiguration() on null" after upgrading to version 7.0.0

### ISSUE THREAD

**Issue by cstrizzolo** [FluidTYPO3/vhs#1877]
After upgrading from version 6.1.3 to 7.0.0 on TYPO3 11.5.31, the following error appears in some unidentified cases and gets reported in the log:

Thu, 14 Sep 2023 12:43:11 +0200 [CRITICAL] request="b4b74da6a2ac6" component="TYPO3.CMS.Core.Error.ProductionExceptionHandler": Core: Exception handler (WEB: FE): Error, code #0, file /(...)/typo3conf/ext/vhs/Classes/Service/AssetService.php, line 131: Call to a member function getConfiguration() on null - {"mode":"WEB","application_mode":"FE","exception_class":"Error","exception_code":0,"file":"/(...)/typo3conf/ext/vhs/Classes/Service/AssetService.php","line":131,"message":"Call to a member function getConfiguration() on null","request_url":"https://www.example.com/","exception":null}

The getConfiguration function isn't used by any local extension on the involved site, thus the error should refer to something internal to the vhs 7.0.0 release itself, or in an interaction with one of the default system extensions of TYPO3 11.5.31.

**Comment by NamelessCoder** [comment]
@cstrizzolo Did you rememeber to flush the system caches via install tool, to ensure that the DI cache is rebuilt?

**Comment by cstrizzolo** [comment]
I apologize.
I had flushed just some of the caches, not all of them.
It seems to work after clearing all of the caches.
