### ISSUE TITLE
BUG: page.resources.fal does not slide in VHS 7.0.0

### ISSUE THREAD

**Issue by steffenmaechtel** [FluidTYPO3/vhs#1878]
**I have checked that the bug exists in the `dev-development` branch**
YES

**I have checked that there are no already open issues or recently closed issues about this bug**
YES

**Describe the bug**
We want to load media ressources from page. If current page has no media ressource, we want to slide up the page tree till root page. In old Version 6 this worked. Now after upgrade to 7.0.0 it stops sliding after current page and do not go the page tree up.

**To Reproduce**
1. Use View Helper and activate slide `<v:page.resources.fal table="pages" field="media" record="{data.uid}" as="media" limit="1" slide="10" slideCollect="false">`
2. Do not set a Media Ressource on current page, only on parent page
3. Open current page in Browser

**Expected behavior**
Should load parent page media if current page has no media

**Screenshots**

**Additional context**
`<v:page.resources.fal table="pages" field="media" record="{data.uid}" as="media" limit="1" slide="10" slideCollect="false">`

I think the fail is in `trait SlideViewHelperTrait`:

Current code, in Line 123:
```
$limitRemaining =- count($recordsFromPageUid);
```

Should be:
```
$limitRemaining -= count($recordsFromPageUid);
```

**Comment by NamelessCoder** [comment]
Nice catch, @steffenmaechtel - that looks like a typo!

Would you mind creating a pull request with that change?

**Comment by steffenmaechtel** [comment]
> Nice catch, @steffenmaechtel - that looks like a typo!
> 
> Would you mind creating a pull request with that change?

ok, i created a pull request: https://github.com/FluidTYPO3/vhs/pull/1879
