### ISSUE TITLE
BUG: v:page.menu.directory problem

### ISSUE THREAD

**Issue by burzaburzynski** [FluidTYPO3/vhs#1882]
TYPO3 v12.4.6 VHS 7.0.0

I have a problem after upgrading TYPO3 to v12 and VHS:

Error: The ViewHelper "<v:page.menu.directory>" could not be resolved. Based on your spelling, the system would load the class "FluidTYPO3\Vhs\ViewHelpers\Page\Menu\DirectoryViewHelper", however this class does not exist.

**Comment by NamelessCoder** [comment]
The correct VH name is `v:menu.directory`.
