### ISSUE TITLE
[REQUEST] : add "media" parameter for v:asset.style

### ISSUE THREAD

**Issue by ilomedia** [FluidTYPO3/vhs#190]
If i'm not mistaken the asset.style VH does not support the "media" parameter used in CSS to load a stylesheet depending on the hardware that renders it, this is especielly useful for a print template.

Is it possible to add this parameter?

**Comment by jousch** [comment]
Is there any update on that missing feature? The mentioned workaround isn't working anymore with `ext:vhs`.

**Comment by bjo3rnf** [comment]
What does

> The mentioned workaround isn't working anymore with ``ext:vhs``

mean exactly?

**Comment by jousch** [comment]
Actually it isn’t possible to use `<v:asset.style />` when I need the attribute `media="print“`

**Comment by bjo3rnf** [comment]
> Actually it isn’t possible to use `<v:asset.style />` 

Come on... Please be a little more specific. Errors? Exceptions? Explosions? Foobar?

;)

**Comment by NamelessCoder** [comment]
@jousch did you try the suggestion from @adick to use a "raw" asset with a manual tag?

https://github.com/FluidTYPO3/vhs/issues/190#issuecomment-20182041

I'm pretty sure that still works ;)
