### ISSUE TITLE
BUG: problem with php-warning in AbstractContentViewHelper in version 6.1.3 

### ISSUE THREAD

**Issue by Padina14** [FluidTYPO3/vhs#1900]
**I have checked that the bug exists in the `dev-development` branch**
yes

**I have checked that there are no already open issues or recently closed issues about this bug**
yes

**Describe the bug**
I got a exception about an php warning related to the index of an array.
I use PHP 8.2 , Typo3 11.5.34.

**To Reproduce**
I neede to install the attached patch to prevent this bug.  
[vhs_AbstractContentViewHelper.patch](https://github.com/FluidTYPO3/vhs/files/14341147/vhs_AbstractContentViewHelper.patch)

**Comment by Padina14** [comment]
Saver should be the following patch.
[vhs_AbstractContentViewHelper.patch](https://github.com/FluidTYPO3/vhs/files/14341675/vhs_AbstractContentViewHelper.patch)

**Comment by NamelessCoder** [comment]
This problem does not exist in `dev-development` and version 7.0+, see https://github.com/FluidTYPO3/vhs/blob/development/Classes/ViewHelpers/Content/AbstractContentViewHelper.php#L236. No further releases will be made in the 6.x branches so I suggest you upgrade VHS to the latest major version 7.0+ (which is compatible with your PHP and TYPO3 versions).

**Comment by Padina14** [comment]
The PHP-code in that place of the patch will cause an error. I added a screenshot from a sandbox for causing the same warning, which caused the exception in my case. 

PHP has changed its behavior in the newer versions. The error would caused in version 7.0 in the same way; or can you  guarantee, that the value `$GLOBALS['TSFE']->recordRegister[$parent]` is defined everytime?

![Bildschirmfoto 2024-02-20 um 14 22 29](https://github.com/FluidTYPO3/vhs/assets/63228213/8ccc0848-9ca1-4574-a744-f1f5d4547a70)

**Comment by Padina14** [comment]
Sorry. My Mistake. I havn't read your comment deeply and the code of the develop deeply enough. I am really sorry.

**Comment by NamelessCoder** [comment]
All good @Padina14 :)
