### ISSUE TITLE
 vhs 6.1.3 v:content.render slide not working

### ISSUE THREAD

**Issue by ako-3004** [FluidTYPO3/vhs#1904]
<v:content.render column="9" slide="-1" />

Slide functionality does not work anymore. Just Had a few content elements in column 9 on parent page, and empty output with this command on the parent and the child page. Removing slide="-1" causes the content is outputed on the corresponding page.

I have vhs 6.1.3 in TYPO3 v11.5.35

Found an fixed old 2016 issue about this, but better opened a new one...

**Comment by NamelessCoder** [comment]
VHS 6.1 is no longer maintained and will receive no further patches. The problem is fixed in VHS 7.x though - you must upgrade to VHS 7.x (which is compatible with your TYPO3 version).
