### ISSUE TITLE
BUG: missing int cast

### ISSUE THREAD

**Issue by simonschaufi** [FluidTYPO3/vhs#1909]
**I have checked that the bug exists in the `dev-development` branch**
Yes

**I have checked that there are no already open issues or recently closed issues about this bug**
Yes

**Describe the bug**
Missing int cast to compare uid with a potential string: https://github.com/FluidTYPO3/vhs/blob/development/Classes/ViewHelpers/Condition/Iterator/ContainsViewHelper.php#L132

**To Reproduce**

have this in a news template (needle is a string here!):
```html
<v:condition.iterator.contains needle="{overwriteDemand.categories}" haystack="{newsItem.categories}">
	<f:then>yes</f:then>
	<f:else>no</f:else>
</v:condition.iterator.contains>
```

**Expected behavior**
output yes but always no.

cast to needle to int as uid is always an int but needle can be a string as well (coming from fluid template)

**Comment by NamelessCoder** [comment]
Fix this quickly by casting: `{overwriteDemand.categories as int}`.

Side note: this condition would probably break or not work correctly; `{overwriteDemand.categories}` does not look like it would always contain a single value and needle must be a single value. If it works then that is by coincidence and you should extract/convert as needed to ensure it is always a single value, or use a different condition based on `iterator.intersect` to compare if iterators A and B have any elements in common.

**Comment by simonschaufi** [comment]
thanx
