### ISSUE TITLE
Weird behaviour of v:iterator.explode when using as-argument

### ISSUE THREAD

**Issue by tpinne** [FluidTYPO3/vhs#32]
I totally do not get, what the desired behaviour of lines 66-72 is if the view helper is used as follows:

``` html
<v:iterator.explode glue="-" content="a-b-c-d" as="var" />
```

because of the view helper code $contentWasSource stays obviously false which ends in an removed as-variable from templateVariableContext.
Is there something I do not get?

**Comment by mbonaker** [comment]
Seems to be broken again in 2017. Try this:

    {iter -> v:iterator.explode(content: 'referrer', glue: 'e', as: 'iter') -> v:format.json.encode()}

It should return `["r", "f", "rr", "r"]` according to @NamelessCoder (as I understand him) but it gives me `"referrer"`. I use VHS 4.2.0 on TYPO3 7.6.

Without `as` it works though:

    {v:iterator.explode(content: 'referrer', glue: 'e') -> v:format.json.encode()}

This gives the desired output but that obviously does not change the fact that `as` is broken.

**Comment by NamelessCoder** [comment]
I'm afraid you're misunderstanding what the "as" argument does. It *assigns a template variable that you can then use in the tag content*. However, your example is constructed in a way where you *use the return variable as input for another ViewHelper*. The short story is that this is not the correct way to use the "as" argument. Rather, you should exclude this argument - and the VH will then return an array that the other VH will use as input (value coming from renderChildren method).

This is why when you define your `content` to be `"referrer"` then that's what gets returned when you specify the `as` argument.

**Comment by NamelessCoder** [comment]
Issue locked (is 4 years old). If you're still facing problems which aren't stemming from incorrect usage, please open a new issue.
