### ISSUE TITLE
How get "title" of page from another page (levels pages) at tree pages?

### ISSUE THREAD

**Issue by typo3ua** [FluidTYPO3/vhs#343]
Hello, all!

I need get "title" from another page at tree pages or another levels pages.

For example:

```
<v:page.info field="title"  />
```

...returns title of the current page.

I need "title" parent page or specified level pages.

```
- Title level 0
- - Title level 1
- - - Title level 2
- - - - - Title level 3
```

For example: I need "title" from level "Title level 2"...

```
<v:page.info field="title" entryLevel="2" />
or 
<v:page.info field="title" levels="2" />
```

It would be nice to be able to obtain "title" page with any level at tree.

It is possible?

How do it?

**Comment by gutschik** [comment]
Since this issue here is the first result when googling for "fluid typo3 title of parent page" and I couldn't find any out-of-the-box solution for it, I'll paste my code for this issue here:

```
<v:page.breadCrumb levels="0" entryLevel="1" linkActive="FALSE" expandAll="FALSE" as="breadCrumbs">
  <f:for each="{breadCrumbs}" as="levelTitle" iteration="index">
    <f:if condition="{index.isFirst}">
      <h3>{levelTitle.title}</h3>
    </f:if>
  </f:for>
</v:page.breadCrumb>
```

**Comment by typo3ua** [comment]
Thanks, Guys!
