### ISSUE TITLE
hidePagesIfNotTranslatedByDefault ignored by vhs page.menu.directory viewhelper

### ISSUE THREAD

**Issue by Winddancer77** [FluidTYPO3/vhs#389]
Hi,

when configuring a page to hide none translated pages by setting "hidePagesIfNotTranslatedByDefault" to true, the VHS navigation viewhelper will ignore this server wide setting. 

It seems that according to your abstract class only page specific variables are checked.

It would be more than helpful to have VHS respect these settings, as TS menu items do.

kind regards

Sven

**Comment by mkrappitz** [comment]
This is again broken in current vhs master on TYPO3 CMS 7.6.5.
Using <v:page.menu levels="2" expandAll="1" entryLevel="0" /> renders all pages in a foreign language, even those not translated even though ['FE']['hidePagesIfNotTranslatedByDefault'] is set to 1.
Changing it to <f:CObject typoscriptObjectPath="lib.mainMenu" /> where lib.mainMenu is something like this all non translated pages in the foreign language disappear from the menu correctly:
lib.mainMenu = HMENU
lib.mainMenu {
    entryLevel = 0
    wrap = <ul>|</ul>
    1 = TMENU
    1.expAll = 1
    1.NO.linkWrap = <li>|</li>
    ...
}

**Comment by bjo3rnf** [comment]
Could you please try the current development branch of vhs. All menu viewhelpers have recently been refactored. The master branch is equal to the TER version, thanks.

**Comment by mkrappitz** [comment]
Thanks, but same error with the development branch. I also cleared all caches via install tool.

**Comment by bjo3rnf** [comment]
Ok, I'll have a look. Thanks for reporting.

**Comment by bjo3rnf** [comment]
Hi Matthias,

I pushed a fix to the development branch. Mind testing again?

Thanks in advance.

Cheers
Björn

**Comment by mkrappitz** [comment]
Fixed for me! Thank you so much!

**Comment by bjo3rnf** [comment]
Nice. Thanks for testing.
