### ISSUE TITLE
<v:page.menu> hideNonTranslated Bug

### ISSUE THREAD

**Issue by rorentz** [FluidTYPO3/vhs#485]
I  am using the newest version of the vhs. Everything is great, but the page.menu viewhelper seems just to ignore my settings. i have a menu that is translated, but on menu point i didn't translate and therefore does not need the point in the menu. The page.menu viewhelper seems to ignore that. 

config.sys_language_overlay = hideNonTranslated
config.sys_language_mode = strict

I always get rendered the default language title. Am i missing something? Any help would be great.

Best regards.
robsonrobi

**Comment by andyhausmann** [comment]
Hey @robsonrobi — i am currently running into the same behaviour. How did you manage this?

**Comment by robsonrobi** [comment]
I think i had to set the language behaviour in the install tool.

**Comment by andyhausmann** [comment]
Dude, thank you so much! You saved me tons of time. I was not aware of this option! 👯
