### ISSUE TITLE
v:if stack. How to ?

### ISSUE THREAD

**Issue by rob-ot-dot-be** [FluidTYPO3/vhs#493]
This one puzzles me:

what I need:
IF {dateObject} > {NowDateObject} AND {objecteValue} >  '1'
THEN: world domination

What I have  tried:
<v:if stack="{
0: '{translation.newsfrontendTranslationsDueDate -> f:format.date(format: 'd.m.Y')}',
1: '>',
2:'{now -> f:format.date(format: 'd.m.Y')}',
3:'AND',
4: '{translation.newsfrontendTranslationsStatus}',
5: '<',
6: '1'
}">

Where I ended : 
Misery :(

The examples here :https://github.com/FluidTYPO3/vhs/pull/401 
are way to abstract for my little brain.

Any help is appreciated

Tnx

**Comment by EvilBMP** [comment]
The standard fluid IfViewHelper also supports the boolean ! (NOT) Operator. How can I achieve this using the vhs IfViewHelper? The following variants are not working!

```html
<v:if stack="{0: value1, 1: '&&', 2: '!', 3: value2}">
```
```html
<v:if stack="{0: 'value1', 1: '&&', 2: '!', 3: 'value2'}">
```
```html
<v:if stack="{0: 'value1', 1: '&&', 2: '!value2'}">
```
```html
<v:if stack="{0: 'value1', 1: '&&', 2: !'value2'}">
```

Any help is highly appreciated.

**Comment by danilobuerger** [comment]
Maybe something like

```
<v:if stack="{0: 'value1', 1: '&&', 2: 'value2', 3: '==', 4: 'false'}">
```

**Comment by EvilBMP** [comment]
Nope, already tested. Results in:
```
array
  0 => string 'value1'
  1 => string '&&'
  2 => boolean false    // value2
  3 => string '=='
  4 => string 'false'
```
Evaluated right condition:
```
array
  0 => boolean false    // value2
  1 => string '=='
  2 => string 'false'
```
results in:
```
boolean false
```

**Comment by EvilBMP** [comment]
```html
<f:alias map="{foo: '{f:if(condition: \'!{value2}\', then: \'true\', else: \'false\')}'}">
    <v:if stack="{0: 'value1', 1: '&&', 2: 'foo'}">
    </v:if>
</f:alias>
```
Not that nice, but works...
