### ISSUE TITLE
[FEATURE] Add async="true" to v:asset.script

### ISSUE THREAD

**Issue by glucka** [FluidTYPO3/vhs#625]

**Comment by doerler** [comment]
@NamelessCoder 
Hello!
We were just looking for a possibility to include the async attribute into script tags and found this issue. Is there anything new conerning the project EXT:assets?

**Comment by cedricziel** [comment]
Hi @doerler ;

no-not really; Sorry.

**Comment by prookie** [comment]
Hi!

Why is not possible to add async/defer attributes to **standalone** assets at least? In this case there shouldn't be any problems concerning merging etc.

Can't believe this is not possible in 2017.

**Comment by danilobuerger** [comment]
@prookie Can't believe you comment on a 3-year-old *closed* issue. If you want it, why don't you submit a PR?

**Comment by prookie** [comment]
What's the matter concerning it is a "closed issue"? The problem is still present (my pull request may change that), and there is no comparable open issue about this.
