### ISSUE TITLE
v:page.header.meta only works for completely cached pages

### ISSUE THREAD

**Issue by lorenzulrich** [FluidTYPO3/vhs#696]
v:page.header.meta uses pageRenderer::addMetaTag. Meta tags added with this method are only respected if all elements of the page are cached. If you e.g. have one Extbase plugin with a non-cached method on the page, instead of pageRenderer::render, pageRenderer::renderPageWithUncachedObjects is used which doesn't render the meta tags.

**Comment by bjo3rnf** [comment]
Hi @all,

if anyone has knows a reliable way to determine if a page is cacheable or not please speak up. The pick is not _that_ easy as it seems ;)

Cheers
Björn

**Comment by coding46** [comment]
Could not reproduce the issue. Built a non-cacheable plugin and put it onto a page with all kinds of {v:page.header...} stuff. And all those tags get rendered.

CMS 6.2.14 / 7.2.4
VHS development

**Comment by NamelessCoder** [comment]
@coding to verify that closing is the right decision - did you also test this while you were **not** logged in to the BE (which would bypass caches and might give false positives)?

**Comment by coding46** [comment]
@NamelessCoder Yes, I did it in a private mode tab, so I wasn't logged into BE.

**Comment by NamelessCoder** [comment]
Excellent - that's all the test we need.

**Comment by lorenzulrich** [comment]
Just to let you know, I can still reproduce this. Didn't find out why yet.

**Comment by Juburin** [comment]
I can definitely reproduce this.
Using Typo3 6.2.21 and VHS 2.4.0
