### ISSUE TITLE
[FEATURE] filter by array in iterator.filter

### ISSUE THREAD

**Issue by Momodedf** [FluidTYPO3/vhs#731]
Hello,

I wanted to use iterator.filter with invert=1 to get some values out of an array.
But as i understand it can only filter 1 value. Is there any reason why filter can't be an array ?

I modified the filter function in the viewHelper like this : 
return is_array($filter) ? in_array($value, $filter) : ($value == $filter);
It does the job in my situation, I can provide a PR is you want.

Kind regards,
Fabien.

**Comment by NamelessCoder** [comment]
Closing this issue - continuing in the PR #751 :)
