### ISSUE TITLE
[BUG] v:media.files is not Array

### ISSUE THREAD

**Issue by typo3ua** [FluidTYPO3/vhs#743]
I have problem, I get string... I need Array
~~~
{f:for(each: '{v:media.files(path: 'files/png/', extensionList: 'png')}
~~~
Output:
name1.pngname2.pngname3.png
I need:
name1.png, name2.png, name3.png

What wrong?

**Comment by NamelessCoder** [comment]
Incorrect use of `f:for`; not a bug. Consider using the tag-based way and don't forget that you need an `as` argument.

Please ask this type of support question on IRC instead of creating bug reports.
