### ISSUE TITLE
"v:asset" and "f:for" in a couple.

### ISSUE THREAD

**Issue by typo3ua** [FluidTYPO3/vhs#745]
I have code:
~~~
<f:for each="{javascript}" as="script" iteration="iteration">
	<v:asset name="0" external="0" allowMoveToFooter="0" fluid="1" rewrite="0" standalone="1" variables="{_all}">
		<script type="text/javascript" src="{script.js.file}"></script>
	</v:asset>
</f:for>
~~~
Output:  Nothing

When I do so:
~~~
<f:for each="{javascript}" as="script" iteration="iteration">
	<v:asset name="0" external="0" allowMoveToFooter="0" fluid="1" rewrite="0" standalone="1" variables="{_all}">
		<f:debug><script type="text/javascript" src="{script.js.file}"></script></f:debug>
	</v:asset>
</f:for>
~~~
Output: 
![2014-12-28_211112](https://cloud.githubusercontent.com/assets/638022/5564672/01721388-8ed6-11e4-85c1-b68fe74f4da1.jpg)

What is wrong and why?
Can someone help me?

**Comment by NamelessCoder** [comment]
You are repeatedly assigning the same asset name and the name is invalid, which causes VHS to drop all but the last asset you define. In addition, the `external` and `fluid` arguments make no sense in this case since you are defining what is essentially a raw asset.
