### ISSUE TITLE
[HELP] Conditional comments - is there final solution?

### ISSUE THREAD

**Issue by zelcode** [FluidTYPO3/vhs#748]
Hi,
so how we can get this (or is this possible):

```html
<!--[if (gt IE 8) | (IEMobile)]><!-->
    <link href="global.css" rel="stylesheet" />
<!--<![endif]-->
<!--[if (lt IE 9) & (!IEMobile)]>
    <link href="old-ie.css" rel="stylesheet" />
<![endif]-->
```
There were several issues (500,455,295,288), but neither has final solution.

And one more similar, how to include font files and get that path in css files.

Regards.

Update: this link does not work:
https://fluidtypo3.org/blog/news/vhs-assets-the-crash-course.html

**Comment by xf-** [comment]
i don't think so - you can use v:page.header (should work).
A lot of people use modernizer or set a condition <html> or don"t give a s**t about old IEs or use a condition for TS.

**Comment by NamelessCoder** [comment]
I think the optimal solution if you *must* use VHS features for your asset, is to use `<v:asset name="xyz" standalone="TRUE"><!-- insert conditionals and full <script> here</v:asset>`. This should add the code as an asset, but of course you cannot use any script merging functions here.
