### ISSUE TITLE
FalViewHelper throws a exception if a resource does not exist 

### ISSUE THREAD

**Issue by loco8878** [FluidTYPO3/vhs#762]
This should not be passed.

**Comment by cedricziel** [comment]
Thank you for reporting.

1. Which class exactly?
2. Retrieving a non existent resource provokes a typo3 core exception, could it be you're hitting that edge?

**Comment by loco8878** [comment]
Class: FluidTYPO3\Vhs\ViewHelpers\Resource\Record\FalViewHelper
Method: getResource or getResources

It is true that this exception comes from the core file handling.
But this should not be passed on if I use a view helper.
