### ISSUE TITLE
Published pages that are moved in draft workspace disappear in navigation

### ISSUE THREAD

**Issue by giwdulnevs** [FluidTYPO3/vhs#763]
When moving a published page in draft workspace to a different location, everything looks fine in the backend. In the frontend preview though, the moved page is not shown in the navigation.

Steps to reproduce:
* Create a page in Live workspace
* Go to draft workspace and move the page to another location
* The moved page will not show in the navigation in the workspace preview

This bug occured with TYPO3 6.2.9 and using VHS for menu rendering. In another TYPO3 6.2.9 installation that does not use VHS the problem did not occur, so my guess is that it is related to VHS menu rendering.

**Comment by xf-** [comment]
needs testing

**Comment by coding46** [comment]
Confirmed

CMS 6.2.* / 7.4 
VHS development
