### ISSUE TITLE
[FEATURE] v:page.header.canonical - href

### ISSUE THREAD

**Issue by ste101** [FluidTYPO3/vhs#764]
It would be great if I could also set an individual href with f:uri viewhandler.
e.g.
```<v:page.header.canonical href="{f:uri.action(action: 'show', pageUid: '13', arguments: '{projekt : projekt}')}" />```

**Comment by xf-** [comment]
Good idea to be able to set a individual url

**Comment by NamelessCoder** [comment]
Rejected a while ago because alternatives with equal complexity and performance exists in the shape of `v:page.header` - see https://github.com/FluidTYPO3/vhs/pull/765.
