### ISSUE TITLE
Make v:page.resources.fal or v:page.resources content-slide enabled

### ISSUE THREAD

**Issue by fgerards** [FluidTYPO3/vhs#767]
Afaik vhs doesnt support content-sliding for page-ressource files, which is a pretty core-feature of typoscript and is used in a lot of projects. 
It would be nice to add the same functionality like for the content-render viewhelpers in that viewhelper-family

**Comment by NamelessCoder** [comment]
Hi @fgerards - we have an open pull request for this (and other FAL-related ViewHelpers). It's a fairly complicated matter.

Follow the discussion at https://github.com/FluidTYPO3/vhs/pull/679 :)
