### ISSUE TITLE
content_fallback not working

### ISSUE THREAD

**Issue by hhoechtl** [FluidTYPO3/vhs#774]
It seems like content_fallback is not working. I tried the following settings with the current intropackage and there it worked as expected.
```
config {
  sys_language_uid = 0
  language = de
  locale_all = de_DE.UTF-8
  htmlTag_langKey = de
  sys_language_overlay = 1
  sys_language_mode = content_fallback; 0
}
[globalVar = GP:L=1]
  config {
    sys_language_uid = 1
    language = en
    htmlTag_langKey = en
    locale_all = en_GB.UTF-8
  }
[end]
```

When switching to L=1 I only see the translated content elements and the content elements with language = all. But the fallback doesn't work.

**Comment by NamelessCoder** [comment]
This is, unfortunately, a core bug that has been around for no less than 8 (!) years.

You can find a **heap** of additional information and issues here: https://forge.typo3.org/issues/19114

**Comment by hhoechtl** [comment]
Actually because this is only a problem when using VHS v:content.render it don't think so. You can try out the difference with the workaround I've submitted to the [library](https://fluidtypo3.org/library/code-examples.html?tx_fluidshare_display%5Bgist%5D=22&tx_fluidshare_display%5Baction%5D=display&tx_fluidshare_display%5Bcontroller%5D=Gist&cHash=6b3609bc9ec341cca2a3965cfe3b8899)
