### ISSUE TITLE
additionalAttributes in v:page.link

### ISSUE THREAD

**Issue by typo3ua** [FluidTYPO3/vhs#781]
Hello, all!
I have problem with "additionalAttributes" in <v:page.link>
I added new attribute in <v:page.link>
~~~
additionalAttributes="{data-toggle: '{f:if(then: \'dropdown-toggle\', condition: \'{menu.hasSubPages} == 1\')}'}"
~~~
But the attribute is displayed regardless of whether it is empty or not.

**Comment by NamelessCoder** [comment]
This is normal Fluid behavior - and not something we can control. It applies to each and every TagBasedViewHelper in Fluid and any third-party extension including VHS. The specific reason for this behavior is:

* The `additionalAttributes` parameter is handled by Fluid itself (see TagBuilder).
* The value is passed directly from ViewHelper arguments.
* Fluid's TagBuilder does not care if a value is empty or not.

Getting around this behavior involves trimming the array values that are empty, which is something we cannot implement in VHS without potentially breaking a **lot** of running sites. Neither will it, I suspect, be possible in Fluid itself.

You can use the following ways to get around this:

* Build your additional attributes array using a custom ViewHelper or in a controller action and remove empty values. Useful for single or multiple additional attributes alike.
* Extend the `f:if` to return the entire `additionalAttributes` array in `then` case; useful if this is the only additional attribute you add, but not useful if you have multiple attributes.
* Create a custom ViewHelper that extends the original one but overrides the `render()` method so you can process the `additionalAttributes` array before you pass it to TagBuilder.
