### ISSUE TITLE
className must not start with a backslash

### ISSUE THREAD

**Issue by Danny-P** [FluidTYPO3/vhs#782]
Hi,
I'm using Typo3 7.1 and vhs 2.2.0 in a multisite installation. 
I tried to create a new backend User Group at the top root level: 
Step into Web => List and than create at the top root level a new backend usergroup. 
After saving the new group I get the error: 

    $className "\FluidTYPO3\Vhs\Service\AssetService" must not start with a backslash.

Best regards
Daniel

**Comment by cedricziel** [comment]
Have you tried the latest git revision? @liayn contributed a good amount of code to improve compatibility. Release is coming soon!

**Comment by Danny-P** [comment]
Works fine! With the new release I don't have any errors.
Thank you very much!
