### ISSUE TITLE
FAL Image in Preview

### ISSUE THREAD

**Issue by mithri** [FluidTYPO3/vhs#785]
Hi guys,

this code is not working anymore:

    <f:section name="Preview">
	
        <f:for each="{v:content.resources.fal(field: 'file')}" as="images">
            <v:resource.image identifier="{images.id}"  width="125c"/>
       </f:for>
    </f:section>

With older version of flux and vhs the image rendering was correct, now i get only the text "Array" as output in the Backend.

Can someone help pls?

Thanks
Tobias

**Comment by vergissberlin** [comment]
**Try this:**
```html
  <strong>
        <f:for each="{v:content.resources.fal(field: 'imagesFal')}" as="imageFal">
            <f:if condition="{imageFal.url}">
                <img src="<v:format.replace substring=".." content="{f:uri.image(src: '{imageFal.id}', maxHeight: '100', treatIdAsReference: true)}" replacement="" />" />
            </f:if>
        </f:for>
```

**Hint**
In the Backend you are in the subdirectory "typo3".

André

**Comment by cedricziel** [comment]
What version of vhs are you referring to?

If you get back an array, you most probably have a syntax error somewhere.

Can you try the following? And of course André is right with the relative path. Be sure to inspect the tag.

```xml
<f:section name="Preview">

    <f:for each="{v:content.resources.fal(field: 'file')}" as="image">
        <v:resource.image treatIdAsReference="TRUE" src="{image.uid}"  width="125c"/>
   </f:for>
</f:section>
```

**Comment by mithri** [comment]
thanks Andre, your code is working.

@cedricziel: I tried your code before, it is not working. I am using vhs 2.3.0 in T3 6.2.10

**Comment by cedricziel** [comment]
Great. Thx for following up!

**Comment by ste101** [comment]
v:resource.image needs the attribute 'identifier' not 'src'.
```<f:for each="{v:content.resources.fal(field: 'file')}" as="image">
        <v:resource.image treatIdAsReference="TRUE" identifier="{image.uid}"  width="125c"/>
</f:for>```

**Comment by DenisMir** [comment]
@cedricziel I can confirm that your code is not working with the latest vhs release. Even when using `identifier` instead of `src` I'm getting `Array` back. 

Here is my example: 

```
      {v:content.resources.fal(field: 'content.image') -> v:iterator.first() -> v:variable.set(name: 'image')}
      {v:resource.image(identifier: '{image.uid}',
                        treatIdAsReference: 'TRUE'
                        title: '{image.title}',
                        alt: '{image.alternative}',
                        width: '{f:if(condition: settings.width, then: settings.width, else: NULL)}',
                        height: '{f:if(condition: settings.height, then: settings.height, else: NULL)}')}
```
