### ISSUE TITLE
v:resource.image strange behavior FAL

### ISSUE THREAD

**Issue by DenisMir** [FluidTYPO3/vhs#808]
I recognized some strange behavior with `v:resource.image` when trying to render a fal image. 

I just wanted to have a content element that renders one fal image. 

Here is the configuration section: 

```html
  <f:section name="Configuration">
    <flux:form id="image">
        <flux:field.inline.fal name="content.image" multiple="false" />
    </flux:form>
  </f:section>
```

And then I'm trying to render the image tag to the page like this: 

```html
  <f:section name="Main">
    <div class="content-item image">
      <v:resource.image identifier="{v:content.resources.fal(field: 'content.image') -> v:iterator.first()}" />
    </div>
  </f:section>
```

The problem is that `v:resource.image` outputs only the word _Array_. I'm not quite sure if I'm using the tag correctly (especially in combination with the fal resource) but some clarification would be great.

Something like this does work to output the image: 

```html
  <f:section name="Main">
    <div class="content-item image">
      {v:content.resources.fal(field: 'content.image') -> v:iterator.first() -> v:variable.set(name: 'image')}
      {f:image(src: '{image.id}', treatIdAsReference: true)}
    </div>
  </f:section>
```

It would be great to know the difference between `f:image` and `v:resource.image` and when to use one over the other.

**Comment by NamelessCoder** [comment]
Mistake here is that `{v:content.resources.fal(field: 'content.image') -> v:iterator.first()}` returns an array, exactly as your last example respects. You can either chain `->v:iterator.extract()` or assign a temporary variable (which is an array!) that you can then read from.

`v:resource.image` will *extract* the image references from IRRE and render them. `f:image` cannot extract the reference when the field is IRRE - it only accepts already extracted references; there, you must load the FAL records through other means (like VHS or a controller action that assigns template variables). That's the difference and indeed the reason VHS's resource ViewHelpers were invented!

**Comment by DenisMir** [comment]
@NamelessCoder Thank you very much for your explanation.

**Comment by galoppi** [comment]
if you add `treatIdAsReference="0"` then it works as in earlier versions:
`<v:resource.image identifier="{v:content.resources.fal(field: 'image') -> v:iterator.extract(key: 'id') -> v:iterator.first()}" treatIdAsReference="0" maxWidth="150" />`

**Comment by coding46** [comment]
Can't reproduce the behaviour described in last comment.

In both cases the image gets rendered correctly.

CMS 7.4.0
VHS development

@NamelessCoder Reason for reopening the issue?

**Comment by NamelessCoder** [comment]
Needed to determine reproducibility - so that's exactly what you've done. Thanks! :)
