### ISSUE TITLE
v:iterator.random subject="{elements}" as="element" > error in VHS 2.3.1

### ISSUE THREAD

**Issue by j-lang** [FluidTYPO3/vhs#811]
After updating VHS 2.2.0 to 2.3.1 the iterator.random viewhelper 

> v:iterator.random subject="{elements}" as="element" 

produces an error
> #1253036401: Argument "subject" has already been defined, thus it should not be defined again.

in:
>TYPO3\CMS\Fluid\Core\ViewHelper\AbstractViewHelper::registerArgument("subject", "mixed", "The subject Traversable/Array instance from which to select a random element", boolean, NULL)

I cannot find changes in the documentation for this viewhelper.

**Comment by NamelessCoder** [comment]
Likely caused by reflection cache not being cleared. The base class and trait implementation was changed - this has no impact on the documentation for the ViewHelper but it does depend on a properly cleared cache to rebuild the reflections.
