### ISSUE TITLE
v:page.link creates an anchor tag with no content for non translated pages

### ISSUE THREAD

**Issue by Ghaniball** [FluidTYPO3/vhs#814]
The href attribute from anchor tag is properly filled.

**Comment by bjo3rnf** [comment]
Hi @Ghaniball,

this works as expected for me. How does your TypoScript language configuration look like?

**Comment by Ghaniball** [comment]
Hi Bjorn,

my typoscript settings from TypoScript Object Browser
[sys_language_uid] = 0
[sys_language_overlay] = 1
[sys_language_mode] = content_fallback
[language] = de
[locale_all] = de_DE.UTF-8

for L=1

[sys_language_uid] = 1
[sys_language_overlay] = 1
[sys_language_mode] = content_fallback
[language] = en
[locale_all] = en_US.UTF-8
[htmlTag_setParams] = lang="en" dir="ltr" class="no-js"

I 99% sure they are alright.

I think problem is here https://github.com/FluidTYPO3/vhs/blob/development/Classes/ViewHelpers/Page/LinkViewHelper.php#L133-L138
Instead of "else" it will be better to put a condition like that
if (empty($title))

This way if there is no page title for current language it will fallback to original one.
