### ISSUE TITLE
v:resource.record.fal and v:content.resources.fal don't respect workspace settings.

### ISSUE THREAD

**Issue by JostBaron** [FluidTYPO3/vhs#817]
Not sure if it introduces problems, but replacing the current `getResources()`-method in `Classes/Resource/Record/FalViewHelper` with this one does the trick for me (in my limited examples):

	public function getResources($record) {
		$sqlTable = $GLOBALS['TYPO3_DB']->fullQuoteStr($this->getTable(), 'sys_file_reference');
		$sqlField = $GLOBALS['TYPO3_DB']->fullQuoteStr($this->getField(), 'sys_file_reference');

		// This branch is new
		if (isset($record['t3ver_oid']) && 0 != $record['t3ver_oid']) {
			$sqlRecordUid = $GLOBALS['TYPO3_DB']->fullQuoteStr($record['t3ver_oid'], 'sys_file_reference');
		}
		else {
			$sqlRecordUid = $GLOBALS['TYPO3_DB']->fullQuoteStr($record[$this->idField], 'sys_file_reference');
		}

		$res = $GLOBALS['TYPO3_DB']->exec_SELECTquery('uid', 'sys_file_reference', 'deleted = 0 AND hidden = 0 AND tablenames = ' . $sqlTable . ' AND fieldname = ' . $sqlField . ' AND uid_foreign = ' . $sqlRecordUid, '', 'sorting_foreign');

		$resources = array();
		while ($row = $GLOBALS['TYPO3_DB']->sql_fetch_assoc($res)) {
			$resources[] = $this->getResource($row['uid']);
		}

		return $resources;
	}

I'm not sure if the field name `t3ver_oid` can be different, and where I would find it if necessary.

**Comment by xf-** [comment]
needs testing

**Comment by NamelessCoder** [comment]
Pull request submitted and is under review. Thanks for reporting and suggesting patch, Jost!
