### ISSUE TITLE
PdfThumbnailViewHelper extends ImageViewhelper (with a lowercase h)

### ISSUE THREAD

**Issue by wazum** [FluidTYPO3/vhs#820]
Fatal error: Class 'FluidTYPO3\Vhs\ViewHelpers\Media\ImageViewhelper' not found in /var/www/typo3conf/ext/vhs/Classes/ViewHelpers/Media/PdfThumbnailViewHelper.php on line 24

**Comment by bjo3rnf** [comment]
Fixed in current development branch. I wonder which case-insensitive-filesystem-user is responsible for this. Ts, ts, ts.
