### ISSUE TITLE
Form / SelectViewHelper

### ISSUE THREAD

**Issue by rafu1987** [FluidTYPO3/vhs#822]
This is page is broken :(

https://fluidtypo3.org/viewhelpers/fluid/master/Form/SelectViewHelper.html

**Comment by NamelessCoder** [comment]
Sorry about that, but the documentation that is being rendered is extracted from the `TYPO3\CMS\Fluid\ViewHelpers\*` classes and is not maintained by us. The reason it does not render correctly is the core's obsession with the RST format (which mixes in HTML...) that requires additional components for rendering and really doesn't fit well in class doc comments. What you are seeing there is misrendered HTML-in-RST and a fix would be to correct the class doc comment's use of HTML tags. Someone put an un-escaped `<select>` in there and thought it would be alright.

It wasn't.
