### ISSUE TITLE
<v:page.menu> do not display shortcut's subpages

### ISSUE THREAD

**Issue by kaolol** [FluidTYPO3/vhs#823]
This menu http://bit.ly/1Fjgv05 line 12 do not display shortcut's subpages. Is it normal ? Any way to fix it ?
I thing I have tried everything documented in 
All the best,
Laurent

**Comment by kaolol** [comment]
OK,  I'll wil update VHS form github before asking question next time ;)

**Comment by julianxhokaxhiu** [comment]
@kaolol can I ask you how you fixed it? I'm currently using the version 2.3.2

**Comment by kaolol** [comment]
It was a bit strange...
I've updated VHS. 
Then downgrade to previous version

**Comment by julianxhokaxhiu** [comment]
Thank you :) The problem was not this extension (shortcuts are working OOB) but template organization in the project where I was working on :D So no need to do special tricks
