### ISSUE TITLE
[BUG] Security / AllowViewHelper

### ISSUE THREAD

**Issue by AMTkkasprzyca** [FluidTYPO3/vhs#827]
Hello

I have tried to use this viewhelper today with arguments `backendUser` and `admin` (separately). 

Problem with `admin` - I tested that with `TRUE`, `true`, `1`, `FALSE`, `false` and `0`. Each time viewhelper has shown content from `f:then` node.

Problem with `backendUser`:

I tried to use viewhelper in this way
````
<v:security.allow backendUser="26">
        <f:then>secured content</f:then>
        <f:else>unsecured content</f:else>
</v:security.allow>
````
but it always renders content from `f:else` node. After small research I probably found problem in `assertBackendUserLoggedIn` function which is placed in `AbstractSecurityViewHelper` lines 196-206. Comparison `$currentBackendUser['uid'] === $backendUser` breaks because `$currentBackendUser['uid']` is integer type and `$backendUser` - string type. I don't know if there are some problems with others arguments because I didn't test all of them.

I checked this with TYPO3 6.2.9, VHS 2.3.1 and PHP 5.5.6

**Comment by bjo3rnf** [comment]
Hi @AMTkkasprzyca,

thanks for reporting and tracking down the cause. 

Cheers
Björn
