### ISSUE TITLE
'allowMoveToFooter' is deprecated, update to 'movable'

### ISSUE THREAD

**Issue by Outdoorsman** [FluidTYPO3/vhs#829]
'allowMoveToFooter' is deprecated according to the changlog but it's everyone is still using it because the auto-generated documentation on FluidTYPO3 doesn't reflect that. Please update it so that it's noted correctly on FluidTYPO3 about 'movable'.
https://fluidtypo3.org/viewhelpers/vhs/development/AssetViewHelper.html

**Comment by DenisMir** [comment]
@Outdoorsman But when trying to use `movable` inside a `<v:asset.script ../>` script helper I'm getting `Argument "movable" was not registered.`. So I think the new argument is not registered in the viewhelper itself. If you look right here this is the case: https://github.com/FluidTYPO3/vhs/blob/development/Classes/ViewHelpers/Asset/AbstractAssetViewHelper.php
