### ISSUE TITLE
OrViewHelper: LLL:label syntax not working

### ISSUE THREAD

**Issue by smichaelsen** [FluidTYPO3/vhs#834]
As far as I understood it you can use the alternative parameter in three ways:

* Provide the plain alternative string
* Provide a locallang reference in the form `LLL:EXT:myext/Resources/Private/Language/locallang.xlf:somelabel`
* Provide a locallang reference in the form `LLL:somelabel`

The last one doesn't work at the moment. But changing the `!==` to `===` in the following line makes it work for me. https://github.com/FluidTYPO3/vhs/blob/development/Classes/ViewHelpers/OrViewHelper.php#L59

**Comment by bjo3rnf** [comment]
Hi @smichaelsen,

you're right. Fixed by direct push to development branch.

**Comment by smichaelsen** [comment]
Thanks!
