### ISSUE TITLE
<page.menu.list> does't respect the typo3 "Disabled" parameter

### ISSUE THREAD

**Issue by f000** [FluidTYPO3/vhs#836]
typo3 7.2.0, vhs 2.3.2

page.menu.list viewhelper is showing pages which are disabled e.g.:

page uid 1 disabled=0
page uid 2 disabled=1
```
<v:page.menu.list pages="1,2" showHiddenInMenu="1" />
```
vhs output:
```
<ul>
    <li><a href="?id=1" title="Home">Home</a></li>
    <li><a href="?id=2" title="Kontakt">Kontakt</a></li>
</ul> 
```

**Comment by NamelessCoder** [comment]
When you say "disabled", do you mean:

1. Hide in menu (column: nav_hide)
2. Hidden (column: hidden)
3. Deleted (column: deleted)
4. Start/endtime (columns: starttime, endtime)
5. Frontend user permissions (column: fe_group)

Which one it is will very much have an influence on whether or not "showHiddenInMenu" has any effect. Hint: if "1" is your case then your output is expected, by design. If it is any of the other cases and your menu items still display then it indicates a bug.

**Comment by f000** [comment]
oops sorry I meant "Hidden (column: hidden)" :)

**Comment by NamelessCoder** [comment]
Thanks :)

If anyone picks this up, it's very likely either a wrong "showHidden" parameter for PageSelect or missing use of enableFields when constructing a query.

**Comment by bjo3rnf** [comment]
I'll have a look at it.

**Comment by bjo3rnf** [comment]
Ok. enableFields is used but it relies on ``$GLOBALS['TSFE']->showHiddenPage`` which is TRUE for active backend sessions in my case. How should this be handled? Forcibly override and never show hidden pages in menus or re-activate the viewhelper argument?

**Comment by f000** [comment]
That's weird... ```$GLOBALS['TSFE']->showHiddenPage``` is TRUE by default on all my instalations of 6.2 and 7.2... I never seen and used this parametr...

Anyway,  I can't see any use case for this current ```<page.menu.list>``` behaviour because if you log out from the backend, you can't use the admin Preview mode for hidden pages... so menu items for hidden pages will be shown but those pages will be unavailable (404 or 503 error).

BTW old typoscript HMENU object supports only ```nav_hide``` and there is no way to show ```hidden``` pages even in the admin preview...

**Comment by bjo3rnf** [comment]
> BTW old typoscript HMENU object supports only nav_hide and there is no way to show hidden pages even in the admin preview...

IMHO we should mimic the original behavior. What do you think @NamelessCoder and @f000?

**Comment by f000** [comment]
@bjo3rnf: go for it :)

**Comment by cedricziel** [comment]
Merged, as I'm with @bjo3rnf. This should mimic core behaviour, as that's what people expect. Thx to the three of you :)

**Comment by bjo3rnf** [comment]
Thank you Sir :)
