### ISSUE TITLE
<v:asset.style> "rewrite" agument is not working as expected

### ISSUE THREAD

**Issue by f000** [FluidTYPO3/vhs#837]
typo3 7.2.0, vhs 2.3.2
```xml
<f:section name="BackgroundImage">
   <v:asset.style rewrite="0" overwrite="0" standalone="0" name="{id}-{serial}-lg">
       #{id}-{serial}{
           background-image: url('<f:format.raw>{path}</f:format.raw>/<f:format.raw>{imageLarge}</f:format.raw>');
       }
   </v:asset.style>
</f:section>
```
URLs in generated CSS are rewritten

e.g. background-image: url('vhs-assets-css-a2bd885e846293766c2d82c9ab76bb0f.jpg');

**Comment by bjo3rnf** [comment]
To have that in a single file with the provided name set ``standalone="1"``

**Comment by f000** [comment]
With  ```standalone="1"``` no css file is generated and css styles are included directly in ```<head>```... and  background-image: url() images are still rewritten :( 

See:

```
<style type="text/css">
           #carousel-hp-1{
               background-image: url('vhs-assets-css-f4009aa10c542b963ac2b2c6d8ff49f0.jpg');
           }
</style>
```

For more clarification, for  ```{path}``` set to ```fileadmin/somepath/``` and  ```{imageLarge}``` to  ```somefile.jpg```  I'm expecting output like this:

```
<style type="text/css">
           #carousel-hp-1{
               background-image: url('fileadmin/somepath/somefile.jpg');
           }
</style>
```

not  ...```url('vhs-assets-css-f4009aa10c542b963ac2b2c6d8ff49f0.jpg');```...

BTW I'm using this BackgroundImage Partial in fluxcontent element...
