### ISSUE TITLE
<v:asset.style> "standalone" agument is not working as expected

### ISSUE THREAD

**Issue by f000** [FluidTYPO3/vhs#838]
typo3 7.2.0, vhs 2.3.2
```xml
<f:section name="BackgroundImage">
   <v:asset.style rewrite="0" overwrite="0" standalone="0" name="{id}-{serial}-lg">
       #{id}-{serial}{
           background-image: url('<f:format.raw>{path}</f:format.raw>/<f:format.raw>{imageLarge}</f:format.raw>');
       }
   </v:asset.style>
</f:section>
```

generated CSS file is not concated with main typo3 css file

e.g.

```xml
<link rel="stylesheet" type="text/css" href="/typo3temp/compressor/merged-27711eba182e48fd566161129e977365.1432248666.css" media="all">
<link rel="stylesheet" href="/typo3temp/vhs-assets-carousel-hp-1-lg-carousel-hp-2-lg-carousel-hp-3-lg.1432250089.css" />
```

**Comment by NamelessCoder** [comment]
This is by design. Unless the asset was included with VHS it won't be processed by VHS - and VHS assets will always come after those added by TYPO3 (with one exception: TYPO3 assets added to document footer come AFTER VHS assets added in the header - obviously).

So that's all in order ;)

**Comment by f000** [comment]
thank you anyway... this is very exciting way how to generate css background images from typo3 elements!
