### ISSUE TITLE
page.menu.sub only works when parent view helper does not set "as"

### ISSUE THREAD

**Issue by pkerling** [FluidTYPO3/vhs#845]
Using page.menu.sub for recycled submenu rendering only works when the parent page.menu instance uses `menu` as `as` argument and `rootLine` as `rootLineAs` argument because those values are hardcoded to be removed from the template variable container in the `$backups` member variable by `backupVariables`. If they are not removed, a duplicate variable exception is thrown and the menu is not displayed.

**Comment by pkerling** [comment]
My "quick fix" was to insert `$this->backups = array($this->arguments['as'], $this->arguments['rootLineAs']);` into `render()`. It's as non-invasive as possible. I'll open a pull request if you think it's an acceptable solution. I'm open to implementing it differently otherwise :)

**Comment by NamelessCoder** [comment]
Sounds like the correct way to tackle this one; assuming that by "insert" you mean to replace all hardcoded references to the `menu` and `rootLine` names with the proper `$this->arguments[]` reference so we don't end up cleaning out template variables that don't exist. Anyway, I'm pretty sure you've got the angles covered on that one ;)
