### ISSUE TITLE
render.uncache does not respect partialRootPath

### ISSUE THREAD

**Issue by ipf** [FluidTYPO3/vhs#849]
In an extension I have explicitly set the partialRootPath to a non-default location. 
Using the v.render.uncache viewHelper to render a partial does - contrary to the f:render viewHelper not respect the set partialRootPath

**Comment by p2media** [comment]
We are using `partialRootPaths.0 = ...` and having the same issue.

**Comment by xf-** [comment]
please test again we changed a default setting 10 to 0 in flux.

**Comment by NamelessCoder** [comment]
Taking a leap of faith here and assuming this is indeed caused by the index Flux uses. In which case this will be fixed next time you pull from development ;)

Thanks for reporting guys!

**Comment by saphrus** [comment]
Can anyone confirm this issue being fixed?
I just ran into the same problem with TYPO3 6.2.25 and VHS 2.4
