### ISSUE TITLE
v:media.exists doesn't support compiled rendering

### ISSUE THREAD

**Issue by smichaelsen** [FluidTYPO3/vhs#851]
The `Media\ExistsViewHelper` doesn't implement static functions for compiled rendering, but extends the `AbstractConditionViewHelper` which already supports compiled rendering. This makes the ViewHelper unfunctional as soon as fluid templates are cached.

**Comment by smichaelsen** [comment]
For me it works like this: https://gist.github.com/smichaelsen/e2c6c73cb3f0129c6aab

**Comment by xf-** [comment]
Can you provide a PR or show a diff.

**Comment by jmverges** [comment]
@xf- Here is the diff: https://gist.github.com/jmverges/4952d9bbc4ebdbfb5823 does it makes sense?

**Comment by smichaelsen** [comment]
The diff looks good.

The problem occurs with TYPO3 7 only, starting with this commit: https://github.com/TYPO3/TYPO3.CMS/commit/1beb07f03e0dd9316f8bb96d8ef2a75803cda69d

You can test the VH like this:
`<v:media.exists file="path/to/some/image.jpg">Yes it exists</v:media.exists>`

The VH will work properly on the first call but as soon as the fluid is cached it will be called statically (because its parent AbstractConditionViewHelper implements the `CompilableInterface`) and the condition will be evaluated with `::evaluateCondition()`. That's why the functionality has to be moved there.

**Comment by jmverges** [comment]
"The VH will work properly on the first call" It is not working for me on the first call
