### ISSUE TITLE
[FEATURE] Add viewhelper for cropped images in TYPO3 7.3.x

### ISSUE THREAD

**Issue by bjo3rnf** [FluidTYPO3/vhs#853]
TYPO3 7.3.x introduces image cropping in the backed via UI. Requirement for a new viewhelper or an extension of the existing to render cropped images should be determined.

**Comment by featdd** [comment]
As I understand it correctly there is no need for a "cropped image" viewhelper. The crop settings are saved in "sys_file_reference" and so you can access and pass them through to the fluid image viewhelper.
Example:
```PHP
<f:for each="{v:content.resources.fal(field: 'images')}" as="image">
    <f:image crop="{image.crop}" treatIdAsReference="true" src="{image.id}" alt="{image.alt}" title="{image.title}" />
</f:for>
```

**Comment by bjo3rnf** [comment]
Thanks for investigating and the example.

**Comment by cedricziel** [comment]
Can you pull request those as doc-changes to the existing media viewhelprs?

Cheers!

**Comment by featdd** [comment]
What doc changes do you mean?

**Comment by cedricziel** [comment]
I thought about adding an additional doc-string. But You're right.
