### ISSUE TITLE
render.request view helper does not take pageUid into account

### ISSUE THREAD

**Issue by netzloesungen** [FluidTYPO3/vhs#856]
Hi guys,

pageUid is documented as a legitim parameter to v:render.request but the class just does not use it. It would be quite useful to be able to set the request pageUid.

Thx,

Andreas

**Comment by xf-** [comment]
confirmed - is a argument and only usage is a unset.

**Comment by jmverges** [comment]
Hi @netzloesungen, 

Taking a look to the history of this viewhelper $pageUid was never used. 

Could you explain to us in which situation pageUid could be useful? 
Are you calling some action that is using something like $pageid = intval($GLOBALS['TSFE']->id); inside it? did you try to set the pageUid as part of $arguments? 

I'm trying to understand the scenario.

**Comment by jmverges** [comment]
After discuss it, we decided to remove this unused argument, @netzloesungen let us now more about the scenario and maybe we can suggest to you some solution

**Comment by netzloesungen** [comment]
Hi,

as far as i can remember it used it in an multi-tree typo3 installation and just wondered where the typoscript config for the rendered plugin is taken from (template of the root of tree A oder tree B?).  

regards,

Andreas

**Comment by NamelessCoder** [comment]
Hi Andreas,

TypoScript is resolved using the standard Extbase logic which when you are in BE context will resolve *the first created root TypoScript template only, unless there is a specific page as context*. You can check out the source code of TYPO3's BackendConfigurationManager to see how that logic is created.

**Comment by netzloesungen** [comment]
>  unless there is a specific page as context

thx for the info. i thought of the pageUid to be there for that reason. but i just was wrong :)
