### ISSUE TITLE
plugin.tx_vhs.settings.asset leads to corrupt style element

### ISSUE THREAD

**Issue by MoppieMop** [FluidTYPO3/vhs#858]
This took my literally hours.
I had following TS:
```
plugin.tx_vhs.settings.asset {
	mainCss {
		path = EXT:speciality/Resources/Public/Build/StyleSheets/site.min.css
		group = css
		standalone = 1
		rewrite = 0
		type = css
	}
}
```
The Problem was the extension does not exist, because I renamed it. The real problem was, that vhs was generating ```<style type="text/css" />``` which is invalid and break the whole markup.
Please prevent that such an element is generated, same for ```<script />```. If we have an empty style use ```<style type="text/css"></style>```

**Comment by NamelessCoder** [comment]
Sorry to hear about the hours, @MoppieMop. I agree, this must be fixed by just forcing a closing tag, always, regardless of content or not, when generating `<style>` tags. If whomever handles this is extra nice, maybe it would be good to include a little comment in the merged file when a resource could not be resolved. You know, for debugging ^^

**Comment by bjo3rnf** [comment]
I wonder why vhs would even render the tag and not complain about the not existing asset which I stumble across in almost every project :S I'm on it.

**Comment by NamelessCoder** [comment]
> I wonder why vhs would even render the tag and not complain about the not existing asset which I stumble across in almost every project :S I'm on it.

That's a very fair question indeed. I'm sorry to say that if there is a reason, I don't recall it. If we re-evaluate that situation then maybe it would be best to just ignore empty assets and throw a line in the `sys_log` or even `devlog`. I think if we throw them at `devlog` they get presented as nice messages in the backend if the extension is installed - and are ignored if it is not, which would be pretty good for dev/production.
