### ISSUE TITLE
once.session is using $_SESSION instead of TYPO3 session handling

### ISSUE THREAD

**Issue by nige-one** [FluidTYPO3/vhs#860]
Hi there,
while playing with v:once.session I just saw PHP's $_SESSION var is used. Maybe it's a better idea to use $GLOBALS['TSFE'] so one can access it with TypoScript etc.

Just a thought.

**Comment by bjo3rnf** [comment]
Hi @nige-one,
thanks for your comment. I think the use of $_SESSION in this context is perfectly fine as the functionality of the viewhelper is quite specific and encapsulated.
Cheers
Björn
