### ISSUE TITLE
AbstractMenuViewHelper - argument 'forceAbsoluteUrl' is missing

### ISSUE THREAD

**Issue by rastocs2** [FluidTYPO3/vhs#861]
would be good have argument forceAbsoluteUrl in AbstractMenuViewHelper

**Comment by bjo3rnf** [comment]
Why not use ``absRefPrefix`` in TS for that?

**Comment by rastocs2** [comment]
because absRefPrefix isn't supported by all extensions (e.g. realurl has problem with this sometimes)
because absRefPrefix is used always and we want to use also relative links
... etc ...
AbstractMenuViewHelper uses typolink for create link and typolink has support for forceAbsoluteUrl, so i think would be good if also AbstractMenuViewHelper has support for forceAbsoluteUrl
