### ISSUE TITLE
v:page.resources.fal doesn't respect language overlays

### ISSUE THREAD

**Issue by markus-k** [FluidTYPO3/vhs#862]
The ViewHelper ```v:page.resources.fal()```does not respect the fact that ```pages``` uses a different table in foreign languages. It should also use ```pages_language_overlay``` next to ```pages```, when the language is > 0. 

So ```{v:page.resources.fal(record: currentPage)}``` returns only images from the default language and no translated ones.

**Comment by mrk131324** [comment]
With the current version in dev-development (930c5f0) the language overlay causes an exception in `TYPO3\CMS\Core\Utility\ArrayUtility::mergeRecursiveWithOverrule()`.

Solution is simple:

Replace `Classes/ViewHelpers/Page/Resources/FalViewHelper.php:64` with
```php
if (is_array($localisation)) ArrayUtility::mergeRecursiveWithOverrule($pageRecord, $localisation);
```

**Comment by ogrosko** [comment]
Hi 
On version 2.4.0 (typo3 v 7.6.4) v:page.resources.fal doesn't respect language overlays again

in file 
`/typo3conf/ext/vhs/Classes/ViewHelpers/Resource/Record/FalViewHelper.php`

method

`getResources`

and line 

`$images = $this->getFileReferences($this->getTable(), $this->getField(), $sqlRecordUid);`

$this->getTable() does not respect sys_language_uid and is still "pages"

**Comment by ogrosko** [comment]
Temporary i fix this bug adding this line of code
`($GLOBALS['TSFE']->sys_language_uid !== 0 && $table == 'pages') ? $table = 'pages_language_overlay' : '';`

to file `/typo3conf/ext/vhs/Classes/ViewHelpers/Resource/Record/FalViewHelper.php` on line 63
