### ISSUE TITLE
problem with v:once.session

### ISSUE THREAD

**Issue by oliverbeck** [FluidTYPO3/vhs#863]
Hi

I want to show an image once per session, so i tried the according viewhelper like that (see attached image)
![screensh](https://cloud.githubusercontent.com/assets/2969451/8797044/59e8c7be-2f99-11e5-8362-0c6f2cd0d199.JPG)
:

But the image is rendered on every pageload.

Did I use it the correct way?

**Comment by NamelessCoder** [comment]
Hi Olivier,

Maybe you are using the ViewHelper in a cached context? Since it relates to the session it has to be in an uncached context - for example, via a `USER_INT` or only on pages where the page cache is disabled. Hope that explains it!

**Comment by NamelessCoder** [comment]
Taking the liberty of closing this one, partly due to missing feedback and partly due to assuming that the suggested explanation is the correct one.
