### ISSUE TITLE
LanguageMenuViewHelper - inactive vs current

### ISSUE THREAD

**Issue by rastocs2** [FluidTYPO3/vhs#871]
"inactive" has higher priority than "current" :
<pre>
			if (TRUE === (boolean) $var['inactive']) {
				$classes[] = 'inactive';
			} elseif (TRUE === (boolean) $var['current']) {
				$classes[] = $this->arguments['classCurrent'];
			}
</pre>
i think that it have be opposite
<pre>
			if (TRUE === (boolean) $var['current']) {
				$classes[] = $this->arguments['classCurrent'];
			} elseif (TRUE === (boolean) $var['inactive']) {
				$classes[] = 'inactive';
			}
</pre>

example:
page has 3 languages: DE (default), EN, FR
but wasn't created translations for EN and FR
if user is on the page with DE language then menu looks like this:
![img1](https://cloud.githubusercontent.com/assets/5691082/8876776/22ee79d0-3222-11e5-8d24-e0ed6f74cdd9.png)
this is ok
but then click e.g. on FR and menu looks like this:
![img2](https://cloud.githubusercontent.com/assets/5691082/8876830/771e1fe2-3222-11e5-82d9-ad29d83a029f.png)
by me it's not ok, because he don't see that FR is now current language
correct would be this:
![img3](https://cloud.githubusercontent.com/assets/5691082/8876900/daa0daf0-3222-11e5-98de-935c00939699.png)

**Comment by bjo3rnf** [comment]
But you mentioned there's no translation for FR?

**Comment by rastocs2** [comment]
yes, page isn't translated, but is set content_fallback, so in link is FR but it display content from default language

**Comment by bjo3rnf** [comment]
Ah, ok. What about assigning both classes current and inactive?

**Comment by rastocs2** [comment]
i don't think it's good idea with both, can be problem with css
in this case is important current, so inactive is not needed

**Comment by xf-** [comment]
i think both is better, because. you can style the case .current.inactive

**Comment by bjo3rnf** [comment]
I'd prefer both classes as well. We can see from your example that a language may be inactive but current at the same time so this special case can be styled accordingly.

**Comment by rastocs2** [comment]
ok, agree
