### ISSUE TITLE
[FEATURE] Gravatar viewhelper

### ISSUE THREAD

**Issue by xf-** [FluidTYPO3/vhs#884]
Gravatar can be useful to get an "valid" userImage and user can maintain it. Should function like youtube viewhelper. Return URI (custom integration) or image tag in proper size which is an argument in viewhelper.

PHP example:
https://en.gravatar.com/site/implement/images/php/

(Never used profile stuff from Gravatar)

**Comment by NamelessCoder** [comment]
Under review in a likely-to-pass shape.
