### ISSUE TITLE
HasValidatorViewHelper doesn't support compiled rendering

### ISSUE THREAD

**Issue by thomasblass** [FluidTYPO3/vhs#893]
The HasValidatorViewHelper seems to have the same Problems under Typo 7.3 like the ExistsViewHelper in Issue #851 . 
I think there are some more ViewHelper which should be adjusted to be compatible with the Upcoming LTS Version.

**Comment by xf-** [comment]
I think also conditions like isArray have problems in v7

**Comment by mneuhaus** [comment]
i started working on the ConditionViewHelpers loads of them are failing in cached 7.3 currently.
will continue tonight with the rest.

**Comment by xf-** [comment]
+1 :)

**Comment by NamelessCoder** [comment]
Solution under review and expected to pass some time during the day tomorrow.
