### ISSUE TITLE
use ArrayConsumingViewHelperTrait inside class AbstractAssetViewHelper not allowed?

### ISSUE THREAD

**Issue by wrock** [FluidTYPO3/vhs#895]
According to scoping rules a use-command should not be inside a class.
-> Get an error (PHP 5.3.10)

If I remove the line 40 in 
typo3conf/ext/vhs/Classes/ViewHelpers/Asset/AbstractAssetViewHelper.php
the Viewhelper works fine.

**Comment by bjo3rnf** [comment]
Hi,

traits have been introduced in PHP 5.4 thus the error. vhs requires at least PHP 5.4 since 5.3 is end of life for quite some time now.

Cheers
Björn

**Comment by cedricziel** [comment]
PHP 5.3 is EOL.

Upgrade your system-we intentionally do not support older versions.

Cheers,
Cedric
