### ISSUE TITLE
[FEATURE] v:format.replace additional parameter for case-insensitive replace

### ISSUE THREAD

**Issue by Kaimane** [FluidTYPO3/vhs#897]
Using an additional parameter (e. g. "casesensitive") to use case-sensitive (str_replace()) or case-insensitive (str_ireplace()) replacement with this viewhelper.

By default casesensitive parameter is set to "true" so that the viewhelper uses str_replace() method. But if casesensitive parameter is set to "false" the viewhelper will use str_ireplace() for case-insensitive replacement.

What do you think?

**Comment by xf-** [comment]
Sounds useful.
PR with unit test is welcome :)

**Comment by NamelessCoder** [comment]
If you do go ahead and create a PR, the right name for the attribute would be `caseSensitive` (note casing - no pun intended), to match `v:format.eliminate` et al.

**Comment by bjo3rnf** [comment]
Hi @Kaimane,

still interested in this view helper? If you don't have the time to create a PR I can take care of it. Please give some feedback, thanks.

**Comment by InvisibleKind** [comment]
I've added a comment at commit. Seems, that new parameter isn't taken into account:
https://github.com/FluidTYPO3/vhs/commit/2a1773d1b39f3ebaa9bcbc024417342f0c2dcbb0#commitcomment-13791127
