### ISSUE TITLE
v:page.menu does not respect group-rights

### ISSUE THREAD

**Issue by MoppieMop** [FluidTYPO3/vhs#898]
I have an extension sfpipauth (old, but working) with which I can auto-assign a group to any visitor of my page. The visitor does not have any fe_user-login, but he has a fe_group ("anon").
But this user cant see pages (in the menu) visible for the fe_group "anon".
If I create the menu with TS (HMENU) the visitor can see this pages, but with v:page.menu it doesnt work. (Same for fluidcontent_core Menu-element).

**Comment by bjo3rnf** [comment]
Hi @MoppieMop,

so the group "anon" doesn't have any restrictions but is simply some sort of "tag" to have a defined state? There _are_ some group checks in vhs' page select service which might cause this.

**Comment by MoppieMop** [comment]
Hello @bjo3rnf,
with your advice of PageSelectService I found the problem. In ```createPageSelectInstance()``` therer is only asked if a user exist, but in my case there is no user - only a usergroup.
So I would suggest to change
```
...
if (TRUE === is_array($GLOBALS['TSFE']->fe_user->user)) {
...
```
to
```
...
if (TRUE === is_array($GLOBALS['TSFE']->fe_user->user) ||
    FALSE === empty($GLOBALS['TSFE']->fe_user->groupData['uid'])) {
...
```
If you dont see any mistake I can do a pull request.

**Comment by bjo3rnf** [comment]
Hi @MoppieMop,

yes, I'd appreciate a PR for better discussion (if required).

Thanks.

**Comment by bjo3rnf** [comment]
Closing this issue for now after the proposed fix has been merged. Feel free to reopen.
