### ISSUE TITLE
v:page.header.link has no effect when used in templates of uncached extbase actions

### ISSUE THREAD

**Issue by JostBaron** [FluidTYPO3/vhs#900]
If the ViewHelper is used in the template of an uncached action, the `<link>` tag is added *after* the marker array has been generated (in `getPreparedMarkerArrayForPageWithUncachedObjects` in `PageRenderer.php`). Thus the link tag will not be present in the output.

It works fine in fluidpage templates and in templates of cached actions.

**Comment by JostBaron** [comment]
Any workarounds on this? It's quite hard to generate the links from places other than fluid... it would at least produce a lot of doubled logic.

**Comment by NamelessCoder** [comment]
There are no workarounds to my knowledge. However, I have seen a few commits about PageRenderer assets cached/uncached in the past so it could be coming. I just don't know for sure.
