### ISSUE TITLE
private methods

### ISSUE THREAD

**Issue by wazum** [FluidTYPO3/vhs#902]
Sorry, but private methods are a pain in the a$$ … don't know why you use them … 
I just want to overwrite a method in Service\AssetService, but that's impossible because of this $$§§§!! 
Now I have to duplicate everything (completely unnecessary).

Any possibility you change this in the (very near) future? protected should be enough, no?

**Comment by NamelessCoder** [comment]
Sorry to hear you poked yourself on one of our rusty old nails. [Here you go](https://github.com/FluidTYPO3/vhs/commit/e79bf9556769258c60e800a228493d5628216b47).
