### ISSUE TITLE
Image URLs broken when absRefPrefix is set

### ISSUE THREAD

**Issue by pkerling** [FluidTYPO3/vhs#915]
The following line:
https://github.com/FluidTYPO3/vhs/commit/4db4ed567f74e3fef25c452fe5d6d337dc79c615#diff-dd3c40c66dd2d2443cb3e8be9e0cf6d6R48
causes all frontend image URLs to become `/typo3//typo3/test.png` instead of `/typo3/test.png` when the image name is `test.png` and TS `config.absRefPrefix` is set to `/typo3/`. Consequently, all FE images rendered through vhs are broken. I am using TYPO3 6.2.14.

**Comment by NamelessCoder** [comment]
@bjo3rnf Would you mind snuffing this one? It might be in more ViewHelpers too.
