### ISSUE TITLE
v:render.uncache stopped working (for me) after upgrading from EXT:flux 7.2.0 to 7.2.2

### ISSUE THREAD

**Issue by uweschmelzer** [FluidTYPO3/vhs#919]
### My problem:
This works fine:
`<f:render partial="Test" arguments="{_all}"/>`

This triggers an error message:
`<v:render.uncache partial="Test" arguments="{_all}"/>`

It seems like FLUID cannot find the partial, when I use `<v:render.uncache/>`.
FLUID looks for the right partial, but in the wrong extension directory.

Is there anything I can do, to fix this?

### Example:
The partial is in this dir
/html/typo3conf/ext/**test1**/Resources/Private/Partials/Test.html
But FLUID looks in this dir
/html/typo3conf/ext/**fluidpages**/Resources/Private/Partials/Test.html
Thus, the partial is not found and I get an error message (See below).

### What did I do to cause this?
I upgraded from EXT:flux 7.2.0 to 7.2.2

### My environment
-PHP 5.5/Apache2/Mac
-Typo3 6.2.15 + latest Fluid powered Typo3 Extensions +  EXT:speciality

### How to recreate this behaviour:
Testcase 1
Create a partial named Test.html and add this line to your FLUID template e.g. in EXT:speciality
`<v:render.uncache partial="Test" arguments="{_all}"/>`

Testcase 2
-Please download Test1-Extension
http://www.file-upload.net/download-10941975/test1_0.0.1_201509291809.zip.html
-Please install the extension
-Use the pagelayout provided by the extension, or use the FE Plugin provided by the extension. Both will trigger the error. 

## Full error message:
Uncaught TYPO3 Exception
#1225709597: The template files "/html/typo3conf/ext/fluidpages/Resources/Private/Partials/Test.html", "/html/typo3conf/ext/fluidpages/Resources/Private/Partials/Test" could not be loaded.

TYPO3\CMS\Fluid\View\Exception\InvalidTemplateResourceException thrown in file
/Volumes/local/html/typo3_src-6.2.15/typo3/sysext/fluid/Classes/View/TemplateView.php in line 477.

## Strange thing
The line `<v:render.uncache partial="Test" arguments="{_all}"/>` which triggered the error above works just fine, when I use it directly in EXT:typo3conf/ext/fluidcontent_core/Resources/Private/Templates/CoreContent/Html.html

**Comment by NamelessCoder** [comment]
Fixed (all extension context related issues) in https://github.com/FluidTYPO3/flux/commit/dcd6132042e5f8b670f443e6b74398ae8c4db6b6 and will be in next TER release. You can roll back to 7.2.2 or use the development branch until then.

**Comment by typo3ua** [comment]
In my case, this not helped me...
I change:
```
from...
<f:render partial="List/Items/MyItem" arguments="{_all}"/>
to...
<v:render.uncache partial="List/Items/MyItem" arguments="{_all}"/>
```
I see...
```
Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1225709597: The partial files "/typo3conf/ext/news/Resources/Private/Partials/List/Items/MyItem.html", "/typo3conf/ext/news/Resources/Private/Partials/List/Items/MyItem" could not be loaded. | TYPO3\CMS\Fluid\View\Exception\InvalidTemplateResourceException thrown in file /typo3/sysext/fluid/Classes/View/TemplateView.php in line 478. Requested URL: http://domain.my/my-page.html
```
In my case, he searches "Partials" in directory "news" and not in my "mysite"...

Version:
TYPO3 7.6.16
FLUX 7.3.0
VHS 3.1.0
FLUID 7.6.0
