### ISSUE TITLE
v:page.header.canonical does not work with realurl and news

### ISSUE THREAD

**Issue by ilomedia** [FluidTYPO3/vhs#921]
Hi all,
Latest TER version, the canonical viewhelper fails to render the correct URL with extra parameters.

For a news item for example the canonical URL should be https://my.domain.tld/article/my-title.html but ends up as https://my.domain.tld/article.html

I use fixedpostvars with realurl :
array(
										'GETvar' => 'tx_news_pi1[news]',
										'lookUpTable' => array(
												'table' => 'tx_news_domain_model_news',
												'id_field' => 'uid',
												'alias_field' => "REPLACE(title, '\'', '-')",
												'addWhereClause' => ' AND NOT deleted',
												'useUniqueCache' => 1,
												'useUniqueCache_conf' => array(
														'strtolower' => 1,
														'spaceCharacter' => '-',
												),
												'languageGetVar' => 'L',
												'languageExceptionUids' => '',
												'languageField' => 'sys_language_uid',
												'transOrigPointerField' => 'l10n_parent',
												'autoUpdate' => 1,
												'expireDays' => 180,
										)
								)

**Comment by bjo3rnf** [comment]
Hi @ilomedia,

mind giving https://github.com/bjo3rnf/vhs/commit/7dabf3404158a2a1987cc6c4149e526147711c4d a spin if it solves your issue? Thanks in advance.

**Comment by bjo3rnf** [comment]
Hi @ilomedia,

a possible fix for your issue has been merged. I'm taking the freedom to close this issue for now. Feel free to reopen if it doesn't work out for you.

Cheers
Björn

**Comment by ilomedia** [comment]
Hi @bjo3rnf,

i realized in issue #938 that my installed version was actually not the lastest. In fact my server is stucked with RHEL6 and PHP 5.3.3 and therefore TYPO3 did not propose me the updates (that's why i thought i was up to date).

Therefore i can not test this fix and i'm not even sure that the bug exists in the latest version.
