### ISSUE TITLE
{v:content.resources.fal(field: 'settings.image')} doesn't work

### ISSUE THREAD

**Issue by lukepower** [FluidTYPO3/vhs#926]
Hi there, giving the following template code:
```
<flux:form id="gallery" wizardTab="MG">
		<flux:field.checkbox name="showMap" label="Show Map" />
		<flux:field.inline.fal name="settings.images" multiple="TRUE" maxItems="20" required="0" collapseAll="true" />
</flux:form>
```
And
```
<f:for each="{v:content.resources.fal(field: 'settings.image')}" as="imageFal">
				<f:if condition="{imageFal.url}">
					<img src="<v:format.replace substring=".." content="{f:uri.image(src: '{imageFal.id}', maxHeight: '100', treatIdAsReference: true)}" replacement="" />" />
				</f:if>
			</f:for>
```

This worked well until I installed the latest releases of vhs, fluidpages and fluidcontent. I really am struggling to get it to work again. In the backend, the images show up correctly, but in the frontend it seems tha tI am unable to access them.

**Comment by NamelessCoder** [comment]
@lukepower Did you *also* upgrade the TYPO3 core to version 7.5+? There is a lot of stuff broken in the new FormEngine concerning resolving IRRE relations used inside FlexForms and I suspect you face one or more of those.

**Comment by lukepower** [comment]
No, the Typo3 Core has not been updated.

 

Von: Claus Due [mailto:notifications@github.com] 
Gesendet: Dienstag, 10. November 2015 14:20
An: FluidTYPO3/vhs <vhs@noreply.github.com>
Cc: lukepower <lukas@lukepower.com>
Betreff: Re: [vhs] {v:content.resources.fal(field: 'settings.image')} doesn't work (#926)

 

@lukepower <https://github.com/lukepower>  Did you also upgrade the TYPO3 core to version 7.5+? There is a lot of stuff broken in the new FormEngine concerning resolving IRRE relations used inside FlexForms and I suspect you face one or more of those.

**Comment by NamelessCoder** [comment]
What is your current version of TYPO3 and versions of FluidTYPO3 extensions, namely VHS and Flux?

**Comment by lukepower** [comment]
Typo3: 6.2.15

VHS: 2.3.3

Flux: 7.2.2

 

However, at the end I was able to somehow fix it:

 

<flux:field.inline.fal name="settings.images" multiple="TRUE" maxItems="20" required="0" />

 

And

<f:if condition="{v:page.resources.fal(field: 'settings.images')}==0">

                                                               <f:then>

                                                                 <f:cObject typoscriptObjectPath="plugin.tx_maagrandomimage_pi1" />

                                                               </f:then>

                                                               <f:else>

                                                                 <f:for each="{v:page.resources.fal(field: 'settings.images')}" as="image">

                                                                              <f:render section="Item" arguments="{_all}" />

                                                               </f:for>

                                                               </f:else>

                                               </f:if>   

 

 

 

Von: Claus Due [mailto:notifications@github.com] 
Gesendet: Dienstag, 10. November 2015 15:05
An: FluidTYPO3/vhs <vhs@noreply.github.com>
Cc: lukepower <lukas@lukepower.com>
Betreff: Re: [vhs] {v:content.resources.fal(field: 'settings.image')} doesn't work (#926)

 

What is your current version of TYPO3 and versions of FluidTYPO3 extensions, namely VHS and Flux?

**Comment by NamelessCoder** [comment]
In that case let's close this issue ;)

For more information about the problems I mentioned with FormEngine, see https://github.com/FluidTYPO3/flux/pull/1003 - our ViewHelper documentation will be updated soon to reflect this, too.
