### ISSUE TITLE
Async/defer for asset.script

### ISSUE THREAD

**Issue by InvisibleKind** [FluidTYPO3/vhs#927]
Small feature request to add these two attributes to v:asset.script.

**Comment by bjo3rnf** [comment]
See vhs#625

**Comment by bjo3rnf** [comment]
But: As far as I can tell this would require to exchange tag builder with a lightweight custom implementation to render the attribute without a value (HTML5 style) and force attribute ``standalone`` to be set on those assets with either ``async`` or ``defer``.  No big deal. Any obligations?

**Comment by bjo3rnf** [comment]
Closing this one after discussing the implications that are still existing and impossible to workaround in the current implementation.

**Comment by NamelessCoder** [comment]
It's sad to say but I completely agree - although we don't like doing it, we have to give up in advance on this case. There's just too much standing in the way of it working.
