### ISSUE TITLE
v:media.image, Argument "srcset" was not registered.

### ISSUE THREAD

**Issue by Atsyn** [FluidTYPO3/vhs#929]
In documentation https://fluidtypo3.org/viewhelpers/vhs/master/Media/ImageViewHelper.html we can see argument srcset but in extension this argument not included.
TYPO3 7.5.3
Extension version 2.3.3

**Comment by cedricziel** [comment]
The argument is available in the current development release and will probably slip into the next TER release. You can use a git clone in the meantime.

Thx for the hint.
