### ISSUE TITLE
Parse error: syntax error, unexpected T_USE, expecting T_FUNCTION

### ISSUE THREAD

**Issue by r4fx** [FluidTYPO3/vhs#932]
I got strange error in one of my projects with `v:iterator.explode`

Parse error: syntax error, unexpected T_USE, expecting T_FUNCTION in /home/www/project/typo3conf/ext/vhs/Classes/ViewHelpers/Iterator/ExplodeViewHelper.php on line 26

with this code 
```
<f:for each="{settings.groups -> v:iterator.explode(glue: ',')}" as="group">
     <f:cObject typoscriptObjectPath="lib.nnAddressGroupTitle" data="{uid:'{group}'}"/>
</f:for>
```

**Comment by cedricziel** [comment]
Sounds like an old interpreter. A really old interpreter.

**Comment by NamelessCoder** [comment]
Update your PHP version to at least 5.4. No older versions are supported.
