### ISSUE TITLE
PdfThumbnailViewHelper renders no thumbnails

### ISSUE THREAD

**Issue by tiggerduck** [FluidTYPO3/vhs#933]
In the PdfThumbnailViewHelper-Class the render-method called the parent::render-Method with some parameters.
But ImageViewHelper->render has no parameters........
So the new pdf-thumbnail src will not transfered to ImageViewHelper.

**Comment by bjo3rnf** [comment]
To fix this adapting recent changes in image rendering viewhelpers is required which in turn are supposed to be refactored regarding inheritance/traits. This is currently in work. You can expect a fix shortly.

**Comment by cedricziel** [comment]
_bump_

**Comment by bjo3rnf** [comment]
@cedricziel I know, I know... I updated my comment. If someone else is equipped with some spare time feel free to take over.

**Comment by huersch** [comment]
May be not the best solution but works fine for me:
 <v:media.pdfThumbnail src="" path="{url}" />
and then in PdfThumbnailViewHelper.php add this lines after line 82 ($image = substr($destination, strlen(PATH_site));

if (!($this->arguments['src']))
	$this->arguments['src'] = $image;
