### ISSUE TITLE
Responsive image ViewHelpers ahving wrong fallback src

### ISSUE THREAD

**Issue by Razrael** [FluidTYPO3/vhs#937]
When using the Media.image ViewHelper we discovered that the smallest srcset option is uses as a fallback for the src attribute.
In internet Explorer, where srcsets are not used, we get the smallest image for the Fallback. This is not desired in most cases since IE is mostly used on desktops.

I propose to remove the [ksort in the trait](https://github.com/FluidTYPO3/vhs/blob/development/Classes/Traits/SourceSetViewHelperTrait.php#L50), so we use the first defined srcset. In this case we are able to select the src by just order the srcsets accordingly.

**Comment by bjo3rnf** [comment]
Hi @Razrael,

as stated in the documentation ``srcset`` is not supported by Internet Explorer at all and you'll have to include some polyfill if you require to support those browsers. 

Feel free to reopen this issue if you need further assistance.

Cheers
Björn

**Comment by Razrael** [comment]
Hi @bjo3rnf 

I know that `srcset` is not availlable in Internet Explorer and I have no problem with that. I don't need it there.
The problem is that the `src` attribute get filled with the wrong (smallest) image size, so this fallback does not work anymore because images get pixelated.
This could easily be changed in the view helper.

**Comment by NamelessCoder** [comment]
I think we need to summon @mneuhaus who if I recall was involved in this srcset feature. Is there a specific reason (compat?) we're ksort'ing the sources?

**Comment by mneuhaus** [comment]
we discussed this a little bit, i have thought in the back of my head that says, that the browser walks those srcsets by that order an takes the first one thats wide enough, that's why i did that ksort there. 
But to be honest i can't find the doc to prove it currently.
i'll implement a little change as soon as my composer over here starts behaving (shitty hotel wifi) 
that will use the first size specified as srcset as the default and still use the ksort after that.

**Comment by bjo3rnf** [comment]
Hi @Razrael,

please take a look at #947 which should solve your issue for good.

Cheers
Björn

**Comment by Razrael** [comment]
Hi @bjo3rnf 

Thanks for your work. I will test it early next week and give you a feedback here.

**Comment by InvisibleKind** [comment]
Maybe I don't get the topic, but why do we need to introduce *'srcsetDefault'* attribute, which contains width of image for browsers, which do not support srcset, when we already have *'width'*, which serves exactly for same purpose?

**Comment by bjo3rnf** [comment]
Because now a derivate of the original image is created in the dimensions of the default image. Using ``width`` only the tag attribute is added.
