### ISSUE TITLE
Use of deprecated method $GLOBALS['typo3CacheManager']

### ISSUE THREAD

**Issue by ilomedia** [FluidTYPO3/vhs#938]
my deprecation log says :
```
05-11-15 16:01: Usage of $GLOBALS['typo3CacheManager'] and $GLOBALS['typo3CacheFactory'] are deprecated since 6.2 will be removed in two versions. Use \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance('TYPO3\CMS\Core\Cache\CacheManager') or dependency injection to access the singletons.
```

i found 3 occurences of $GLOBALS['typo3CacheManager'] in vhs code.

**Comment by mneuhaus** [comment]
hey :)

yes, ```$GLOBALS['typo3CacheManager']``` is still in the code, but it's already prepared for the case when it goes away, since we want to support old TYPO3 versions as well, we'll leave it in there for now:

```php
$cacheManager = isset($GLOBALS['typo3CacheManager']) ? $GLOBALS['typo3CacheManager'] : GeneralUtility::makeInstance('TYPO3\\CMS\\Core\\Cache\\CacheManager');
```

**Comment by ilomedia** [comment]
Sorry about that, i've just realized that my vhs version is version is 2.2.0 and that for some unknown reason Extension manager does not propose any update (event if i updated my extension list)

I guess i'll have to check all my versions manually :(

**Comment by mneuhaus** [comment]
:/ yea plenty of providers don't keep up properly. right now there's nothing really to do so i hope you're ok with me closing this issue. if not, feel free to hit me up :)
