### ISSUE TITLE
page.resource.fal overlays with deleted pages_language_overlay

### ISSUE THREAD

**Issue by mrk131324** [FluidTYPO3/vhs#953]
The method 

`vhs/Classes/ViewHelpers/Page/Resources/FalViewHelper.php->getSlideRecordsFromPage()`

Performance a page overlay for translations without enableFields(). Therefor, deleted, hidden and workspace records will be found as well. 

All in all, there are a lot non standard translation overlay processes throughout the whole TYPO3 flux/fluid project. I would recommend to refactor them all to use TYPO3 API standard methods.

**Comment by typo3ua** [comment]
Yes, I have a problem with that also... in version 2.4.0

**Comment by bjo3rnf** [comment]
This should be fixed now by the above patch so I take the liberty of closing this issue. Please reopen it in case it requires some extra work.

**Comment by neufeind** [comment]
tested with current released version (2.4.0) as well as development-version from git.
Works fine for the file-metadata itself. But when sys_file_reference is used to override a title/description that takes precendence - and the translated sys_file_reference is not taken into account. Workaround so far is only to use sys_file_metadata and not the title from sys_file_reference.

**Comment by NamelessCoder** [comment]
Now uses PageRepository for fetching these relations. If misbehaviors remain, we will need to address those in TYPO3 CMS.
