### ISSUE TITLE
Fetch single column only in v:resource.record when field is specified

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/vhs#961]
`v:resource.record` does a `SELECT *`, even though through `field` only a single column is used in the end.

Instead of fetching all data, only the column specified by the `field` attribute should be fetched.

**Comment by NamelessCoder** [comment]
I'll take a little risk and reject this one with the following reasons:

* The method in which this would be changed is used by more than one class (standard FAL ViewHelper, content FAL ViewHelper, page FAL ViewHelper and so on).
* Access in classes involves at least two other fields: a dynamic "id field" that pulls for example `uid` or another column that identifies the record, and `t3ver_oid` which gets used in workspaces supports.
* Restricting the field selections could cause values to be missing in future additions of resources-attached-to-records ViewHelpers or userland ViewHelpers which are encouraged by this structure.
* The performance increase is negligible in the end.

That being said, we should be aiming for wider use of prepared SQL statements in these ViewHelpers and others, and in general throughout FluidTYPO3. This should be a much greater benefit than limiting our field inclusions ;)

Hopefully you understand and agree - if not, please feel free to discuss with me on IRC.
