### ISSUE TITLE
[BUG] Asset/AbstractAssetViewHelper

### ISSUE THREAD

**Issue by AMTkkasprzyca** [FluidTYPO3/vhs#964]
Hello

I think there is a possible bug when property `movable` is used by `<v:asset.script />` and `<v:asset.style />`. Condition from line 361 always returns `TRUE` and it overwrites this setting to `TRUE` (default value for `allowMoveToFooter`)

Tested with vhs 2.4.0

**Comment by dmitryd** [comment]
I can confirm that movable="0' has no effect at all because it is always overriden by the default value of allowMoveToFooter.

In my opinion "movable" is not as clear as allowMoveToFooter. I prefer the latter :)
