### ISSUE TITLE
v:security.allow does not work in fluidcontent elements (caching)

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/vhs#975]
When using `<v:security.allow admin="1">` inside a  fluidcontent frontend element, the `<f:then>` branch is only used when the content element has not been cached yet.

Loading the page with the element a second time always executes the `<f:else>` branch, no matter if I'm an admin user.
Only clearing the system cache or modifying the content element template makes it work for a single time again.

```
<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en"
     xmlns:f="http://typo3.org/ns/TYPO3/Fluid/ViewHelpers"
     xmlns:flux="http://typo3.org/ns/FluidTYPO3/Flux/ViewHelpers"
     xmlns:v="http://typo3.org/ns/FluidTYPO3/Vhs/ViewHelpers">
  <f:layout name="Content" />

  <f:section name="Configuration">
    <flux:form id="securitytest">
    </flux:form>
  </f:section>

  <f:section name="Main">
    <v:system.timestamp/>
    <v:security.allow admin="1">
      <f:then>I am admin!</f:then>
      <f:else>NO admin</f:else>
    </v:security.allow>
  </f:section>
</html>
```

Seems to be related to #116.

**Comment by cweiske** [comment]
Removing the `CompilableInterface` from `typo3/sysext/fluid/Classes/Core/ViewHelper/AbstractConditionViewHelper.php` makes it work, but that breaks of course most caching in fluid :)

**Comment by NamelessCoder** [comment]
I'll take the liberty of closing this issue with a reference to this TYPO3 issue: https://forge.typo3.org/issues/73565

When that one gets corrected we can adopt to whichever solution they choose (I suggest a couple of them) - and we can do that for all our condition ViewHelpers at the same time. Hopefully we get a backwards compatible solution but if not, I expect this switch will not happen until TYPO3 8 LTS is released.
