### ISSUE TITLE
Support showAccessRestrictedPages in v:page.menu

### ISSUE THREAD

**Issue by NamelessCoder** [FluidTYPO3/vhs#976]
* Show pages which are inaccessible
* Option to link access restricted pages
* Property in page record "is protected" (include as CSS class in auto rendering)

**Comment by bjo3rnf** [comment]
Mmmh...Clickbait for me. What do you mean with 'Show pages which are inaccessible'?

**Comment by NamelessCoder** [comment]
Sorry about the fast notes - jotted down during a meeting where it was mentioned ;)

The problem is, given the following page tree:

* Front page (public)
  * Sub 1 (public)
  * Sub 2 (protected)
  * Sub 3 (public)

When using `<v:page.menu />` the "Sub 2" page does not get displayed. Which is correct as such, but we lack an option to make `<v:page.menu />` render the pages and links even if the target page is inaccessible. I believe in HMENU etc. this toggle is called `showAccessProtectedPages` and I seem to recall something about a `linkAccessProtectedPages` property for menus, too (which if FALSE outputs the page title but no link around it).

There *is* a public property on the PageRepository that may govern this behavior. If so, we'd need a pretty simple new argument and just setting that property before we pull pages.

There are two additional requirements that should be filled at the same time:

* In both manual and automatic menu rendering any inaccessible page should have an additional CSS class (to allow changing link icons, muting text, etc)
* When menus are rendered manually the page records should have a new property which indicates if the target page is access protected (to allow checking that property to do further custom rendering)

The actual use case is that one of our users, Systime here in Aarhus, are rendering so-called iBooks (interactive eBooks) as TYPO3 sites and use a previewing method where the first couple of chapters are public and the rest are rendered with a small lock icon until users log in. Protected pages are shown to give a small teaser and further impression about what's contained in the book. Currently they have to pull the page lists manually or use HMENU to get those protected pages rendered in the menu.

Hope that explains it!

**Comment by bjo3rnf** [comment]
> Hope that explains it!

Absolutely, thanks.

**Comment by bjo3rnf** [comment]
Should a page be marked 'accessProtected' also if access is allowed for the current user?

**Comment by bjo3rnf** [comment]
> Should a page be marked 'accessProtected' also if access is allowed for the current user?

Well, I propose they should and get another class like 'access-granted' or something.

**Comment by NamelessCoder** [comment]
A CSS class sounds like a nice way to indicate that. But for those doing manual iteration of menu items we should also have a dedicated property in the menu array.

**Comment by bjo3rnf** [comment]
Yes. I currently have ``$page['accessProtected']`` and ``$page['accessGranted']``.

**Comment by NamelessCoder** [comment]
Perfect - that should be enough to solve all use cases :)

**Comment by robbl** [comment]
Any progress? We have a lot of navigations build with fluid and don't want to go back to TypoScript. :) Can you point me to any workaround (overriding a class, etc.) for now?

**Comment by bjo3rnf** [comment]
@robbl the refactored code in #987 is in a very early stage but it's there ;) Testing it is highly appreciated.

**Comment by NamelessCoder** [comment]
#987 is now merged.
