### ISSUE TITLE
Which is now the last 6.2 compatible version? 

### ISSUE THREAD

**Issue by DenisMir** [FluidTYPO3/vhs#977]
At the moment I am getting offered to install vhs 2.4.0 from the TYPO3 extension manager in 6.2 LTS. But when reading through the changelog file of version 2.4.0 I see `Support of TYPO3 6.2 dropped`. So I assume that it is not save to install 2.4.0 on 6.2 LTS. Is this correct?

**Comment by NamelessCoder** [comment]
2.4.0 is not considered safe to use on 6.2 but in all likelihood you can still use many of the ViewHelpers from there. Officially, the minimum required version of TYPO3 to run VHS 2.4.0+ is 7.6.0 (LTS).

**Comment by DenisMir** [comment]
Please exclude the 2.4.0 release from being offered to 6.2 instance in the TER. If it is not compatible with 6.2 LTS releases it shouldn't be offered as an update.

**Comment by NamelessCoder** [comment]
Indeed - the next release we create will have the correct constraints in the manifest. Unfortunately we can't redo TER releases (at least not without significant hassle also from the TER admins) so hopefully it's Good Enough (TM) that 2.4.1 will fix the issue.

**Comment by DenisMir** [comment]
Great. Thank you very much.
