### ISSUE TITLE
[FEATURE] v:iterator.chunk on infinite chunks

### ISSUE THREAD

**Issue by githubrsys** [FluidTYPO3/vhs#986]
### Summary

AFAIU Creates chunks from an input Array/Traversable with option to allocate items to a fixed number of chunks.

But what is if you just want to group/wrap every 3 elements with e.g. an \<li\> on an infinite number of. You are busted to a very unhandy construction. AFAIK

````
<f:for each="{foo}" as="bar" iteration="cycle">
		<f:if condition="{cycle.isFirst}">
									<li>
								</f:if>
								<f:if condition="{cycle.cycle} % 3">
									<f:then>
									<f:render section="whatever" arguments="{_all}" />
									</f:then>
									<f:else>
									<f:render section="whatever" arguments="{_all}" />
										<f:if condition="{cycle.isLast}">
											<f:then></f:then>
											<f:else>
												</li>
												<li>
											</f:else>
										</f:if>
									</f:else>
								</f:if>
								<f:if condition="{cycle.isLast}">
									</li>
		</f:if>
</f:for>
````

### Question
Isn't this something that this VH could handle? Or did I get the thing wrong and it does that already?

**Comment by cedricziel** [comment]
```xml
<f:for each="{foo -> v:iterator.chunk(count: 3)}" as="barChunk" iteration="chunkCycle">
<li>
<:for each="{barChunk}" as="bar">
..
</f:for>
</li>
</f:for>
```

Is not feasible in your case?

**Comment by githubrsys** [comment]
Yes @cedricziel ... This works flawless but was and is not obvious for me in the documentation. 

That reminds me on a long discussion about the docs :-)

Nontheless. Thank you for that. I've put it into a gist and posted in library
https://gist.github.com/githubrsys/398e7cc380299cea712d

**Comment by cedricziel** [comment]
Hey David,

I'm glad it helped + I like your "solution" :)

As always: Thank you for your time.
