### ISSUE TITLE
v:condition.type.isObject does not work 

### ISSUE THREAD

**Issue by loco8878** [FluidTYPO3/vhs#990]
Setup:
TYPO3 6.2.17
vhs  2.4.0
php 5.6.17

The viewhelper render the message:
Argument "value" has already been defined, thus it should not be defined again. 

it looks like, static implementation does not work for all

**Comment by bjo3rnf** [comment]
Hi,

this issue should be fixed in the meantime so I'll take the liberty of closing it for now. Please reopen otherwise.

Cheers
Björn
