### ISSUE TITLE
v:page.languageMenu icons not working with SVG in 7.6.4

### ISSUE THREAD

**Issue by MarkusBausK** [FluidTYPO3/vhs#997]
I only like to report that `<v:page.languageMenu layout="flag" />` is not working in 7.6.4. First I thought this depends on a path-problem but after changing flagPath option to a local folder with the old png-flags it is working. If I change the images (for example deleting the de.png an putting a svg named de.svg inside) the flag is not shown. I guess the problem depends on the svg-formatted flag-icons in TYPO3 7.6.4...

**Comment by cedricziel** [comment]
I can confirm this.

**Comment by bjo3rnf** [comment]
Which TYPO3 Version came with SVG flags first?

**Comment by bjo3rnf** [comment]
Ach, nvm. VHS 2.4.0 requires TYPO3 7.6.0 or greater which has SVGs already. So there you go ;)
