### ISSUE TITLE
PHP7 compatibility

### ISSUE THREAD

**Issue by fnagel** [FluidTYPO3/vhs#999]
It seems VHS should be PHP7 ready (see #970), but the dependencies are still configured for < 7.x.

https://github.com/FluidTYPO3/vhs/blob/development/ext_emconf.php#L24
https://github.com/FluidTYPO3/vhs/blob/development/composer.json#L27

**Comment by NamelessCoder** [comment]
If there are any remaining issues with things like signatures and inheritance I'm not aware of them - I would be happy with a pull request to update the dependency metadata and allow PHP7 ;)

**Comment by bjo3rnf** [comment]
> If there are any remaining issues with things like signatures and inheritance I'm not aware of them

I just found one in AbstractMultipleMathViewHelper::calculate(). How to fix that?

**Comment by NamelessCoder** [comment]
> I just found one in AbstractMultipleMathViewHelper::calculate(). How to fix that?

Normally: change the signature if the cause is that the parent class defines it differently. But if that requires changing many other ViewHelper classes for example adding redundant function arguments, let's discuss in more detail on the team chat!

**Comment by bjo3rnf** [comment]
Constraints have been adapted to those of TYPO3 7.6.x, thanks.
